### ISSUE TITLE
Track glTexImage for cube textures targets in trace_analyzer.

### ISSUE THREAD

**Issue by mz-zajaczkowski** [apitrace/apitrace#107]
apitrace trim with --deps switch seems to leave out glTexImage calls for GL_TEXTURE_CUBE_MAP_POSITIVE/NEGATIVE_X/Y/Z. 
Is there any particular reason for that or is it just "not yet implemented" ?

**Comment by jrfonseca** [comment]
I'm afraid there are no plans to fix this -- https://lists.freedesktop.org/archives/apitrace/2017-April/001215.html
