### ISSUE TITLE
trim --trim-spec=textures doesn't seem to trim any

### ISSUE THREAD

**Issue by anholt** [apitrace/apitrace#113]
Trace at http://people.freedesktop.org/~anholt/etqw-trim2.trace

Using:

```
./apitrace trim etqw-trim2.trace -o etqw-trim3.trace --auto --trim-spec=textures
```

the file size stayed the same, which seems unlikely.

**Comment by jrfonseca** [comment]
I'm afraid there are no plans to fix this -- https://lists.freedesktop.org/archives/apitrace/2017-April/001215.html
