### ISSUE TITLE
trace_analyzer needs to track the glClear(GL_COLOR_BUFFER_BIT) calls

### ISSUE THREAD

**Issue by mz-zajaczkowski** [apitrace/apitrace#114]
At the moment i don't think a case where a frame isn't recreated from scratch, is supported.
The glClear calls need to be tracked and appropriate calls have to be added as required after clearing the color buffer but before the range specified by the user.

**Comment by jrfonseca** [comment]
I'm afraid there are no plans to fix this -- https://lists.freedesktop.org/archives/apitrace/2017-April/001215.html
