### ISSUE TITLE
Qapitrace thumbnailing uses all RAM and swap

### ISSUE THREAD

**Issue by eero-t** [apitrace/apitrace#147]
I had a 10 min/1GB trace of Nexuiz.  To see what frames I would like to trim, I thought to check the frame thumbnails.

I had to kill Qapitrace at the point when thumbnailing had consume about 8 GB RAM + 8 GB of swap and made my machine nearly completely inoperable.

IMHO thumbnailing dialog:
* Should tell how much memory thumbnailing will take
* Allow specifying that only each Nth frame will have thumbnail, and for what range of frames
* Potentially thumbnails could be saved to disk and memory mapped from there, with option for removing them at program exit.

Edit: fixed memory numbers (16GB together).

**Comment by jrfonseca** [comment]
As of commit 9f9bc14c28aed7b2571e641bfeeca81876ec48ec there's a cap on the maximum (1GB) on outstading blobs.

So this should no longer happen.
