### ISSUE TITLE
Minecraft 1.6.1 looking for NV_present_video extension

### ISSUE THREAD

**Issue by nigels-com** [apitrace/apitrace#161]
Came across this in the course of some testing today,
are they commented out of specs/glxapi.py for a known
reason?  In any case, doesn't seem fatal to tracing
Minecraft.
- Nigel

---

<pre>
Client> 2013-07-08 10:12:27 [CLIENT] [INFO] (Session ID is ...)
Client> apitrace: redirecting dlopen("libGL.so.1", 0x101)
Client> apitrace: tracing to /home/nstewart/.minecraft/java.trace
Client> apitrace: warning: unknown function "glXEnumerateVideoDevicesNV"
Client> apitrace: warning: unknown function "glXBindVideoDeviceNV"
Client> apitrace: warning: unknown function "glXBindVideoCaptureDeviceNV"
Client> apitrace: warning: unknown function "glXEnumerateVideoCaptureDevicesNV"
Client> apitrace: warning: unknown function "glXLockVideoCaptureDeviceNV"
Client> apitrace: warning: unknown function "glXQueryVideoCaptureDeviceNV"
Client> apitrace: warning: unknown function "glXReleaseVideoCaptureDeviceNV"
Client> 2013-07-08 10:12:28 [CLIENT] [INFO] LWJGL Version: 2.9.0
</pre>

**Comment by leaf918** [comment]
install glew on ubuntu
