### ISSUE TITLE
Wrong profile if eglCreateWindowSurface is called before eglCreateContext

### ISSUE THREAD

**Issue by kopkong** [apitrace/apitrace#197]
In some OpenGLES apps, we call eglCreateWindowSurface first and then call eglCreateContext. It's no problem to get a trace file on Android. but probably cause replay error.

While retracing, calling eglCreateWindowSurface before eglCreateContext. I think Visual \* createVisual get an unsupported context profile. Actually context should not have been created at this time.

Any solution ? I can easily change app's source code if I have, but I'm considering if I'm dealing with an apk without sourcecode.

**Comment by x414e54** [comment]
I am currently having this issue in relation to desktop Wayland support. 

Applications will typically call eglGetConfigs or eglChooseConfigs then eglCreateWindowSurface with one of those configs. On the call to either eglGetConfigs or eglChooseConfigs you could simply fill in a config_map and then map the original config id to the internal config id or error if a match is not available.
