### ISSUE TITLE
playback of trace causes many "glCallList" errors with GL_INVALID_VALUE

### ISSUE THREAD

**Issue by HRTAGH** [apitrace/apitrace#234]
Traceback generated with a large CAD application that uses display lists as well as immediate mode causes many "glCallList" errors such as the following

TEMP> apitrace replay test1.trace
0 4765 glCallList(list = 0)
4765: warning: glGetError(glCallList) = GL_INVALID_VALUE
0 4766 glCallList(list = 0)
4766: warning: glGetError(glCallList) = GL_INVALID_VALUE
0 4767 glCallList(list = 0)
4767: warning: glGetError(glCallList) = GL_INVALID_VALUE
0 4768 glCallList(list = 0)
4768: warning: glGetError(glCallList) = GL_INVALID_VALUE
0 4769 glCallList(list = 0)
4769: warning: glGetError(glCallList) = GL_INVALID_VALUE
0 4770 glCallList(list = 0)
4770: warning: glGetError(glCallList) = GL_INVALID_VALUE
0 4771 glCallList(list = 0)
4771: warning: glGetError(glCallList) = GL_INVALID_VALUE

The display is very incomplete, which I can only assume is because the replay is not processing the portions of the display generated by display lists.  The trace file can be downloaded from:  https://www.dropbox.com/s/gavdccbjgu87m69/test1.trace

This is all on a Windows 7, 64 bit operating system using an Nvidia Quadro 5000 graphics board with driver version 9.18.13.3165.

Interestingly, running the same trace file runs correctly without errors (and the display rendered correctly) when it's run interactively in qapitrace (using all the default settings):
TEMP>  qapitrace test1.trace

**Comment by EoD** [comment]
Are there any news on this? I just encountered the same issue and I was confused that this bug has been closed.

**Comment by jrfonseca** [comment]
@EoD, there are _ a lot _ of different issues discussed on this bug.  And I have no clue to what same issue you encountered.

You'll need to provide more detail.  But don't add them here, please file a new issue, and just refer this issue if you believe it's related.

**Comment by EoD** [comment]
The replay is super slow due to the massive error messages; at least that's what I assume. Using ``apitrace replay -b`` makes the replay smooth again.
