### ISSUE TITLE
Add a bisection tool to QApitrace

### ISSUE THREAD

**Issue by inequation** [apitrace/apitrace#257]
Localizing faulty draw calls is often a question of bisecting the stream. It would be cool if there was a tool to automate this task:

1. Choose the start call.
2. Choose the end call.
3. Click "bisect".
4. If the range between start and end has size 1, stop.
5. Determine the call in the middle of the range. Look up the state at that call.
6. Let the user inspect the state. Ask if the result of the searched for draw call is already present.
8. a) If user says yes, set start to the current middle.
9. b) If user says no, set end to the current middle.
10. Go back to step 4.

**Comment by jrfonseca** [comment]
FYI, the per-draw call thumbnail code has been polished and merged into master, as of https://github.com/apitrace/apitrace/commit/d1d48f2c0e5a53988b10b1541f5fb37f084b76ca .

No ETA on pixel history though. But I added issue #317, to track it.

Given I have no plans of implementing bisection, I'm closing this one.
