### ISSUE TITLE
glVertexAttribPointer moved to draw calls without warning

### ISSUE THREAD

**Issue by JayFoxRox** [apitrace/apitrace#259]
As the issue title says, the vertex attribute bindings are moved to draw calls which is very confusing  when using debug groups. There should be a dummy entry (possibly without data) when the call is originally made, and a (possibly grayed out or apitrace marked) call to it with data before the draw call.

**Comment by jrfonseca** [comment]
I agree with your remark that at least apitrace should warn about this.  And I've updated the code to do so.

I don't plan to do anything more, so I'm closing this issue.

**Comment by lawlove** [comment]
(https://github.com/apitrace/apitrace/blob/master/BUGS.markdown#tracing
is missing the "docs" subdir; should be
https://github.com/apitrace/apitrace/blob/master/docs/BUGS.markdown#tracing)
