### ISSUE TITLE
qapitrace unstable in windows 7?

### ISSUE THREAD

**Issue by mattrmunson** [apitrace/apitrace#275]
The program seems to crash reliably in a number of cases
1) any time I try to edit call arguments
2) any time I run profile (it crashes part way through, at about the same spot). After I confirm to close qapitrace, glretrace keeps going and finishes.
3) if I open and then close frames one after another, the program crashes on the 15th - 30th frame or so.
 
I tried more than one build and got the same results.

**Comment by jrfonseca** [comment]
I think this was substantially improved with commit 446ca50d78d519230060d60c7179347ffb23de0c .  I can now do the operations mentioned in the first comment on Windows without running out of memory.
