### ISSUE TITLE
Tracing Half-Life 2 Ep1 on Mac OS X 10.9 limited to CGLFlushDrawable calls, black screen on replay

### ISSUE THREAD

**Issue by jmataraz** [apitrace/apitrace#278]
Built using latest source as of today. I tried using the apitrace executable and the DYLD_FRAMEWORK_PATH method.

The hl2.sh startup script puts the apitrace command at the front of the exec call via the GAME_DEBUGGER variable. It also sets its own DYLD_LIBRARY_PATH for the game's dynamic libs. Here's the terminal output as it starts:

```
/Volumes/Data/SteamLibrary/steamapps/common/Half-Life 2 (0) 716 > GAME_DEBUGGER="apitrace trace -v -o joe.trace" ./hl2.sh -game episodic -dev -fullscreen -console +playdemo flicker3.dem
info: did not find /usr/local/bin/wrappers/OpenGL.framework/OpenGL
info: found /usr/local/bin/../lib/wrappers/OpenGL.framework/OpenGL
DYLD_FRAMEWORK_PATH=/usr/local/bin/../lib/wrappers
"/Volumes/Data/SteamLibrary/steamapps/common/Half-Life 2/hl2_osx" -game episodic -dev -fullscreen -console +playdemo flicker3.dem
apitrace: loaded
SDL video target is 'cocoa'
SDL video target is 'cocoa'
apitrace: tracing to joe.trace
...
```

The trace contains some context startup boilerplate with calls to CGLDescribeRenderer mostly, and shortly launches into a stream of CGLFlushDrawable calls for the remaining frames. No other gl* calls are captured.

Here's the trace file from the above command:
https://drive.google.com/file/d/0B3bQ0JW_4stNbVRfWEZPRWJJUVE/edit?usp=sharing

I've been able to debug/trace this application using OpenGL Profiler, but I'd prefer to try out apitrace with it, for the trim capability.

I cloned the apitrace-tests repo and those all passed, as well.

**Comment by jrfonseca** [comment]
The `libGL.dylib` issue has been worked around, the `GL_APPLE_client_storage` issue is being tracked on issue #325, so I believe we can close this issue now.
