### ISSUE TITLE
trim breaks trace of BZFlag

### ISSUE THREAD

**Issue by g4jc** [apitrace/apitrace#280]
Game download: http://bzflag.org/downloads
Problem: When doing a trim to from a "BZFlag" video game trace it is not possible to trim it. Any attempt ends with a crash: "warning: no current context".

Broken Trimmed trace available for reference -
https://mega.co.nz/#!sAVnhbIa!3gxTG0Jiq1q3R_huSV_jvMAqSYtGSfnsaMgIPSvkeR8

**Comment by jrfonseca** [comment]
I'm afraid there are no plans to fix this -- https://lists.freedesktop.org/archives/apitrace/2017-April/001215.html
