### ISSUE TITLE
Crash using Bumblebee

### ISSUE THREAD

**Issue by ev1313** [apitrace/apitrace#306]
When tracing using my NVIDIA Optimus card with

>optirun apitrace trace ./program

It produces following output: https://db.tt/nMGeWqEm

Which let crash qapitrace instantly, when loading it.

When tracing with primusrun

>primusrun apitrace trace ./program

apitrace itself segfaults instantly.

I'm using Fedora 21 with the proprietary NVIDIA drivers and bumblebee.

**Comment by ev1313** [comment]
With the latest git version it crashes for me neither, but produces following output in the messages tab:

caught an unhandled exception
glretrace+0x247eec
/lib64/libpthread.so.0+0x100cf
/lib64/libc.so.6: gsignal+0x37
/lib64/libc.so.6: abort+0x169
/lib64/libc.so.6+0x2d46c
/lib64/libc.so.6: __assert_fail+0x41
/lib64/libX11.so.6+0x42ad8
/lib64/libX11.so.6+0x42b8a
/lib64/libX11.so.6: _XEventsQueued+0x5c
/lib64/libX11.so.6: _XGetRequest+0x64
/lib64/libX11.so.6+0x45d3e
/lib64/libX11.so.6: _XError+0x130
/lib64/libGL.so.1+0x1e8d1
/lib64/libGL.so.1+0x1abf9
glretrace+0x9d4a
glretrace+0x1073a
glretrace+0x1cac61
glretrace+0xe435
glretrace+0xa9e5
glretrace+0xb1c9
glretrace+0x6fc7
/lib64/libc.so.6: __libc_start_main+0xef
glretrace+0x8663
?
apitrace: info: taking default action for signal 6

**Comment by jrfonseca** [comment]
glretrace crashed.  (At least on debug builds) qapitrace will dump to stderr the glretrace command line.

Please paste that command line here, and try invoking glretrace directly inside gdb to produce a stack backtrace.

**Comment by jrfonseca** [comment]
So it seems the original GUI crash is fixed.

And without further info I can't do anything about the glretrace assertion failure.  If the glretrace issue persists and you're able to provide further info feel free to reopen or file a new issue.
