### ISSUE TITLE
link failed with arm64-v8a

### ISSUE THREAD

**Issue by hailinmath** [apitrace/apitrace#312]
hi 
  i build the solution for android version.( using ndk-10d)
but it failed with
 cmake -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/android.toolchain.cmake -DANDROID_API_LEVEL=9 -H. -Bbuild -DANDROID_ABI=arm64-v8a

but it works fine for armv7.

the following is the error message

/home/android64/android-ndk-r10d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9/../../../../aarch64-linux-android/bin/ld: CMakeFiles/egltrace.dir/gltrace_state.cpp.o: unrecognized relocation (0x20c) in section `.text._ZN7gltraceL6get_tsEv'
/home/android64/android-ndk-r10d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9/../../../../aarch64-linux-android/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../libs/arm64-v8a/egltrace.so] Error 1
make[1]: *** [wrappers/CMakeFiles/egltrace.dir/all] Error 2
make: *** [all] Error 2

hailinmath

**Comment by amonakov** [comment]
Looks like the gold linker is used, which didn't support that AArch64 relocation until this patch: https://sourceware.org/ml/binutils/2014-10/msg00192.html

If the android toolchain ships with the BFD linker and a recent enough gcc, a possible workaround is to add `-fuse-ld=bfd` to link flags.

**Comment by hailinmath** [comment]
hi amonakov:
   thanks for your quick reply.
   i try this option add
   set(CMAKE_SHARED_LINKER_FLAGS  "-fuse-ld=bfd")
   but this can not work. same error message.
this patch was add in oct, but ndk-10d was released at Dec, it may include this patch.
i also post a message to google ndk develop forum. but no one reply me.
https://groups.google.com/forum/#!topic/android-ndk/fBId6rSCV7E

thanks


hailinmath

**Comment by amonakov** [comment]
If the error message is literally the same, your change was not in effect; perhaps you didn't regenerate Makefiles?

**Comment by hailinmath** [comment]
/home/mtk30303/android64/android-ndk-r10d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9/../../../../aarch64-linux-android/bin/ld.bfd: CMakeFiles/libGLES_mtrace.dir/SnapContext.cpp.o: unrecognized relocation (0x20c) in section `.text._ZN4snapL6get_tsEv'
/home/mtk30303/android64/android-ndk-r10d/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9/../../../../aarch64-linux-android/bin/ld.bfd: final link failed: Bad value

a little difference ld.bfd , orignal one ld ,

hailinmath

**Comment by amonakov** [comment]
Hm, bfd linker seems to not support that relocation either, and I was probably wrong that gold linker was being used, my bad there.

What if you pass `-fuse-ld=gold`?

**Comment by hailinmath** [comment]
the error changes to 
/usr/bin/ld.gold: fatal error: /home/android64/android-ndk-r10d/platforms/android-21/arch-arm64/usr/lib/crtbegin_so.o: unsupported ELF machine number 183
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [android/libs/arm64-v8a/libGLES_mtrace.so] Error 1

**Comment by amonakov** [comment]
Heh, so ld.gold shipped with android ndk appears to not support aarch64 at all, and ld.bfd does not support relocation emitted by Clang. Is clang the default compiler for AArch64 Android? Have you tried using GCC rather than Clang?

**Comment by hailinmath** [comment]
yes, it works fine. 

thanks


cmake -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/android.toolchain.cmake -DANDROID_API_LEVEL=9 -H. -Bbuild/x64 -DANDROID_TOOLCHAIN_NAME=aarch64-linux-android-4.9 -DANDROID_ABI=arm64-v8a

hailinmath
