### ISSUE TITLE
Mantle support?

### ISSUE THREAD

**Issue by oscarbg** [apitrace/apitrace#315]
Hi,
I know Mantle SDK isn't public still but should be coming soon.. so only asking if once avaiable there is interest to support Mantle API..
I know that is ambitious plan but think apitrace should support all next gen APIs (of course I asume Dx12 and GLNext will be supported eventually being new iterations of currently supported APIS by apitrace).. But right now we only have Metal with Mantle should be coming soon..

**Comment by jrfonseca** [comment]
I won't refuse Mantle support if somebody is committed to implement and maintain it, but I confess that as long as Mantle is a single vendor API, I don't see much benefit.

AMD also provides similar graphics tools like GPU Perfstudio and CodeXL, and if somebody is developing a Mantle application they are already locked into AMD platform, so I can't imagine why they wouldn't want to use AMD tools.

Direct3D 12 and GL.Next would be a different story.

Therefore, unless you're ready to commit yourself to implement and maintain Mantle support I see no point in keeping this issue open.
