### ISSUE TITLE
glProgramBinary fails on NVIDIA if there is variation of GL_CONTEXT_FLAGS

### ISSUE THREAD

**Issue by computerquip** [apitrace/apitrace#316]
Natural Selection 2 uses glProgramBinary and does not explicitly call glLinkProgram. Despite the LINK_STATUS returning true and this seemingly working when running the game, apitrace does not seem to play with this well, and replaying displays a white screen of nothingness. If any feedback can be provided, I've provided the apitrace that fails from the public build of NS2 that does not work for me (which anyone can provide themselves). 

http://www.mediafire.com/download/i26f1403f6j0f2e/ns2_linux32.trace

**Comment by jrfonseca** [comment]
If you rebuild with commit 8f39c877ffa8fdb0c24f1e8f17adca830ad71a5c and replay, you might get more useful info (as glretrace warnings.)

I don't have the exact same NVIDIA driver version, so I can't actually replay your trace.  And there doesn't seem to be a demo of that game.

glProgramBinary replaces the need of calling glLinkProgram.  AFAICT it should just work.  The problem might not be program binary related.

If you apply the following patch and capture another trace, then it might be possible to trick NS2 to not use glProgramBinary, and prove whether the corruption you saw is or not related to it:

    diff --git a/wrappers/glcaps.cpp b/wrappers/glcaps.cpp
    index 2fc246c..078c7b9 100644
    --- a/wrappers/glcaps.cpp
    +++ b/wrappers/glcaps.cpp
    @@ -238,7 +238,12 @@ _glGetStringi_override(GLenum name, GLuint index)
             }
         }
     
    -    return _glGetStringi(name, index);
    +    const GLubyte *result;
    +    result = _glGetStringi(name, index);
    +    if (strcmp((const char *)result, "GL_ARB_get_program_binary") == 0) {
    +        result = (const GLubyte *)"GL_FOO_foo";
    +    }
    +    return result;
     }

**Comment by computerquip** [comment]
That patch appears to cause a segfault. Also, it won't apply to master out of the box...

**Comment by computerquip** [comment]
Taking the patch away, apitrace now tells me that the program binary is not compatible with my driver.... which doesn't make sense either as I only have one possible driver.

**Comment by jrfonseca** [comment]
> That patch appears to cause a segfault. Also, it won't apply to master out of the box...

This patch was taken from master. It applies fine here:

    $ git checkout master
    Already on 'master'
    $ git pull
    Current branch master is up to date.
    $ cat patch
    diff --git a/wrappers/glcaps.cpp b/wrappers/glcaps.cpp
    index 2fc246c..078c7b9 100644
    --- a/wrappers/glcaps.cpp
    +++ b/wrappers/glcaps.cpp
    @@ -238,7 +238,12 @@ _glGetStringi_override(GLenum name, GLuint index)
             }
         }
    
    -    return _glGetStringi(name, index);
    +    const GLubyte *result;
    +    result = _glGetStringi(name, index);
    +    if (strcmp((const char *)result, "GL_ARB_get_program_binary") == 0) {
    +        result = (const GLubyte *)"GL_FOO_foo";
    +    }
    +    return result;
     }
    $ patch -p1 -i patch
    patching file wrappers/glcaps.cpp

> apitrace now tells me that the program binary is not compatible with my driver.... which doesn't make sense either as I only have one possible driver.

I can think of a few explanations:
1) the program binary blob wasn't recorded properly somehow;
2) some other external factor (e.g., visual) changed, causing the binary blob to become useless.

**Comment by computerquip** [comment]
How would I fix 2 and how do I tell if 1 is happening?

**Comment by computerquip** [comment]
Also, how does this even work outside of apitrace if either is happening.

**Comment by jrfonseca** [comment]
I confess I'm not very sure on what's the best way to tackle this myself.

First, please confirm that when you run glxinfo, the reported "OpenGL version string" and "OpenGL shading language version string" strings match what's in the trace: 

    793 glGetString(name = GL_VENDOR) = "NVIDIA Corporation"
    794 glGetString(name = GL_VERSION) = "3.1.0 NVIDIA 346.35"
    795 glGetString(name = GL_RENDERER) = "GeForce GTX 770/PCIe/SSE2"
    796 glGetString(name = GL_SHADING_LANGUAGE_VERSION) = "1.40 NVIDIA via Cg compiler"

**Comment by jrfonseca** [comment]
I could reproduce the issue with https://github.com/g-truc/ogl-samples/blob/master/tests/gl-410-program-binary.cpp test/example.

In order to workaround https://github.com/g-truc/ogl-samples/issues/48 I had to do

    $ cd ogl-samples
    $ ln -s data/gl-410 gl-410

in the top directory.

    $ rm data/gl-410/binary.*.bin
    $ apitrace trace -o gl-410-program-binary.trace build/Debug/gl-410-program-binary 
    apitrace: loaded into /home/jfonseca/work/vmware/tests/ogl-samples/build/Debug/gl-410-program-binary
    apitrace: tracing to gl-410-program-binary.trace
    [...]
    $ glretrace gl-410-program-binary.trace
    8588 @0 glProgramBinary(program = 1, binaryFormat = 36385, binary = blob(7552), length = 7552)
    8588: warning: Program binary could not be loaded. Binary is not compatible with current driver/hardware combination.
    8590 @0 glProgramBinary(program = 2, binaryFormat = 36385, binary = blob(8215), length = 8215)
    8590: warning: Program binary could not be loaded. Binary is not compatible with current driver/hardware combination.
    8592 @0 glProgramBinary(program = 3, binaryFormat = 36385, binary = blob(7077), length = 7077)
    8592: warning: Program binary could not be loaded. Binary is not compatible with current driver/hardware combination.
    8594: message: major api error 1282: GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.
    8594 @0 glUseProgramStages(pipeline = 1, stages = GL_VERTEX_SHADER_BIT, program = 1)
    8594: warning: glGetError(glUseProgramStages) = GL_INVALID_OPERATION
    8595: message: major api error 1282: GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.
    8595 @0 glUseProgramStages(pipeline = 1, stages = GL_GEOMETRY_SHADER_BIT, program = 2)
    8595: warning: glGetError(glUseProgramStages) = GL_INVALID_OPERATION
    8596: message: major api error 1282: GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.
    8596 @0 glUseProgramStages(pipeline = 1, stages = GL_FRAGMENT_SHADER_BIT, program = 3)
    8596: warning: glGetError(glUseProgramStages) = GL_INVALID_OPERATION
    8601: message: major api error 1282: GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.
    8601 @0 glGetUniformLocation(program = 1, name = "MVP") = 0
    8601: warning: glGetError(glGetUniformLocation) = GL_INVALID_OPERATION
    8602: message: major api error 1282: GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.
    8602 @0 glGetUniformLocation(program = 3, name = "Diffuse") = 0
    8602: warning: glGetError(glGetUniformLocation) = GL_INVALID_OPERATION
    Rendered 4 frames in 0.152848 secs, average of 26.1699 fps

This narrows the problem.

Next thing to do is to verify or eliminate hypotheses 1) above, i.e, make sure that the blob that gets recorded on the trace and replaying, matches byte-per-byte to what's on the `data/gl-410/binary.*.bin` files.

If you could help with that I'd appreciate it.


Concerning hypothese 2), glretrace doesn't use _exactly_ the same visuals etc that were used in the application -- see https://github.com/apitrace/apitrace/blob/master/docs/BUGS.markdown#retracing for more details --.  These differences are small (e.g., alpha channel vs no alpha channels, etc.), but maybe they matter more to NVIDIA driver, and make the compilation useless.

To confirm or verify hypotheses 2) we'll need to compare what the app does, vs what glretrace does, and eliminate the differences one by one.

**Comment by jrfonseca** [comment]
I made a trace of `glretrace gl-410-program-binary.trace` and compared it with `gl-410-program-binary.trace` via `apitrace diff --tool=python`.

I've confirmed the blobs are the same, hence hypothese 1) is false.

And looking at the differences, I've figured out why `glretrace gl-410-program-binary.trace` was failing: the app uses `GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB` but glretrace was not. This hack fixes the problem for `glretrace gl-410-program-binary.trace`:

    diff --git a/retrace/glws_glx.cpp b/retrace/glws_glx.cpp
    index c3250ab..873a345 100644
    --- a/retrace/glws_glx.cpp
    +++ b/retrace/glws_glx.cpp
    @@ -314,9 +314,12 @@ createContext(const Visual *_visual, Context *shareContext, bool debug)
             } else {
                 assert(0);
             }
    +        int contextFlags = 0;
    +        contextFlags |= GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB;
             if (debug) {
    -            attribs.add(GLX_CONTEXT_FLAGS_ARB, GLX_CONTEXT_DEBUG_BIT_ARB);
    +            contextFlags |= GLX_CONTEXT_DEBUG_BIT_ARB;
             }
    +        attribs.add(GLX_CONTEXT_FLAGS_ARB, contextFlags);
             attribs.end();
     
             context = glXCreateContextAttribsARB(display, visual->fbconfig, share_context, True, attribs);

For NS2 the problem is opposite different, the app doesn't set any GLX_CONTEXT_FLAGS_ARB at all, so this hack is required:

    diff --git a/retrace/glws_glx.cpp b/retrace/glws_glx.cpp
    index c3250ab..b057a7c 100644
    --- a/retrace/glws_glx.cpp
    +++ b/retrace/glws_glx.cpp
    @@ -315,7 +315,7 @@ createContext(const Visual *_visual, Context *shareContext, bool debug)
                 assert(0);
             }
             if (debug) {
    -            attribs.add(GLX_CONTEXT_FLAGS_ARB, GLX_CONTEXT_DEBUG_BIT_ARB);
    +            //attribs.add(GLX_CONTEXT_FLAGS_ARB, GLX_CONTEXT_DEBUG_BIT_ARB);
             }
             attribs.end();
     
However, this means that NVIDIA will not provide any debug info whatsoever...

**Comment by jrfonseca** [comment]
I believe the only sane way of dealing with this, is to have apitrace to disable this extension.

@computerquip, could you please try tracing and replaying with https://github.com/apitrace/apitrace/tree/disable-program-binary branch, and see if the changes there are effective to prevent NS2 from using program binaries?

If it doesn't work, try wipe out existing program binaries per http://forums.unknownworlds.com/discussion/132655/linux-nvidia-beta-driver-331-13 , to see if it helps.

**Comment by computerquip** [comment]
Just tested the game with the tree, it works great. Good job!

**Comment by computerquip** [comment]
This issue has come back it seems. Tried with trunk with the exact same symptoms as the beginning. The original trace is old but should still reproduce the issue.

**Comment by jrfonseca** [comment]
> This issue has come back it seems. Tried with trunk with the exact same symptoms as the beginning. 

Weird, as far as I can see, the fix is still there.

> The original trace is old but should still reproduce the issue.

The fix is triggered while tracing, so it would  actually be useful that you captured another trace, so I can see exactly how the application is bypassing the fix.

**Comment by computerquip** [comment]
Okay, this was probably my fault. I used what version was in current Arch Linux repositories and it appears that wasn't new enough. I then installed from trunk and everything works fine. Apologies!
