### ISSUE TITLE
trace and replay on embedded Linux without wayland or X

### ISSUE THREAD

**Issue by Jong7707** [apitrace/apitrace#318]
Hello,

I tried to trace/replay on my armv7 board(OpenGL ES2).
It doesn't have a window system such as wayland or X11(there is only fbdev)
I modified Cmake file and succeed to get egltrace.so and look like it work.

However, I don't know how to build Waffle in my situation.(For getting, eglretrace)
Should I build wayland weston?

Regards,
Jongsung

**Comment by jrfonseca** [comment]
I really can't say.  I don't use apitrace on embedded systems myself.

I think you might get more luck using the [mailing list](http://lists.freedesktop.org/mailman/listinfo/apitrace) for this sort of questions.

**Comment by Jong7707** [comment]
Thanks for your reply. Yes, you're right. I should have use mailing list.
