### ISSUE TITLE
qapitrace not accurate when profiling

### ISSUE THREAD

**Issue by Emanem** [apitrace/apitrace#319]
I've recently trace games such as HoN (Heroes of Newerth) and apparently profiling reports some huge timings for simple calls (drawing ~180 tri), which is not reflected when playing the game (60 FPS rock solid).
Any idea why that could be?

Ps. I'm using default APITrace version from Ubuntu 14.04

**Comment by jrfonseca** [comment]
Are these timings consistent or random?

In order to obtain these timings aptirace needs to create thousands of queries.  These can have some overheads or hit some hardware limits, yielding wrong results.

There are also overheads in reading traces from disk.  Particularly if the application uses vertex arrays in user memory (as opposed to VBOs).

**Comment by jrfonseca** [comment]
BTW, you can easily dump the profile output to a plain text file if you follow the instructions in https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown#profiling-a-trace

**Comment by Emanem** [comment]
@jrfonseca these are more random timings; the game runs at 60+ FPS. What advantage should I get by dumping the profile output to a text file compared to UI?

**Comment by jrfonseca** [comment]
> What advantage should I get by dumping the profile output to a text file compared to UI?

Just to help diagnose these issue. I'd like to see if, when you dump the profile output multiple times, the spikes in the times are consistent, or move around (every time different results.)

If you can see that with the UI that's fine too.  I just imagined with a plantext file it's easier to see multiple results side-by-side with visual diff sort of too.

**Comment by jrfonseca** [comment]
I'm afraid there's not enough info here fore me to be able to diagnose the issue or take any concrete action.
