### ISSUE TITLE
qapitrace: Do not enforce Qt graphics system unless it’s necessary

### ISSUE THREAD

**Issue by lachs0r** [apitrace/apitrace#327]
Commit 023a4f8 enforces the graphics system used by Qt to the generally faster raster backend. However, the raster backend is also known to be broken with 30 bpp display modes (which can be used on at least X11), rendering the UI unusable (Qt 5.4 addresses this issue).

Assuming the performance problem is still present in recent Qt versions, please make sure qapitrace respects the usual ways to override the graphics system (`-graphicssystem` switch, `QT_GRAPHICSSYSTEM` environment variable), and only override the default in environments where it really matters.

**Comment by haasn** [comment]
I have the same issue. This is what it looks like on my end:
![](http://0x0.st/zv.png)

**Comment by jrfonseca** [comment]
That line of code was removed in master, when the GUI was ported to Qt5.  So I presume the issue is now gone.
