### ISSUE TITLE
use of std::isnan broke B2G-emulator build

### ISSUE THREAD

**Issue by staktrace** [apitrace/apitrace#328]
Hi,
The apitrace project is one of the projects that gets built as part of the B2G (github.com/mozilla-b2g/B2G.git) project. The commit fc740d702d3a1369603d08444ec8809d1a109160 appears to have introduced a compiler error for me when I build the "emulator" configuration of the B2G project. The error message goes away if I remove the std:: namespace prefix on the isnan and isinf call sites (with no other changes). It might just be that I just need to compile with a different compiler - can you let me know what the supported compiler versions are for this project? I'm currently building with gcc-4.8 on Ubuntu.

**Comment by jrfonseca** [comment]
That's odd. I've succesffuly built it on:
* gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3 https://travis-ci.org/apitrace/apitrace/
* gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
* gcc version 4.9.1 (Ubuntu 4.9.1-16ubuntu6)

Maybe it's not just the gcc version, but some other factor.

Maybe something (some system header) is include "math.h" (instead of cmath) somewhere, causing problems.

This C99 isinf macro vs C++11 std::isinf is quite a nightmare to deal with....

**Comment by jrfonseca** [comment]
Sorry I mean isnan, not isinf

**Comment by jrfonseca** [comment]
If you apply this patch locally the error message should pop up.

    diff --git a/retrace/json.hpp b/retrace/json.hpp
    index 75b6f5d..1d83171 100644
    --- a/retrace/json.hpp
    +++ b/retrace/json.hpp
    @@ -33,6 +33,10 @@
     #include <stddef.h>
     #include <wchar.h>
     
    +#ifdef isnan
    +#error "math.h was included before"
    +#endif
    +
     #include <cmath> // for std::isinf, std::isnan; as C99 macros are unavailable in C++11
     
     #include <iomanip>

**Comment by staktrace** [comment]
Ah, sorry! I screwed up - it's actually the "target" build rather than the "host" build that's failing. The "target" build is using gcc-4.4.3 with an arm target, which is probably too old to build this happily. I did apply the patch you posted and math.h doesn't seem to be included in either host or target builds. I'll probably just work around it locally, and try to get the B2G build system to upgrade the ARM compiler being used. Thanks!

**Comment by jrfonseca** [comment]
Yeah, you probably need gcc-4.6 or clang-3.4 for reasonable C++11 support

**Comment by staktrace** [comment]
FYI I found a bug filed a few days ago on this topic: https://bugzilla.mozilla.org/show_bug.cgi?id=1140963

**Comment by jrfonseca** [comment]
I took a look at that bug report.

We'll probably use more and more C++11 from now on.  So even if this particular change can be easily worked around it's just a matter of time until new breakages ensues.

So using the tag for the last release seems a good idea for these old gcc platforms.

apitrace CMakelist.txt actually tries to check whether gcc supports C++11 or not, but it looks like per https://gcc.gnu.org/projects/cxx0x.html that gcc-4.4 has some C++11 support.

I'll probably need to make CMakeLists.txt a little meaner and require gcc-4.6, which is the lowest version I try to compile with.

**Comment by staktrace** [comment]
Sounds good, thanks!
