### ISSUE TITLE
Crash when tracing C++ applications

### ISSUE THREAD

**Issue by turol** [apitrace/apitrace#330]
Apitrace crashes when tracing C++ applications. Platform is Debian testing x86_64.

Bisected to 21e685f12ef9a9d2ef0c31bb538c6171ebf72d2a "cmake: Statically link wrappers against libgcc and libstdc++ on Linux."

Compiling apitrace with ENABLE_STATIC_LIBSTDCXX=OFF avoids the issue but it would be nice to not crash by default.

Error message is like "free(): invalid pointer: 0x00000000041af300". Examining with gdb it appears that my code calls std::stringstream operator << which goes to glxtrace.so, from there to libstdc++.so.6  and back to glxtrace.so std::string::reserve where it crashes.

`#1  0x00007f443d1c94e8 in __GI_abort () at abort.c:89
`#2  0x00007f443d206204 in __libc_message (do_abort=do_abort@entry=1, 
`    fmt=fmt@entry=0x7f443d2f8fe0 "*** Error in `%s': %s: 0x%s ***\n")
`    at ../sysdeps/posix/libc_fatal.c:175
`#3  0x00007f443d20b9de in malloc_printerr (action=1, 
`    str=0x7f443d2f509e "free(): invalid pointer", ptr=<optimized out>)
`    at malloc.c:4996
`#4  0x00007f443d20c6e6 in _int_free (av=<optimized out>, p=<optimized out>, 
`    have_lock=0) at malloc.c:3840
`#5  0x00007f443ff6d394 in std::string::reserve(unsigned long) ()
`   from apitrace/wrappers/glxtrace.so
`#6  0x00007f443daeefb4 in std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> `>::overflow(int) ()
`   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
`#7  0x00007f443ff44bf5 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, `long) ()
`   from apitrace/wrappers/glxtrace.so
`#8  0x00007f443ff4f706 in std::basic_ostream<char, std::char_traits<char> >& `std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> `>&, char const*, long) ()
`   from apitrace/wrappers/glxtrace.so
`#9  0x00007f443ff4fad7 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< `<std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*) () from `apitrace/wrappers/glxtrace.so
`#10 0x00007f443f88c507 in user code

Tested with two different C++ programs. Both were compiled in C++11 mode. Non-C++11 C++ programs were not tested. A plain C program doesn't crash. All programs and apitrace were compiled with GCC 4.9.2.

**Comment by jrfonseca** [comment]
Indeed doing

    nm dynamic --defined-only wrappers/glxtrace.so | sed -n 's/^[0-9a-fA-F]\+ T //p'

shows libstdc++ symbols.  It looks like the -static-libstdc++ symbols have public visibility.

Not sure what to do here: some LD script, or something else.

**Comment by jrfonseca** [comment]
The trick from http://lists.freedesktop.org/archives/mesa-dev/2015-March/079121.html seems to work:

    diff --git a/wrappers/CMakeLists.txt b/wrappers/CMakeLists.txt
    index 38d5fae..ac624b5 100644
    --- a/wrappers/CMakeLists.txt
    +++ b/wrappers/CMakeLists.txt
    @@ -21,7 +21,7 @@ if (ENABLE_STATIC_LIBSTDCXX)
         unset (CMAKE_REQUIRED_LIBRARIES)
         unset (CMAKE_REQUIRED_FLAGS)
         if (STATIC_LIBSTDCXX_PIC)
    -        add_linker_flags ("-static-libstdc++")
    +        add_linker_flags ("-static-libstdc++ -l:libgcc.a -l:libstdc++.a -Wl,--exclude-libs,libgcc.a:libstdc++.a")
         endif ()
     endif ()
