### ISSUE TITLE
Trimming breaks Civilization: Beyond Earth trace

### ISSUE THREAD

**Issue by sliedes** [apitrace/apitrace#335]
On apitrace HEAD (8a1ba735):
1. Download CivBE.trace.lz from https://drive.google.com/file/d/0BwgPzH1WFyIuUEVLQ0NtVGlOSVU/view?usp=sharing (sorry, 233 MiB compressed)
2. lzip -d CivBE.trace.lz
3. apitrace trim --frames=500 -o trim.trace CivBE.trace

Now, we can make a few observations on the result, and I think at least the first one is a bug (of the other ones I'm not sure, so not filing separately):
1. The trimmed file renders (more) incorrectly compared to the original. Specifically, the city buildings and other constructions (slightly below the CENTRAL text) now are all black.
2. The trimming does not seem to be very effective (though I don't know if it could be). The trace is trimmed from 711 MiB to 533 MiB, with a really huge frame.
3. Running qapitrace on the resulting trace and Showing Thumbnails for the single frame allocates 5.3 GiB of memory, while running Show Thumbnails for all frames of the original trace requires minimal memory.

**Comment by jrfonseca** [comment]
I'm afraid there are no plans to fix this -- https://lists.freedesktop.org/archives/apitrace/2017-April/001215.html
