### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by x414e54** [apitrace/apitrace#336]
I am trying to get api-trace working on Wayland. 

So far is is successfully collecting the EGL and gl calls into a trace but when trying to play back the eglretrace process exits with unable to create opengl visual.

I have looked through and retrace supports waffle so it would be simply a case of adding in WAFFLE_PLATFORM_WAYLAND into waffle and making sure USE_WAFFLE is ON. 

After enabling this and recompiling apitrace and (recompiling waffle to make sure there is wayland support) it errors at eglGetProcAddress. To fix this I just switched to using the android method of dlopen on libGL.so directly.

**Comment by x414e54** [comment]
It also looks like if an application calls:

eglChooseConfig
eglCreateWindowSurface
eglCreateContext

It is not correctly picking the correctly EGL API and defaulting to creating a GLES window/context.

The issue related to this is https://github.com/apitrace/apitrace/issues/197

**Comment by jrfonseca** [comment]
@x414e54 please provide a sample trace for the config issue,

**Comment by x414e54** [comment]
https://www.dropbox.com/s/86w50jxski9wv4n/UE4Editor.1.trace.tar.bz2?dl=0

**Comment by art-gs** [comment]
Trying to compile apitrace with Wayland support, but it fails with an error about missing X11/Xlib.h header which is obviously absent on my system.
The question is for topic starter: have you modified sources in order to compile and run apitrace on Wayland?
