### ISSUE TITLE
Can't run apitrace from /usr/local/bin on Mac OSX 10.10.3

### ISSUE THREAD

**Issue by TheAbhiKumar** [apitrace/apitrace#337]
I moved the apitrace executable to /usr/local/bin and tried to run it, but it doesn't seem to detect the OpenGL.framework.

```
apitrace trace -a gl -v ./main
info: did not find /usr/bin/wrappers/OpenGL.framework/OpenGL
info: did not find /usr/bin/../lib/wrappers/OpenGL.framework/OpenGL
info: did not find /usr/local/lib/wrappers/OpenGL.framework/OpenGL
error: failed to find OpenGL.framework/OpenGL wrapper (rerun with -v option for more details)
```

How do I make apitrace recognize the location of OpenGL.framework?

**Comment by jrfonseca** [comment]
You can't just move the apitrace executable. There are many other files that would need to go too, like the `wrappers/OpenGL.framework/*`

You can try doing `make install`, but by far the simplest way is to just run where you built it.
