### ISSUE TITLE
Tracing on android segfaults with assertion failure

### ISSUE THREAD

**Issue by divkis01** [apitrace/apitrace#341]
I am using [AndyOs](http://www.andyroid.net/) on windows for tracing on android. The version of Android on AndyOs is 4.2.2. Having built the libraries for android egltrace.so and libgnustl_shared.so, and running a java application using **am** with LD_PRELOAD, I get the assertion failure as soon as the application is started on the following line:

`assert(tr->profile.api == glprofile::API_GLES);`

The relevant code in egltrace.cpp:15862 is:

``` 
           if (api == EGL_OPENGL_ES_API) {
                assert(tr->profile.api == glprofile::API_GLES);
                EGLint version = 1;
                _eglQueryContext(dpy, ctx, EGL_CONTEXT_CLIENT_VERSION, &version);
                assert(tr->profile.major >= version);
            }
```
It is sort of expected since  API_GLES is defined as value 1 in glprofile.hpp. Tracing on android the context type is API_GLES and the default value of Context->profile.api is set to API_GL in the constructor initializer for Context:

In wrappers/gltrace.hpp:

```
Context(void) :
        profile(glprofile::API_GL, 1, 0),
        user_arrays(false),
        user_arrays_nv(false),
        userArraysOnBegin(false),
        retain_count(0),
        bound(false)
    { }
```
Nowhere do I see profile type being changed after it has been initialized once in Context constructor above.

**Comment by jrfonseca** [comment]
> Nowhere do I see profile type being changed after it has been initialized once in Context constructor above.

When `eglMakeCurrent` is called, it will invoke `gltrace::setContext` (just a few lines above the code you pasted), which will do

     ctx->profile = glprofile::getCurrentContextProfile();

which in turn will detect the profile based on the `glGetString(GL_VERSION)`.

Maybe AndyOS EGL/GLES implementation is returning a non-standard `GL_VERSION` string?

**Comment by divkis01** [comment]
I see that the GL_VERSION returned is "4.2.0 - Build 10.18.10.3345" This is because the glGetString is called for the host gpu which has exactly the same version (found using glExtensionViewer on windows). Since calling glGetString(GL_VERSION)  could return the value for client or server, the glGetString should return a compatible version. In case of extensions only the common extensions could be returned but the specs are not clear what does compatible mean in case of GL_VERSION. My guess is since the application should return the version against which the library has been linked which in this case is GLES and not GL.

[[https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetString.xml]] -- In the **Notes** section there is a mention of the compatibility.

I guess then it is not really a bug in apitrace but an issue with the way emulators like andyos work (by utilizing the host GPU). For now building with Release version should fix the issue.

**Comment by jrfonseca** [comment]
Yep, this is not a bug in apitrace.  The application requested GLES implementation, yet it's receiving a full desktop GL.

But probably AndyOS is not the only GLES implementation on top of desktop GL that takes this sort of liberties.

And as you said, everything should work fine -- this was mostly for debugging Apitrace itself.  So I'll change the assertion to a mere warning.
