### ISSUE TITLE
Qapitrace leaks when saving traces

### ISSUE THREAD

**Issue by jlegg0** [apitrace/apitrace#345]
When editing a trace in qapitrace, the modified trace is saved to a file. This leaks memory. On very large traces, this tends to be enough cause the kernel out of memory killer to kill qapitrace before it completes. 

The following patch fixes the problem (I haven't checked if no memory is leaked after applying it, but editing large traces no longer causes an obvious permanent increase).
```patch
diff --git a/gui/saverthread.cpp b/gui/saverthread.cpp
index 990aeee..e9e5a3f 100644
--- a/gui/saverthread.cpp
+++ b/gui/saverthread.cpp
@@ -374,6 +374,7 @@ void SaverThread::run()
         } else {
             writer.writeCall(call);
         }
+        delete call;
     }
 
     writer.close();
```

**Comment by jrfonseca** [comment]
Good catch. Thanks.

One day I should invest in automated testing of the GUI so we can catch this sort of things.
