### ISSUE TITLE
Building on Mac OS X / clang can take up to 45 mins

### ISSUE THREAD

**Issue by racarate** [apitrace/apitrace#346]
osx 10.9.4
cmake 3.3.0
apple LLVM 6.0
make 3.81
python 2.75

"make -C build" hangs at this line:

[ 32%] Building CXX object wrappers/CMakeFiles/cgltrace.dir/cgltrace.cpp.o

**Comment by jrfonseca** [comment]
Could you confirm the clang version (`clang --version`) and the build type you used.

Probably the same as issue #333. 

In short, some clang versions are incredibly slow to compile apitrace with optimizations on. That's really a bug in clang/llvm, and nothing I can do about.

There was even a report bug in llvm -- http://llvm.org/PR9499 . But I'm not sure if it's the same issue or a new one.

But I think I'll have to add a warning to apitrace build so people are aware of this problem.

**Comment by jrfonseca** [comment]
I just tried a release build on

    $ clang --version
    Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)

and it only took 5min.  So maybe you just need to upgrade Xcode.

Either way I added a warning about this on d172b02d2d43774b934a866912b9a170c7f495df.  There's nothing more I can do.

**Comment by z3t0** [comment]
Just noticed the warning and this does not seem to be an issue for me either
