### ISSUE TITLE
GLX Pbuffer with size (0, 0) are valid but cause a BadValue

### ISSUE THREAD

**Issue by Kangz** [apitrace/apitrace#347]
In ANGLE we use a (0, 0) Pbuffer to query some GL limits. When replaying a trace this will cause glws::createWindow to try to create an empty window, which results in a BadValue error.

I fixed this locally by adding the following on top of createWindow but it is probably too hacky:
```cpp
if (width == 0) width = 1;
if (height == 0) height = 1;
```

**Comment by jrfonseca** [comment]
Could you provide a small trace?

**Comment by Kangz** [comment]
[Here it is](http://inf553.kangz.net/empty_pbuffer_trace), it is 120k and about 4k calls, though the problem is early in frame 1.

**Comment by Kangz** [comment]
Thanks a lot!
