### ISSUE TITLE
Retracing calls to IDXGISwapChain1::Present1 crashes

### ISSUE THREAD

**Issue by jrmuizel** [apitrace/apitrace#348]
Present1 takes a pointer to a DXGI_PRESENT_PARAMETERS which contains a pointer to an array of pDirtyRects. It looks like the retrace code doesn't properly allocate the pDirtyRects array.

**Comment by jrfonseca** [comment]
Could you provide me a sample trace?

**Comment by jrmuizel** [comment]
http://people.mozilla.org/~jmuizelaar/tmp/firefox.1.trace

**Comment by jrfonseca** [comment]
Thanks. I actually don't have a system capable of replaying this handy, but I believe this should be fixed  by 41efd945c841175f733ef764fe5f6a85c592970b .
