### ISSUE TITLE
CMake configure fails on Windows with relative build path

### ISSUE THREAD

**Issue by mtschoen** [apitrace/apitrace#352]
For some reason, on my system, I had to specify an absolute path for the build directory, otherwise Configure would fail with the following output:

The C compiler identification is unknown

Should update INSTALL.markdown with a note on this.

**Comment by mtschoen** [comment]
Also, I end up having to set my Qt paths manually anyway. It might be time to generally test/update the Windows install instructions.

**Comment by jrfonseca** [comment]
Take a look at the build logs of https://ci.appveyor.com/project/jrfonseca/apitrace -- everything you're complaining about "just works" there.  I also build on many other Windows systems and never had troubles.

It must be something specific to your system. 

Were you using MSVC or something else?

> It might be time to generally test/update the Windows install instructions.

Maybe it's time for to re-install Windows.

**Comment by mtschoen** [comment]
Haha, yeah I'll admit my configuration is... "exotic."  And yes, I'm using MSVC 12/2013

My guess is that the main issue is that I have everything set up on D:\ since I use an SSD and shift my docs/etc. to another physical drive. Even still, it would be nice to add some help for noobs like me when it doesn't "just work"

I was able to get everything working by just launching cmake on its own, setting absolute paths, choosing VS 2013 Win64, setting the Qt_WebKitWidgets, and Widgets paths manually, and then building out of Visual Studio.  Neigther build command in the doc worked for me, presumably because of my D:\ paths.  I suspect this issue because it's come up in some other odd scenarios regarding dependency tracking.

**Comment by jrfonseca** [comment]
> My guess is that the main issue is that I have everything set up on D:\ since I use an SSD and shift my docs/etc. to another physical drive. 

Weird. On one system I always build my source from a network drive, and never run against this issue.
On another is the opposite: Qt is on a network path, and it builds fine...

> Even still, it would be nice to add some help for noobs like me when it doesn't "just work"

I wonder if there's anybody else in the world that would hit this issue, but I suppose a note in the docs wouldn't hurt, just in case.  So it was done in 8c42541489a8f493e17f7110bdbe10c11c983079.

**Comment by mtschoen** [comment]
Yeah, I'm not sure what the issue is, but thankfully absolute paths fix it just fine. Thanks for making the note!
