### ISSUE TITLE
Scrolling with a touchpad gesture in qapitrace causes a segfault

### ISSUE THREAD

**Issue by sstewartgallus** [apitrace/apitrace#354]
Scrolling up, down, left, right causes a crash. Scrolling using the mouse bar and the arrow keys does not.

**Comment by jrfonseca** [comment]
I can't reproduce this: I have a laptop with touch-screen, but multi-touch doesn't work out of the box, so I suspect I can't make the scroll touch gesture.

@sstewartgallus Is it possible to provide a stack back trace (by running qapitrace inside gdb)? The problem might obvious enough to fix without actually reproducing myself.

**Comment by jrfonseca** [comment]
I just noticed this was with touch-pad, not touch-screen.

Nevertheless I still can't repro this.  Scrolling with my touch-pad works fine.

I'm afraid there's nothing further I can do.  If the issue persists and you're able to provide more information then feel free to reopen this issue.

**Comment by sstewartgallus** [comment]
I rebuilt with the latest sources and now the issue has seem to have gone away.

**Comment by jrfonseca** [comment]
Thanks for confirming.
