### ISSUE TITLE
Segmentation fault in qapitrace

### ISSUE THREAD

**Issue by exbluesbreaker** [apitrace/apitrace#357]
I've got SEGFAULT during replaying traces in qapitrace (gui/apitrace.cpp:285). 
GDB output:

`Program received signal SIGSEGV, Segmentation fault.
0x0000000000456d6f in ApiTrace::loaderFrameLoaded (this=0xb90b30, frame=0x7fff681b32b0, topLevelItems=..., calls=..., binaryDataSize=129452) at <...>/apitrace-master/gui/apitrace.cpp:285
285	            if ((*itr).first == frame) {`

I think, this is because of incorrect erasing elements from list during iteration. I guess this must be done, something like this (i change for loop to while loop):

    ...
    itr = m_queuedErrors.begin();
    while (itr != m_queuedErrors.end()) {
    const ApiTraceError &error = (*itr).second;
    if ((*itr).first == frame) {
                ApiTraceCall *call = frame->callWithIndex(error.callIndex);

                if (!call) {
                        itr++;
                    continue;
                }

                call->setError(error.message);
                itr = m_queuedErrors.erase(itr);

                if (call->hasError()) {
                    m_errors.insert(call);
                } else {
                    m_errors.remove(call);
                }
                emit changed(call);
            }
        }
     ...

**Comment by exbluesbreaker** [comment]
Sorry, i missed if statement inside loop. "else" branch is needed, of course.

        QList< QPair<ApiTraceFrame*, ApiTraceError> >::iterator itr;
        itr = m_queuedErrors.begin();
        while (itr != m_queuedErrors.end()) {
            const ApiTraceError &error = (*itr).second;
            if ((*itr).first == frame) {
                ApiTraceCall *call = frame->callWithIndex(error.callIndex);

                if (!call) {
                        itr++;
                    continue;
                }

                call->setError(error.message);
                itr = m_queuedErrors.erase(itr);

                if (call->hasError()) {
                    m_errors.insert(call);
                } else {
                    m_errors.remove(call);
                }
                emit changed(call);
            }
            else
                   itr++;
            }

**Comment by jrfonseca** [comment]
Good catch. Sorry it took this time to push your fix. Thanks.
