### ISSUE TITLE
glGetIntegerv(GL_CURRENT_PROGRAM, ...) on gles 1.1 context

### ISSUE THREAD

**Issue by krnlyng** [apitrace/apitrace#360]
Hi,
I am trying to debug the android renderer from the android emulator target (reason: i want to use it as some sort of android compatibility layer for android apps on non-android phones - as explained here: http://talk.maemo.org/showthread.php?t=95631). Now i want to debug it, because of course it doesn't work ootb on mobile devices.
I have created this trace: http://www.mediafire.com/download/ob7sbvgbm2obbvl/emulator_test_renderer.trace with "ANDROID_WINDOW_SIZE=540x960 ANDROID_EGL_LIB=libEGL.so ANDROID_GLESv1_LIB=libGLESv1_CM.so ANDROID_GLESv2_LIB=libGLESv2.so LD_LIBRARY_PATH=. apitrace trace --api=egl ./emulator_test_renderer" where emulator_test_renderer is this program: https://github.com/krnlyng/android_renderer (for rendering stuff emulator_test_renderer requires an android chroot which sends egl/gl commands over tcp) and when i replay the trace on my desktop it gives me: https://bpaste.net/show/75bb41e27bd6 (with MESA_DEBUG=1). All the contexts which have been created in the trace file where gles 1.1 contexts and not gles 2.0 contexts, but why does apitrace call glGetIntegerv with GL_CURRENT_PROGRAM? and does that mean it created a gles 2.0 context? and is this the reason why i get a black screen on desktop? (on the device i get at least garbage) Also note that, i have tried to replay the trace on a different machine and i get the same results.

thanks in advance and best regards,
krnlyng

**Comment by jrfonseca** [comment]
Mesa: User error: GL_INVALID_ENUM in glGetIntegerv(pname=GL_CURRENT_PROGRAM)

This is a bug in egl/glretrace. I'll fix it shortly.

Not sure why the black screens.  Was it also black when recording?

**Comment by jrfonseca** [comment]
I noticed your trace uses `glEGLImageTargetTexture2DOES`. Note that apitrace can't trace across processes, so it emits fake `glTexImage2D` with the calls with the pixels instead.
