### ISSUE TITLE
Cooperation with gdb

### ISSUE THREAD

**Issue by mkollaro** [apitrace/apitrace#362]
I'm not sure whether the apitrace architecture allows it, but I'd be very happy if I could somehow run the tracer while stepping in gdb (and visualize the trace in qapitrace at the same time). [Valgrind supports cooperation with gdb](http://billiob.net/blog/20140330_vgdb.html), so I hope it should be at least theoretically possible to do this. My main problem is that GL calls are abstracted behind a lot of layers in the program I'm debugging and I often find it difficult to figure out where exactly did a call originate from, given the trace. This could perhaps also be solved by saving the stack trace in the apitrace log for each GL command (which would also be nice, but gdb support would be awesome).

**Comment by jrfonseca** [comment]
> This could perhaps also be solved by saving the stack trace in the apitrace log for each GL command

There's no integration with gdb, but this actually is already supported -- https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown#backtrace-capturing .  It causes a hit on performance which is why it's not enable by default.

It would also be nice to have a command line option for `apitrace trace` to do this automatically (a patch would be welcome)

**Comment by jrfonseca** [comment]
>  Valgrind supports cooperation with gdb, so I hope it should be at least theoretically possible to do this. 

I read the link  you provided, but I'm afraid it doesn't apply.  Apitrace works by recording all GL calls into a file, but when inspecting the state (via glretrace) the original process is long gone.

What you ask, is basically a live OpenGL debugger (ie, one that attaches to running application, and inspected the state inside the application.) There is merit in that approach, and such tools exist (e.g., [bugle](https://www.opengl.org/sdk/tools/BuGLe/) and [gl intercept](https://github.com/dtrebilco/glintercept), but that's not apitrace architecture, which revolves about offline traces.

Offlines traces might have some inconveniences vs live inspectors for app developers, but it is quite useful for OpenGL implementors (like for reproducing bugs and regression testing), and is a all-round nice concept.

If you want better context when debugging with qaptitrace, you can ask to use the stack back traces as suggested above, or annotate the trace as explained in https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown#emitting-annotations-to-the-trace.

As I said above, the ability to include call stacks could be made more user friendly.  And I'm happy to take further action, you have concrete suggestions or patches around it.

But I'm afraid that gdb integration itself just doesn't quite apply to Apitrace.
