### ISSUE TITLE
JSON output from glretrace isn’t valid JSON

### ISSUE THREAD

**Issue by linkmauve** [apitrace/apitrace#366]
In JSON, a string can’t contain a line return, and glretrace doesn’t convert them into \n in the GLSL strings and in the base64 attachments.

**Comment by jrfonseca** [comment]
Yes, glretrace's output is not strictly JSON:
* strings can have new lines
* floats can be Inf/NaN

This was not by mistake, but by design, as this is widely accepted superset of JSON (e.g., Python, Qt parsers all support it. Probably many others do too.)

Why do you need strict JSON?

**Comment by linkmauve** [comment]
Both Python’s (3.4) and node’s (0.12) chocked on the new lines in the strings, so I had to filter the input before giving it to them.  I didn’t encounter the float difference, but node doesn’t accept either Inf or NaN, while Python only accepts NaN. I didn’t try any other parser though.

Python says “ValueError: Invalid control character” for a newline, and node “SyntaxError: Unexpected token”.

**Comment by jrfonseca** [comment]
For Python you need to pass `strict=False` option.  See https://github.com/apitrace/apitrace/blob/master/scripts/jsondiff.py#L322-L332 

For Node I don't know.

If you're writing new tools to read glretrace/eglretrace output I strongly recommend you use the UBJSON format (`--dump-format=ubjson`), which is now the one currently used for Qt qapitrace gui.  JSON and base64 encoding ends up wasting too much space, specially for large textures where even the raw image can be several GBs.

If you want to provide a patch to produce strict JSON (ie., `--dump-format=strict-json`), I wouldn't refuse. It's probably an easy to do (by making a specialization of `retrace/json.cpp`).  I don't however have the time/interest to pursue it myself.
