### ISSUE TITLE
Implement glretrace --headless using a render node on Linux

### ISSUE THREAD

**Issue by linkmauve** [apitrace/apitrace#368]
This would allow retracing without a X11 server, for example on Wayland or on a headless server.

**Comment by jrfonseca** [comment]
`glretrace --headless` means no X window, but not necessarily without  X.

`eglretrace` could (and in same cases can) be made to work without X though.

**Comment by linkmauve** [comment]
Indeed, I was thinking about `eglretrace` here, where using a render node where available would mean being totally independent on the underlying rendering system.

It might still be possible to emulate the GLX calls from glretrace as EGL calls for use in the render node, but that’s for another feature request. :)

**Comment by jrfonseca** [comment]
> Indeed, I was thinking about eglretrace here, where using a render node where available would mean being totally independent on the underlying rendering system.

I'm afraid I don't have the time to pursue it myself, but I wouldn't oppose such feature, and would probably be easy for you to quickly hack something together: in addition to `glws_egl_xlib.cpp` and `glws_egl_android.cpp`, we just need a `glws_egl_headless.cpp`.

> It might still be possible to emulate the GLX calls from glretrace as EGL calls for use in the render node, but that’s for another feature request.

That's how eglretrace behaves today already by design: one can replay GL trace with eglretrace and EGL traces with glretrace, provided EGL supports OpenGL, or GLX supports OpenGL ES compatibility extensions.   This even works betwen GLX/WGL/CGL/EGL.

**Comment by evelikov** [comment]
@jrfonseca seems like the proposed patch adds exactly the same functionality as the waffle backend - wayland and/or raw gbm. Do you personally use it (apitrace+waffle), have you seen any issues with it ?

**Comment by jrfonseca** [comment]
No, I don't regularly use apitrace + waffle. I just built it a few times for sanity checking.

I rarely use apitrace + EGL too.

I don't want apitrace to depend on waffle for major desktop GL APIs (WGL/GLX/CGL).  It's simply too much a hassle to have an external dependency.  And it's not that much code necessary anyway.

I don't feel strongly about EGL: whether people prefer waffle, or dedicated backends, or both; I'm OK either way.

**Comment by evelikov** [comment]
Personally I do not see the waffle dependency as much of a hassle, in Android/Linux land. Although I do see your point - it isn't really needed if your platform has only a single GL winsys.

Not to mention that, with waffle, setting up the cmake includes/libs and managing window specifics on Windows is a bit awkward.

**Comment by jrfonseca** [comment]
With commit 661f2cfe53303dd60676e7fd0b25440be80d6644 it's now possible to choose `WAFFLE_PLATFORM` on Linux.  Per discussion on this issue and issue #369, I Waffle backend should meet @linkmauve needs, and there's nothing more to do here.
