### ISSUE TITLE
std::regex_error with GCC 4.7 / 4.8

### ISSUE THREAD

**Issue by farmboy0** [apitrace/apitrace#370]
The error message is:
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted

I bisected it to commit 36b945cb98a4e9009d57b8c20a720fc1a5905452

This happens for qapitrace as well the cli tools.

**Comment by jrfonseca** [comment]
I've been using this on Linux without problems. What linux/ gcc / libstdc++ you have?

**Comment by farmboy0** [comment]
I am using GCC 4.8.4 on Gentoo

**Comment by jrfonseca** [comment]
It looks like std::regex was only properly supported on GCC 4.9:

   http://stackoverflow.com/questions/12530406/is-gcc-4-7-and-gcc-4-8-buggy-about-regular-expressions

I'll to think a bit more how to handle this. On one hand regex are really handy. But it's not clear how much important is GCC 4.8 compatability.

In the meanwhile, if you can upgrade to GCC 4.9 that would be the idea.

**Comment by farmboy0** [comment]
why do you need those regexes on linux anyway?

**Comment by jrfonseca** [comment]
So I can dump Windows traces on Linux. Furthermore I plan to use regexes for glDraw* calls too.

Regardless of the API, maintainging these table by hand is not sustainable, as every new Direct3D version or OpenGL requires manually adding more entries.  While a regex is future proof.

**Comment by farmboy0** [comment]
Then I guess you will need to bump the gcc check to 4.9.

**Comment by farmboy0** [comment]
I have rebuilt apitrace with GCC 4.9.3 and it works again.

**Comment by jrfonseca** [comment]
> Then I guess you will need to bump the gcc check to 4.9.

Yes, I'll do that for now.

But I'm not sure if making GCC 4.9 a hard requirement is too aggressive, and if I should make it a soft requirement somehow, even if functionality is poorer.

**Comment by farmboy0** [comment]
how can you do that if you want to have the regexes?

**Comment by mtschoen** [comment]
Couldn't we just wrap the regex calls in one of these?

https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html

**Comment by jrfonseca** [comment]
> Couldn't we just wrap the regex calls in one of these?

Not unless we loose functionality, or add back the non-regex code to do it.  Neither ideal.

**Comment by jrfonseca** [comment]
> how can you do that if you want to have the regexes?

I was thinking of bundling a std::regex look alike, or drop-in replacement.  Just until GCC 4.9 is widely spread.  But I haven't search for one yet.

**Comment by jrfonseca** [comment]
I found a simple solution -- http://re2c.org/

I'll push after I have done more testing.
