### ISSUE TITLE
OpenGL 2015 ARB extensions support

### ISSUE THREAD

**Issue by oscarbg** [apitrace/apitrace#371]
Hi,
Khornos release 12-13 new ARB extensions which be would like a new OpenGL revision..
can you add support forthat?

**Comment by jrfonseca** [comment]
Done.

BTW, @oscarbg, it's rare for an apitrace user to be interested in so many different APIs.  If you don't mind asking, what are you using apitrace for?

**Comment by oscarbg** [comment]
not professionaly only for my hobby engine supporting D3D11/12 and OpenGL and soon hope Vulkan and Metal OSX..
