### ISSUE TITLE
Proper handling of GL_TEXTURE_SWIZZLE_RGBA

### ISSUE THREAD

**Issue by mosra** [apitrace/apitrace#376]
`GL_TEXTURE_SWIZZLE_RGBA` in `glTextureParameter()` accepts four values (red, green, blue and alpha) but apitrace is recording only the first value. It then emits an error while retracing, as only the first value is set to proper enum value and the remaining three are probably just some random memory:

![swizzle](https://cloud.githubusercontent.com/assets/344828/9385100/bb320fd0-4754-11e5-9a2b-e35ffec19728.png)

Anyway, thanks for this great tool!

**Comment by jrfonseca** [comment]
Should be fixed now.  Thanks for reporting this issue.
