### ISSUE TITLE
Recent apitrace breaks wine

### ISSUE THREAD

**Issue by sarnex** [apitrace/apitrace#378]
Hi. I use apitrace often in Wine to trace d3d9 calls to debug the Gallium Nine. If I use the latest msvc binary, I get `error: binaries mismatch: you need to use the 64-bits apitrace binaries to trace this application` in a 32 bit prefix with 32 bit wine with a 32 bit exe. My friend sent me a msvc binary from 2015.7.21 and apitrace works fine. I can't really bisect because I don't have access to a windows machine to compile.

Thanks,
sarnex

**Comment by jrfonseca** [comment]
Most likely the regression was introduced with commit 6ddfd98cdafefaa1b60273d5568b8dbd13730dae .  But this works fine natively, so it might be some WINE bug in IsWow64Process implementation.

That said, I just went through the instructions  in https://github.com/apitrace/apitrace/wiki/WINE#windows-native to trace a simple D3D9 application (vanilla Wine, not Gallium Nine) and all worked just fine.

But I did have to fix one other issue: ba0d9915742b28a6e705aa1af4310bb26a3098f2 .  Maybe that's the problem you're also having, and the 'binaries mismatch' warning is harmless.

Give another try with the next set of MSVC binaries (which should be re-uploaded automatically in 1-2 hours.)

BTW, it's possible (and not too dificult) to build apitrace with mingw cross-compilers. I do it all the time actually. You can see how from the Travis-CI build logs, such as https://travis-ci.org/apitrace/apitrace/jobs/76682613 and https://github.com/apitrace/apitrace/blob/master/.travis.yml

**Comment by sarnex** [comment]
@jrfonseca Hi, thanks for your response.

It took some time for the packages to update, and I just tested. The same issue occurs. I tried building apitrace myself but I didn't come with all of the dlls I needed, only a few files in the bin folder, so it was a no-go.

I'm using wine 1.7.50, basically wine git, so maybe there is a bug in wine introduced after 1.6 which it seems you used.

If it's not too annyoing, could you create a binary package with https://github.com/apitrace/apitrace/commit/6ddfd98cdafefaa1b60273d5568b8dbd13730dae reverted?

Thanks alot,
sarnex

**Comment by jrfonseca** [comment]
My wine prefix was actually 64bits, and by setting `WINEARCH=win32` I was able to repro the issue.

And it turns out this is not a bug in Wine but rather me forgetting about the IsWow64Process's semantics on commit 6ddfd98.

But commit bafc84295df205d0db53353734ec6d61e0f180c5 should now fix it.
