### ISSUE TITLE
Replaying don't work correctly with Unigine heaven's trace.

### ISSUE THREAD

**Issue by citrix123** [apitrace/apitrace#385]
Steps to reproduce.
1. Install Unigine Heaven.
2. Run heaven : 
    apitrace trace  ./heaven.
3. apitrace replay ./heaven.trace and observe corruption.

Note: Heaven is finely running while trace and without trace.

**Comment by jrfonseca** [comment]
What OS and was this seen?
And what GPU and graphics driver version you have?

**Comment by citrix123** [comment]
I am working on ubuntu 14.04, and GPU AMD pitcairn, with latest graphics Driver.

**Comment by jrfonseca** [comment]
Is this latest proprietary driver from AMD, or from Mesa?

Could you please provide the heaven.trace somehow (google driver, dropbox).  I strongly suspect the problem is specific to your setup.  It would not be the first time that trace/retrace doesn't work due bugs in AMD OpenGL drivers.

**Comment by amonakov** [comment]
If on Mesa, it's likely due to Mesa applying a workaround based on executable name: http://cgit.freedesktop.org/mesa/mesa/tree/src/mesa/drivers/dri/common/drirc

**Comment by jrfonseca** [comment]
@amonakov, great point.

In hindsight, I think that the executable name based Mesa workarounds is probably a bad idea, as it totally defeats tools like apitrace, causing problems to Mesa users and Mesa developers alike.

**Comment by jrfonseca** [comment]
@citrix123, you can verify this by renaming `glretrace` as `heaven_x86` and doing

    mv glretrace heaven_x86
    ./heaven_x86 heaven.trace

**Comment by citrix123** [comment]
I tried by renaming gletrace to heaven_x64, then it don't even open with
error

# heaven_x64 heaven_x64.trace
error: unsupported trace format version 5
error: failed to open heaven_x64.trace

And here is the attachment of trace.
Please have a look to it.
​
 heaven_x64.trace
<https://drive.google.com/file/d/0B3xj9W-gdGBTWHhzcmc2c0FtOFE/view?usp=drive_web>
​


On Thu, Sep 3, 2015 at 12:14 AM, José Fonseca <notifications@github.com>
wrote:

> @citrix123 <https://github.com/citrix123>, you can verify this by
> renaming glretrace as heaven_x86 and doing
>
> mv glretrace heaven_x86
> ./heaven_x86 heaven.trace
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apitrace/apitrace/issues/385#issuecomment-137206051>.
>



-- 
Rahul jain

**Comment by citrix123** [comment]
I am using latest proprietary driver from AMD.

**Comment by jrfonseca** [comment]
Your heaven_x64.trace replays fine here on NVIDIA

    $ glxinfo |grep  'OpenGL \w\+ string:'
    OpenGL vendor string: NVIDIA Corporation
    OpenGL renderer string: Quadro K1000M/PCIe/SSE2
    OpenGL version string: 4.5.0 NVIDIA 346.59

I don't have an AMD machine.

I also don't understand how "unsupported trace format version 5" message can come from renaming glretrace to heaven_x64.   Make sure you run "./heaven_x64" and not "heaven_x64".

**Comment by citrix123** [comment]
Hi,
   I tried this,
   mv /usr/bin/glretrace /usr/bin/heaven_x64
   heaven_x64 ./heaven_x64

And then i am getting that error.
I will try to replay this trace on Nvidia Machine and let you know.

Thanks,
Rahul

On Thu, Sep 3, 2015 at 7:36 PM, José Fonseca <notifications@github.com>
wrote:

> Your heaven_x64.trace replays fine here on NVIDIA
>
> $ glxinfo |grep  'OpenGL \w\+ string:'
> OpenGL vendor string: NVIDIA Corporation
> OpenGL renderer string: Quadro K1000M/PCIe/SSE2
> OpenGL version string: 4.5.0 NVIDIA 346.59
>
> I don't have an AMD machine.
>
> I also don't understand how "unsupported trace format version 5" message
> can come from renaming glretrace to heaven_x64. Make sure you run
> "./heaven_x64" and not "heaven_x64".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apitrace/apitrace/issues/385#issuecomment-137460645>.
>



-- 
Rahul jain

**Comment by jrfonseca** [comment]
So you're using apitrace from your linux distro? Please try building apitrace from source.

**Comment by citrix123** [comment]
Hi ,
I had compiled from source and then used it.

**Comment by jrfonseca** [comment]
In that case you shouldn't use `/usr/bin/glretrace`, as that's probably the one from your distribution, unless you installed it there yourself.

Instead, you should do

    cd /path/to/where/you/have/source/of/apitrace/
    make
    mv glretrace heaven_x86
    ./heaven_x86  /path/to/heaven_x86.trace

**Comment by citrix123** [comment]
Yes this worked for me .. Now that trace is replaying normally.
So do i have to run the trace every time like this only??

**Comment by jrfonseca** [comment]
> So do i have to run the trace every time like this only??
One final question:
I'm afraid that if the driver checks the process name, then there's no alternative.

We could however one day record the executable name in the trace, and then automatically use a symlink/copy when replaying.

But it's quite a fair a bit of work.


One final question: could you confirm the output of `glxinfo |grep  'OpenGL \w\+ string:'`, for future reference?

**Comment by citrix123** [comment]
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon R9 200 Series
OpenGL version string: 4.5.13684 Compatibility Profile Context 15.20

On Wed, Sep 9, 2015 at 8:46 PM, José Fonseca <notifications@github.com>
wrote:

> So do i have to run the trace every time like this only??
> One final question:
> I'm afraid that if the driver checks the process name, then there's no
> alternative.
>
> We could however one day record the executable name in the trace, and then
> automatically use a symlink/copy when replaying.
>
> But it's quite a fair a bit of work.
>
> One final question: could you confirm the output of glxinfo |grep 'OpenGL
> \w\+ string:', for future reference?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apitrace/apitrace/issues/385#issuecomment-138943437>.
>



-- 
Rahul jain
