### ISSUE TITLE
apitrace diff using sdiff exits with undefined variable error

### ISSUE THREAD

**Issue by mosra** [apitrace/apitrace#386]
```
$ apitrace diff --tool=sdiff a.trace b.trace
Traceback (most recent call last):
  File "/usr/bin/../lib/apitrace/scripts/tracediff.py", line 583, in <module>
    main()
  File "/usr/bin/../lib/apitrace/scripts/tracediff.py", line 576, in main
    differ = factory(options.apitrace, options)
  File "/usr/bin/../lib/apitrace/scripts/tracediff.py", line 131, in __init__
    if width is None:
UnboundLocalError: local variable 'width' referenced before assignment
```

[Relevant section](https://github.com/apitrace/apitrace/blob/7ad1d34c97cb0d2f07a381d7664f1ba0f1be410b/scripts/tracediff.py#L131-L138) of the script:
```py
        elif tool == 'sdiff':
            if width is None:
                import curses
                curses.setupterm()
                width = curses.tigetnum('cols')
            self.diff_args += [
                '--width=%u' % width,
                '--speed-large-files',
            ]
```

Probably caused by d587885d2ec9a3d4d5b0e424c89966f796ddc6f7, I guess the fix could be done by replacing `width` by `options.width`, but I'm not sure if there are any other occurences.

**Comment by jrfonseca** [comment]
> I guess the fix could be done by replacing `width` by `options.width`, but I'm not sure if there are any other occurences.

This seems the right fix to me too. Pushed now. Thanks.
