### ISSUE TITLE
Screenshots are only 32×32 when using the WAFFLE_PLATFORM=gbm

### ISSUE THREAD

**Issue by linkmauve** [apitrace/apitrace#390]
On the gbm platform, dumping a bunch of screenshots with `eglretrace -s img_ some_apitrace.trace` results in 32×32 images of only a small part of the framebuffer.

Additionally, every backend prints this error, which might be related:
```
error: drawable failed to resize: expected 640x480, got 32x32
```

**Comment by jrfonseca** [comment]
This is arguably a bug in waffle.

EGL often doesn't honor window resizes, so `apitrace/retrace/glws_egl_xlib.cpp` we recreate drawables to ensure they are properly resized.

We could do the same in `glws_waffle.cpp`, but Waffle should abstract this inconsistencies away from its users, as not all implementations need this (e.g., GLX and WGL do not.)

**Comment by jrfonseca** [comment]
I see you followed up upstream. Thanks.  Closing this now, given no further action is planned from apitrace side.
