### ISSUE TITLE
Apitrace doesn't give any traces in Android 5.0(Note 5)

### ISSUE THREAD

**Issue by nam1796** [apitrace/apitrace#393]
I have used version of Android 5.0(Note 5) with root permission and  try to examine apitrace log (for example, "com.android.opengl" package).I followed "INSTALL.markdown" and "Dalvik.markdown" documents. but when i used command "adb logcat *:S apitrace" the output: 

$adb logcat *:S apitrace
--------- beginning of main
--------- beginning of system
D/apitrace(14136): apitrace: loaded into /system/bin/app_process
D/apitrace(14274): apitrace: loaded into /system/bin/app_process
D/apitrace(15075): apitrace: loaded into /system/bin/app_process
D/apitrace(15414): apitrace: loaded into /system/bin/app_process
D/apitrace(16655): apitrace: loaded into /system/bin/app_process
D/apitrace(16849): apitrace: loaded into /system/bin/app_process
D/apitrace(20915): apitrace: loaded into /system/bin/app_process

 and there are no .TRACE file in package "data/data/com.android.opengl"
I already checked with command: adb getprop wrap.com.android.opengl. It returned LD_PRELOAD=/data/libgnustl_shared.so:/data/egltrace.so.

**Comment by jrfonseca** [comment]
I don't use Android myself.

You might get more help for Android related matters if you post on the [mailing list](http://lists.freedesktop.org/mailman/listinfo/apitrace).

**Comment by jrfonseca** [comment]
I'm afraid Android is no longer supported.  See #521
