### ISSUE TITLE
Abort (unimplemented code) on simple trace

### ISSUE THREAD

**Issue by io7m** [apitrace/apitrace#402]
[trace.zip](https://github.com/apitrace/apitrace/files/59489/trace.zip)

Upon reaching call `9678`, `qapitrace` aborts:

```
$ qapitrace /tmp/trace.trace 
Loading: "/tmp/trace.trace"
Running: "glretrace" "-D" "9678" "--dump-format" "ubjson" "/tmp/trace.trace"
/home/someone/git/com.github/apitrace/apitrace/gui/qubjson.cpp:138: int readSize(QDataStream&, ubjson::Marker): Unimplemented code.
ASSERT: "0" in file /home/someone/git/com.github/apitrace/apitrace/gui/qubjson.cpp, line 284
Aborted (core dumped)
```

Selecting the call in `qapitrace` will cause the abort. Selecting a much later call such as `10000` will instead result in no state being calculated and `qapitrace` saying "Process exited with non zero exit code".

This is from 2d70fdfc0244a7217df1cfa7df9f4798cbfa3af6, on:

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.0.6
OpenGL core profile shading language version string: 3.30

Linux copperhead 4.2.4-1-ARCH #1 SMP PREEMPT Fri Oct 23 07:32:38 CEST 2015 x86_64 GNU/Linux
```

**Comment by jrfonseca** [comment]
glretrace is crashing:

    $ glretrace -D 9678 issues/402/trace.trace > /dev/null
    apitrace: warning: got null GL_VERSION
    glretrace: helpers/glprofile.cpp:296: void glprofile::Extensions::getCurrentContextExtensions(const glprofile::Profile&): Assertion `begin' failed.
    apitrace: warning: caught signal 6
    9679: error: caught an unhandled exception
    apitrace: info: taking default action for signal 6

Call 9678 binds a NULL context, so there's no current state:

    $ apitrace dump issues/402/trace.trace | grep -C2 9678
    9662 glXGetVisualFromFBConfig(dpy = 0x7fdbc50d8700, config = 0x7fdbc516e260) = &{visual = 0x7fdbc40eb2e8, visualid = 167, screen = 0, depth = 24, c_class = 4, red_mask = 16711680, green_mask = 65280, blue_mask = 255, colormap_size = 256, bits_per_rgb = 8}
    9677 glFinish()
    9678 glXMakeContextCurrent(dpy = 0x7fdbc4000b90, draw = 0, read = 0, ctx = NULL) = True
    9679 glXMakeContextCurrent(dpy = 0x7fdbc50d8700, draw = 0, read = 0, ctx = 0x7fdbc558fb40) = True
    9680 glFinish()

But yeah, there's something weird happening in call 9705, at least for me:

    $ glretrace issues/402/trace.trace  |& github-quote 
    apitrace: warning: got null GL_VERSION
    glretrace: helpers/glprofile.cpp:296: void glprofile::Extensions::getCurrentContextExtensions(const glprofile::Profile&): Assertion `begin' failed.
    apitrace: warning: caught signal 6
    9705: error: caught an unhandled exception
    apitrace: info: taking default action for signal 6

Not sure exactly why:

    $ apitrace dump issues/402/trace.trace | grep -C2 9705
    9687 glXGetVisualFromFBConfig(dpy = 0x7fdc3485cb00, config = 0x7fdc34afbb40) = &{visual = 0x7fdc34867198, visualid = 167, screen = 0, depth = 24, c_class = 4, red_mask = 16711680, green_mask = 65280, blue_mask = 255, colormap_size = 256, bits_per_rgb = 8}
    9704 glXCreateContextAttribsARB(dpy = 0x7fdc3485cb00, config = 0x7fdc34afbb40, share_context = NULL, direct = True, attrib_list = {GLX_CONTEXT_MAJOR_VERSION_ARB, 3, GLX_CONTEXT_MINOR_VERSION_ARB, 3, GLX_RENDER_TYPE, GLX_RGBA_TYPE, GLX_CONTEXT_FLAGS_ARB, 0x0, GLX_CONTEXT_PROFILE_MASK_ARB, GLX_CONTEXT_CORE_PROFILE_BIT_ARB, 0}) = 0x7fdc34b002a0
    9705 glXMakeContextCurrent(dpy = 0x7fdc3485cb00, draw = 0, read = 0, ctx = 0x7fdc34b002a0) = True
    9711 glGetIntegerv(pname = GL_MAJOR_VERSION, params = &3)
    9712 glGetIntegerv(pname = GL_MINOR_VERSION, params = &3)

**Comment by io7m** [comment]
I should mention that the vast majority of the context calls are [JOGL](http://jogamp.org/jogl/www/) setting itself up. Control doesn't reach my code until call `9788`.

**Comment by io7m** [comment]
Not to push, but any ETA on a fix for this? I'm fairly stuck without a working OpenGL debugger.

**Comment by jrfonseca** [comment]
The problem was caused due to the binding a non-null context with a null drawable:

    9705 glXMakeContextCurrent(dpy = 0x7fdc3485cb00, draw = 0, read = 0, ctx = 0x7fdc34b002a0) = True

This is legal, and in fact required to be supported on GL 3.2 and higher.  But in fact apitrace has poor support for it.

I'm gonna push a minimum fix for it, but I wouldn't be surprised if more tweaks are necessary.

I presume JOGL was working before, so maybe JOGL recently  changed to do this?

**Comment by io7m** [comment]
> I presume JOGL was working before, so maybe JOGL recently changed to do this?

Yeah, I think the semantics change just about every release! Thanks for the fix, I'll be trying it out today.
