### ISSUE TITLE
ubjson is broken on ARM Android

### ISSUE THREAD

**Issue by stefand** [apitrace/apitrace#410]
Retracing on ARM-based Android is broken for me since commit c296a3e80977e6cb0eb7fd2676ff074967704a88. Various problems were fixed in follow-up commits, but at least one problem remains: Writing a signed -1 or unsigned 255 char in the ubjson writer corrupts the output stream.

I believe the problem happens because android.toolchain.cmake sets -fsigned-char, but ARM defaults to unsigned chars. A very similar symptom is described e.g. here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47275 . I have reported the problem as https://github.com/taka-no-me/android-cmake/issues/74.

I haven't tested yet if simply removing the compiler option is enough to fix the problem. There may be more integer handling problems in the code.

**Comment by stefand** [comment]
[0001-Pass-chars-as-pointers-to-ostream.txt](https://github.com/apitrace/apitrace/files/74170/0001-Pass-chars-as-pointers-to-ostream.txt)

This patch appears to work around the problem, but it is not correct as other ABI incompatibilities may happen.

Removing -fsigned-char from android.toolchain.cmake also appears to make things work at the pre-ubjson level. That was just a quick test though, so no guarantees.

Retracing on Android reports a GL_STENCIL_VALUE_MASK of -1, whereas retracing the same trace on the Desktop (Gallium llvmpipe) says it is 255. I have yet to find out where this integer interpretation difference happens...

**Comment by stefand** [comment]
The -1 vs 255 is not a bug I think. llvmpipe defaults to a stencil mask of 0x000000ff, whereas my android GPU has 0xffffffff. In both cases an 8 bit stencil buffer is used, so the difference doesn't really matter.

**Comment by jrfonseca** [comment]
Per https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47275 this really needs to be fixed in android-cmake.

Until android-cmake is fixed, we could modify the android instructions to patch the `android.toolchain.cmake` to not add `-fsigned-char`.  But I rather not complicate the C++ code.

> The -1 vs 255 is not a bug I think.

Yep.  This is a slight ambiguity in the default initial value of the stencil mask allowed by the spec, but it doesn't make difference in practice.

**Comment by jrfonseca** [comment]
I'm afraid Android is no longer supported.  See #521
