### ISSUE TITLE
No Documentation directory cmake build flag.

### ISSUE THREAD

**Issue by orbea** [apitrace/apitrace#411]
Can you please add a cmake build flag for the documentation directory?  It would mean a lot to me if I could install the documentation into the correct directory without:
```
mv $PKG/usr/share/doc/$PRGNAM/* $PKG/usr/doc/$PRGNAM-$VERSION
rm -rf $PKG/usr/share
```
Thanks!

**Comment by jrfonseca** [comment]
Isn't `/usr/share/doc/foo` the standard for documentation on Linux?

What Linux distro is this?  Maybe there are some CMake recipes I can use to get this right.

**Comment by orbea** [comment]
Sorry for the slow reply, I got distracted with other priorities...

This is on slackware linux where the default documentation directory is /usr/doc/foo and /usr/share/doc is symlinked to /usr/doc.  Many other distros follow a different standard.

I have seen this in other programs with cmake, so I assume its possible.  Unfortunately my experience extends only as far as building with cmake...

**Comment by orbea** [comment]
Thanks, that fixes it.
