### ISSUE TITLE
error: failed to execute: glretrace ...

### ISSUE THREAD

**Issue by techtonik** [apitrace/apitrace#415]
Can't get `apitrace replay` working on Linux. Compiled as described in https://github.com/apitrace/apitrace/blob/master/docs/INSTALL.markdown, `apitrace` binary is in `build/` dir, but running it on a .trace file gives this error.

    error: failed to execute: glretrace testrun.trace

I don't see any `glretrace` binary in build directory. What to do?

**Comment by jrfonseca** [comment]
You're most likely missing the X headers.

CMake should have printed a `Could not find X11` somewhere.

**Comment by techtonik** [comment]
I explicitly installed `libx11-dev` after I've got `fatal error: X11/Xlib.h: No such file or directory`, but it doesn't help.

There are some warnings though:
```
[ 75%] Generating glretrace_gl.cpp
warning: unsupported glVertexArrayRangeAPPLE call
...
```

**Comment by jrfonseca** [comment]
Weird. From the `Generating glretrace_gl.cpp` there's no doubt that either `glretrace` or `eglretrace` should executable should have been created in the top of the build directory. 

Does `find . -name glretrace -or -name eglretrace` command output anything?

**Comment by techtonik** [comment]
> Does find . -name glretrace -or -name eglretrace command output anything?

Nothing.

**Comment by jrfonseca** [comment]
Very weird.  OK, to diagnose this, I'll need you to restart from scratch: wipe out both source and build directory, download again, then provide command lines for cmake and make, plus their output.

**Comment by techtonik** [comment]
Restarted from scratch. Now it compiled ok.

https://pastebin.mozilla.org/8856911

I added https://github.com/apitrace/apitrace/pull/413 to mention that libx11-dev package is needed.

**Comment by techtonik** [comment]
Now it works ok. =)
