### ISSUE TITLE
[Feature request] profiling compute shaders

### ISSUE THREAD

**Issue by haasn** [apitrace/apitrace#428]
In the qapitrace “profile” output I can only see the time it took for my regular draw passes to execute, but not any compute shaders that executed.

It would be fantastic if you could add a summary of programs with compute shaders + the amount of time spent on DispatchCompute.

It's especially important for me because I'm trying to benchmark performance gains from switching to compute shaders, which requires the ability to directly compare execution times between my fragment shaders and my equivalent compute shaders.

**Comment by jrfonseca** [comment]
Done.
