### ISSUE TITLE
Use components to find QT5 in CMakeLists.txt

### ISSUE THREAD

**Issue by iiv3** [apitrace/apitrace#429]
The official documentation for this feature is here: [CMake - Packages_with_components]
(https://cmake.org/Wiki/CMake:How_To_Find_Libraries#Packages_with_components)

The line could look like :
`find_package(Qt5 COMPONENTS Widgets WebKitWidgets ${REQUIRE_GUI})`

It's common for QT to be installed in its own prefix, even more so when you need two different major versions. My distributions still ships only QT4, so I've built my own QT5.
However to allow finding of these components environment variables are needed.

By using the above method, a single `Qt5_DIR` is sufficient to locate all its components. Otherwise I'd need to set vars for every single component, and QT have plenty of them.

**Comment by jrfonseca** [comment]
The CMake wikipage you refer to hasn't been updated in ages.

This official documentation on Qt and CMake is http://doc.qt.io/qt-5/cmake-manual.html  and that's what I'm following here.

Furthermore I build with QT5 on non-standard directory all the time.  All I need to do is pass `-CMAKE_PREFIX_PATH=/path/to/where/qt5/lives`.

My link above explains this:

> In order for find_package to be successful, Qt 5 must be found below the CMAKE_PREFIX_PATH, or the Qt5<Module>_DIR must be set in the CMake cache to the location of the Qt5WidgetsConfig.cmake file. The easiest way to use CMake is to set the CMAKE_PREFIX_PATH environment variable to the install prefix of Qt 5."

It should work for you too.
