### ISSUE TITLE
d3d 9 buffer writes should be captured even if readonly is set

### ISSUE THREAD

**Issue by axeldavy** [apitrace/apitrace#435]
Hi,

Our tests (which confirm some information read on the driver ddi doc) seem to show that for most usage creation flags/lock flags, the READONLY flag is ignored.

We have found games that rely on readonly to be ignored, and it would be great if apitrace could catch that as well, i.e. apitrace should memcpy the buffer content even if there is the readonly flag.

Currently when the app is using the readonly flag, apitrace doesn't record the write to the buffer, preventing traces to catch the application behaviour.

**Comment by jrfonseca** [comment]
D3D9 API doesn't allow rendering into buffers, so apps should rarely (if ever) lock buffers with READONLY with intent for only reading.  Therefore there should be little to no downside to the workaround of ignoring READONLY while tracing.

However, I'd like to better understand this and reproduce it myself.  I couldn't find any MSDN docs indicating that READONLY should be ignored.

Could you point out any documentation you know, and list the apps that make this assumption?

**Comment by axeldavy** [comment]
Here is from the documentation for the kernel driver (windows 2000/xp and previous):
https://msdn.microsoft.com/en-us/library/windows/hardware/ff568216(v=vs.85).aspx

Here is the interesting part:
https://msdn.microsoft.com/en-us/library/windows/hardware/ff551637(v=vs.85).aspx
"DDLOCK_READONLY: The surface being locked will only be read from. On Windows 2000 and later, this flag is never set."

In fact there is some nvidia or amd presentation saying the flag is ignored, but I don't remember which one.

**Comment by axeldavy** [comment]
An example of app relying of READONLY to be ignored is World of Warships.

I think it allocates some vertex buffers in default pool without usage flag (which is quite bad for performance if I understand the NV/AMD slides I found and other docs), and for these buffers, it locks them with readonly flag twice, and then uses them for all the remaining frames.
If readonly is not ignored, the game renders very bad.

**Comment by jrfonseca** [comment]
It should be fixed now.

Thanks.
