### ISSUE TITLE
Crash when tracing Xonotic v0.8, due to missing (GL 4.4) GL_ARB_query_buffer_object extension support

### ISSUE THREAD

**Issue by eero-t** [apitrace/apitrace#442]
Normally occlusion queries have pointer to integer, but with GL 4.4 GL_ARB_query_buffer_object extension, the parameter can be an index:
https://www.opengl.org/registry/specs/ARB/query_buffer_object.txt

Apitrace doesn't seem to support this extension as it crashes when tracing Xonotic v0.8.x with GL driver supporting GL 4.4 or newer.  Apitrace unconditionally assumes that the parameter is a pointer instead of e.g. checking whether given buffer object is bound to target:

<pre>
Thread 1 "xonotic-linux64" received signal SIGSEGV, Segmentation fault.
glGetQueryObjectivARB (id=<optimized out>, pname=<optimized out>, params=0x4)
    at /home/testrunner/work/apitrace/build/wrappers/glxtrace.cpp:48258
48258	    trace::localWriter.writeSInt((params)[_iGLint]);
(gdb) list
48253	    if (params) {
48254	        size_t _cGLint = _gl_param_size(pname) > 0 ? _gl_param_size(pname) : 0;
48255	        trace::localWriter.beginArray(_cGLint);
48256	        for (size_t _iGLint = 0; _iGLint < _cGLint; ++_iGLint) {
48257	            trace::localWriter.beginElement();
48258	    trace::localWriter.writeSInt((params)[_iGLint]);
48259	            trace::localWriter.endElement();
48260	        }
(gdb) info locals
_iGLint = 0
_cGLint = 1
_call = 200624
</pre>

Tracing works if driver support for GL_ARB_query_buffer_object extension is disabled.

The corresponding Xonotic / DarkPlaces engine code from https://gitlab.com/xonotic/darkplaces/blob/div0-stable/r_shadow.c is this:
<pre>
                        // See if we can use the GPU-side method to prevent implicit sync
                        if (vid.support.arb_query_buffer_object) {
#define BUFFER_OFFSET(i)    ((GLint *)((unsigned char*)NULL + (i)))
                                if (!r_shadow_occlusion_buf) {
                                        qglGenBuffersARB(1, &r_shadow_occlusion_buf);
                                        qglBindBufferARB(GL_QUERY_BUFFER_ARB, r_shadow_occlusion_buf);
                                        qglBufferDataARB(GL_QUERY_BUFFER_ARB, 8, NULL, GL_DYNAMIC_COPY);
                                } else {
                                        qglBindBufferARB(GL_QUERY_BUFFER_ARB, r_shadow_occlusion_buf);
                                }
                                qglGetQueryObjectivARB(rtlight->corona_queryindex_visiblepixels, GL_QUERY_RESULT_ARB, BUFFER_OFFSET(0));
                                qglGetQueryObjectivARB(rtlight->corona_queryindex_allpixels, GL_QUERY_RESULT_ARB, BUFFER_OFFSET(4));
                                qglBindBufferBase(GL_UNIFORM_BUFFER, 0, r_shadow_occlusion_buf);
                                occlude = MATERIALFLAG_OCCLUDE;
                        } else {
                                qglGetQueryObjectivARB(rtlight->corona_queryindex_visiblepixels, GL_QUERY_RESULT_ARB, &visiblepixels);
                                qglGetQueryObjectivARB(rtlight->corona_queryindex_allpixels, GL_QUERY_RESULT_ARB, &allpixels); 
                                if (visiblepixels < 1 || allpixels < 1)
                                        return;
                                rtlight->corona_visibility *= bound(0, (float)visiblepixels / (float)allpixels, 1);
                        }
</pre>

**Comment by jrfonseca** [comment]
Thanks for the detailed bug report.

It should be fixed now.  I tested with `gl-440-query-occlusion` sample from https://github.com/g-truc/ogl-samples.

Please confirm it fixes Xonotic / DarkPlaces too, and reopen if not.

**Comment by eero-t** [comment]
Verified.

Everything works now fine with Xonotic and I see the GL_ARB_query_buffer_object functions in the trace.  Thanks for the fix!
