### ISSUE TITLE
retrace: Markers cause GL errors to be generated

### ISSUE THREAD

**Issue by imirkin** [apitrace/apitrace#443]
Running glretrace with --markers, I get this:

```
Mesa: User error: GL_INVALID_VALUE in glDebugMessageInsert(length=4096, which is not less than GL_MAX_DEBUG_MESSAGE_LENGTH=4096)
811: message: major api error 1: GL_INVALID_VALUE in glDebugMessageInsert(length=4096, which is not less than GL_MAX_DEBUG_MESSAGE_LENGTH=4096)
811: message: shader compiler issue 2: type: 1, local: 0, gpr: 8, inst: 15, bytes: 120
811 @0 glCreateShaderProgramv(type = GL_FRAGMENT_SHADER, count = 2, strings = {"#version 330 core
#extension GL_ARB_shading_language_420pack: require
#extension GL_ARB_separate_shader_objects: require
#define DISABLE_GL42_image
#define ZERO_TO_ONE_DEPTH
#define pGL_ES 0
...
```
Clearly that shader is just longer than 4k, and retrace is truncating it. However it seems like the length is off by 1? (This is on top of mesa, obviously.)

From KHR_debug:

    The lengths of all messages, including their null terminators, must be
    guaranteed to be less or equal to the value of the
    implementation-dependent constant MAX_DEBUG_MESSAGE_LENGTH.

    ...

    The parameter <length> contains the number of characters in <buf>

I guess the interpretation Mesa has taken is that length does not include the null terminator.

**Comment by jrfonseca** [comment]
`KHR_debug` also says:

    [...] The error INVALID_VALUE will be 
    generated if the number of characters in <buf>, excluding the null
    terminator when <length> is negative, is not less than the value of
    MAX_DEBUG_MESSAGE_LENGTH.

So the extension intent is ambiguous.  Anyway, one less char makes no much difference here.  I'll fix this.

**Comment by imirkin** [comment]
Well, your quote again implies that the number of characters before the null has to be less than MAX_DEBUG_MESSAGE_LENGTH. And it makes some amount of sense that length is something like what's returned by strlen, hence no null.

I guess you could ask for a spec clarification if you _really_ cared...

**Comment by jrfonseca** [comment]
No I don't care that much for apitrace.  I rather err on the side of caution anyway,

But in face of this, I think that Mesa might want to err on the side of forgiveness here.
