### ISSUE TITLE
Option to not store texture data

### ISSUE THREAD

**Issue by sesse** [apitrace/apitrace#444]
Hi,

Would it be possible to not store textures when tracing? I don't have any need for them (I'm trying to debug OpenGL driver crashes only, which don't depend on texture contents), and I stream several hundred megabytes of data each second. This causes my app not to run well under apitrace (if it drops too many frames from its 60 fps target, it's generally unhappy), as it simply becomes too slow.

**Comment by jrfonseca** [comment]
It's not that trivial to accomplish. `glTexImage*` calls must still be recorded, and they must still receive pointer to valid memory that's as big as the blobs are, or the OpenGL driver internal state won't be consistent.

Furthermore if you use PBOs it's impossible to distinguish texture data from vertex/index data.

So implementing this feature in apitrace is impractical, just too complicated.  But even a hack of apitrace source code is far from trivial... 

If this is an app you're developing, then my recommendation is for you to hack your app directly: create a big PBO (as big as the biggest texture), don't bother writing into it, just bind it whenever you call glTexImage.  If your app already uses PBOs even simpler -- just don't write into them.

**Comment by sesse** [comment]
My app uses persistently-mapped PBOs (several, actually). How does that interact with what you suggested? (To make things worse, I use explicit flushing, which apitrace warns is poorly supported.)

**Comment by jrfonseca** [comment]
> My app uses persistently-mapped PBOs (several, actually). How does that interact with what you suggested? 

It really depends if you set `GL_MAP_FLUSH_EXPLICIT_BIT` or not, which is not entirely clear to me yet.

If you do, you should modify the app to not call glFlushMappedBufferRange.  If you don't, then there should be nothing more to do -- apitrace should be ignoring those writes already.

> To make things worse, I use explicit flushing, which apitrace warns is poorly supported.

apitrace should support mappings with `GL_MAP_FLUSH_EXPLICIT_BIT` just fine, persistent or not.  It shouldn't warn about it.

So something's not right here: either apitrace is warning when it shouldn't, or you're not setting `GL_MAP_FLUSH_EXPLICIT_BIT` bit in all the places that should have it.

It's `MAP_PERSISTENT_BIT` without `FLUSH_EXPLICIT_BIT` that's the problem.  Note you shouldn't call `glFlushMappedBufferRange` for a mapping created without `FLUSH_EXPLICIT_BIT`, per https://www.opengl.org/sdk/docs/man4/html/glFlushMappedBufferRange.xhtml .

**Comment by sesse** [comment]
I have some that are persistent without flush, but those are only ever read from (and only then after a barrier followed by a client wait on a fence). That ought to be allowed, no?

The ones that I flush are mapped with FLUSH_EXPLICIT_BIT.

**Comment by sesse** [comment]
Turning off the flush makes the trace go full speed ahead, by the way. :-)

**Comment by jrfonseca** [comment]
> I have some that are persistent without flush, but those are only ever read from (and only then after a barrier followed by a client wait on a fence). That ought to be allowed, no?

You're right -- I've spotted some flaws in the warning logic. It should be fixed with 34d047c48c89aa5f7310e48f3ec326c3ff40598c.  Let me know otherwise.

> Turning off the flush makes the trace go full speed ahead, by the way. :-)

Great.  Your problem's solved then.

**Comment by sesse** [comment]
Yes, my apitrace problem is solved—thanks. Now I just need to solve my OpenGL problem. The program crashed after eight hours, 3.8GB of trace, over 450 million OpenGL calls… Debugging through replay isn't going to be so quick :-)
