### ISSUE TITLE
egltrace.so make application hang

### ISSUE THREAD

**Issue by rainboy93** [apitrace/apitrace#447]
Hi,
I'm having issues with tracing on Android devices. (I use three Android phones which run Android 5.1.1, 5.0 and 4.3). I follow the steps in INSTALL.markdown and ANDROID.markdown with root permission. Everything just ok until i run the app (com.android.settings), the app just hang with black screen (all three devices) and not responding. When i type _adb logcat *:S apitrace_ the following line appear: 
_root@m0:/ # logcat *:S apitrace
--------- beginning of /dev/log/main
D/apitrace(15703): apitrace: loaded into com.android.settings
--------- beginning of /dev/log/system
D/apitrace(16375): apitrace: loaded into com.android.settings_

**Comment by jrfonseca** [comment]
I don't use Android myself.  You might get more feedback on https://lists.freedesktop.org/mailman/listinfo/apitrace

**Comment by xtrawurst** [comment]
If you have source access to the app you may prefer to just link against libegltrace.so (instead of linking against OpenGL ES). This has worked out for me. BogDan Vatra has more information about this:

https://github.com/bog-dan-ro/0ad/commit/3c75fb9c9c33f8145c77e62657331f4b7fd3bfaa

**Comment by jrfonseca** [comment]
I'm afraid Android is no longer supported.  See #521
