### ISSUE TITLE
Implicit buffer unmap is not handled during retrace and leads to crashes

### ISSUE THREAD

**Issue by nhaehnle** [apitrace/apitrace#450]
Section 6.3.1 (Unmapping Buffers) of the OpenGL 4.5 (Compatibility Profile) spec says: "Unmapping that occurs as a side effect of buffer deletion (...) or reinitialization by BufferData is not an error."

XCOM2 actually makes use of this.

During retrace, the RegionMap is not properly cleaned of mappings corresponding to deleted or reinitialized buffers, which leads to later address lookups becoming confused and writing over random memory / crashing.

**Comment by nhaehnle** [comment]
This patch seems to be sufficient to get XCOM2 traces to work, but it has some obvious holes because it relies on the *Named* API being available and doesn't handle glBufferData:

[implicit-unmap.diff.txt](https://github.com/apitrace/apitrace/files/232773/implicit-unmap.diff.txt)

**Comment by jrfonseca** [comment]
@nhaehnle I've pushed your fix with minor modifications.  Thanks.  I'm deferring glBufferData and non-DSA support until it's actually needed.

**Comment by nhaehnle** [comment]
Thanks!
