### ISSUE TITLE
Windows 10 SDK problem with Cmake (also Qt)

### ISSUE THREAD

**Issue by OsirisDeveloper** [apitrace/apitrace#451]
Hello,

I trying to make VS2015 solution with CMake  but have some problems:
```
CMake Warning at CMakeLists.txt:122 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at CMakeLists.txt:123 (find_package):
  By not providing "FindQt5Network.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Network", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Network" with
  any of the following names:

    Qt5NetworkConfig.cmake
    qt5network-config.cmake

  Add the installation prefix of "Qt5Network" to CMAKE_PREFIX_PATH or set
  "Qt5Network_DIR" to a directory containing one of the above files.  If
  "Qt5Network" provides a separate development package or SDK, be sure it has
  been installed.


CMake Error at CMakeLists.txt:156 (message):
  Windows 10 SDK must be selected (-DCMAKE_SYSTEM_VERSION=10.0) for D3D11.3
  support
```
Main problem is Windows 10 SDK , I just installed it but I can't explain it to Cmake.

Seond problem is Qt folders, it is folders on includes? I set this folders but he still can't find them.

**Comment by OsirisDeveloper** [comment]
I solved problem with Qt - just need to set path like:
 CMAKE_PREFIX_PATH=D:\Qt\Qt5.6\5.6\msvc2015

Still have a problem with Win 10 SDK

**Comment by OsirisDeveloper** [comment]
By the way, maybe you have VS2015 solution, I could try configure it directly.

**Comment by jrfonseca** [comment]
You need to pass `-DCMAKE_SYSTEM_VERSION=10.0` when configuring apitrace.  You should also use a modern CMake version.

I don't have VS2015 solutions: the point of using CMake is that it should generate a VS2015 solution automatically for you.

**Comment by jrfonseca** [comment]
Also, please read https://github.com/apitrace/apitrace/blob/master/docs/INSTALL.markdown#windows .

The `CMAKE_PREFIX_PATH` is already explained there.  So is `CMAKE_SYSTEM_VERSION`

**Comment by OsirisDeveloper** [comment]
> You need to pass  -DCMAKE_SYSTEM_VERSION=10.0  when configuring apitrace. You should also > use a modern CMake version.
Thanks for answer! I think I did everything what you sad
![cmake](https://cloud.githubusercontent.com/assets/17878405/14762288/9fab73b4-0987-11e6-88ef-15ead64d1f44.jpg)

**Comment by OsirisDeveloper** [comment]
Can you say what exactly program checks, maybe some PATH is wrong. And off course I installed Win 10 SDK, but I have Win 8.1 and think this is not problem.

**Comment by jrfonseca** [comment]
The cmake should be executed from the apitrace source dir.  But your screenshot shows cmake-gui being executed from Visual Studio subdir.

Also you don't need to run Visual Studio Command line at all.  That's what's probably interfering with CMake.

In short, you need to do is:
* delete the D:\apitrace\build\ subdirectory
* open command line prompt (not Visual Studio, just ordinary Windows command line prompt)
* cd /d D:\apitrace
* `cmake -H. -Bbuild -DCMAKE_SYSTEM_VERSION=10.0 -CMAKE_PREFIX_PATH=D:\Qt\Qt5.6\5.6\msvc2015`

**Comment by OsirisDeveloper** [comment]
Many thanks, it worked! Only -DCMAKE_PREFIX_PATH is correct!!!!

**Comment by jrfonseca** [comment]
Right.  Good!
