### ISSUE TITLE
Any CMake variables to allow GL-only support on Windows?

### ISSUE THREAD

**Issue by ananthonline** [apitrace/apitrace#452]
When building on Windows, there seems to be bunch of DX dependencies and DX related issues. Are there any CMake flags that allow an OpenGL-only build of apitrace?

**Comment by jrfonseca** [comment]
No there's no CMake variable/option to enable building just GL.

It's not impossible to add such option, but I rather not: unless I continuously build with such option, odds are that it will quickly break, and I'm already keeping track of too many platforms/configurations.

But if you pass `-DWINDOWS_XP=1` then D3D10/etc won't be built, and everything should build without additional  dependencies.
