### ISSUE TITLE
Black screen when replaying DOTA2 game

### ISSUE THREAD

**Issue by yjaelex** [apitrace/apitrace#453]
Cannot play back DOTA2 game on Linux.
Trace works fine; replay results back screen.
May due to new updates of Dota2; works fine previously.

Thanks,

**Comment by jrfonseca** [comment]
Could you please provide the trace.   See https://github.com/apitrace/apitrace/blob/master/docs/BUGS.markdown#attachments

**Comment by jrfonseca** [comment]
Also, were there any `apitrace: warning: ...` when recording the trace?

**Comment by yjaelex** [comment]
Yes, there are some error msg:

**
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT|MAP_WRITE_BIT w/o MAP_FLUSH_EXPLICIT_BIT unsupported <https://git.io/vV9kM>
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT|MAP_WRITE_BIT w/o MAP_FLUSH_EXPLICIT_BIT unsupported <https://git.io/vV9kM>
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT|MAP_WRITE_BIT w/o MAP_FLUSH_EXPLICIT_BIT unsupported <https://git.io/vV9kM>
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT|MAP_WRITE_BIT w/o MAP_FLUSH_EXPLICIT_BIT unsupported <https://git.io/vV9kM>
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT|MAP_WRITE_BIT w/o MAP_FLUSH_EXPLICIT_BIT unsupported <https://git.io/vV9kM>
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT|MAP_WRITE_BIT w/o MAP_FLUSH_EXPLICIT_BIT unsupported <https://git.io/vV9kM>
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT|MAP_WRITE_BIT w/o MAP_FLUSH_EXPLICIT_BIT unsupported <https://git.io/vV9kM>
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT|MAP_WRITE_BIT w/o MAP_FLUSH_EXPLICIT_BIT unsupported <https://git.io/vV9kM>
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT|MAP_WRITE_BIT w/o MAP_FLUSH_EXPLICIT_BIT unsupported <https://git.io/vV9kM>
... ...
apitrace: warning: _gl_param_size: unknown GLenum 0x8258
apitrace: warning: _gl_param_size: unknown GLenum 0x8258
apitrace: warning: _gl_param_size: unknown GLenum 0x8258
apitrace: warning: _gl_param_size: unknown GLenum 0x8258
apitrace: warning: _gl_param_size: unknown GLenum 0x8258
apitrace: warning: _gl_param_size: unknown GLenum 0x8258
... ...
**

**Comment by yjaelex** [comment]
And the trace file:
http://jmp.sh/jZGWdtD

Thanks,

**Comment by yjaelex** [comment]
Seems to be a known issue?
Cannot support persistent map?
But it works fine with previous versions of dota2 game.

**Comment by jrfonseca** [comment]
I fixed `unknown GLenum 0x8258` warning with commit 701202aff05205b15b2fe91e43d39f70ec4b2d5d.

But I checked the `dota2.trace` you provided and the cause for black screen is indeed lack of coherent/persistent buffer mapping (issue #232), as all vertex/index geometry data is missing from the trace; no data is uploaded to any buffer whatsoever.

If DOTA2 used to work in the past, then that's because it didn't use this feature.  Or maybe your drivers didn't expose `GL_ARB_buffer_storage` extension in the past.

One potential solution would be for apitrace to mask away `GL_ARB_buffer_storage`, but it's not a generic solution as `GL_ARB_buffer_storage` is implied by OpenGL 4.4, so if I'm to spend time on this, I rather aim at the generic solution.

**Comment by yjaelex** [comment]
OK, thanks for your effort.
Persistent mapping is not easy to support, as it is hard to tell which part of memory is changed.
So looking forward to your solution!

Thanks,

**Comment by turol** [comment]
The obvious solution would be to abuse read-only pages and SIGSEGV though I suspect that would blow up if the program being traced also tried to handle signals.

**Comment by eero-t** [comment]
Many/most games use libSDL and by default that installs SIGSEGV handler to be able to restore correct resolution / graphics after crash, unless game calls SDL_Init() with additional SDL_INIT_NOPARACHUTE flag.
