### ISSUE TITLE
Add support for EGL_EXT_swap_buffers_with_damage

### ISSUE THREAD

**Issue by linkmauve** [apitrace/apitrace#454]
Currently, using eglSwapBuffersWithDamageEXT to swap its buffers won’t be handled by apitrace as a frame end, nor will this call be even recorded.

You can reproduce this issue by tracing `weston-simple-egl` on any Wayland compositor, if your libEGL exposes this extension and EGL_EXT_buffer_age.

**Comment by linkmauve** [comment]
You said untested in 8adb8b08e139ffce362cdc90d007cda3ac5d8da9, I just tested it and confirmed it’s working. :)

**Comment by jrfonseca** [comment]
Cool. Thanks for confirming.
