### ISSUE TITLE
glDeleteShader, Unable to find shader ID 0, handled as error

### ISSUE THREAD

**Issue by ktamail666** [apitrace/apitrace#455]
When we call glDeleteShader with zero then should ignore it.

From reference:
"A value of 0 for shader will be silently ignored."

**Comment by jrfonseca** [comment]
The message `Unable to find shader ID 0` is not from apitrace.  It's most certainly from your OpenGL driver.

Which OpenGL driver are you using?  You'll need to report this bug against it.
