### ISSUE TITLE
Some object black texture in CSGO replay

### ISSUE THREAD

**Issue by PhucDL** [apitrace/apitrace#457]
I have traced CSGO game and when i replay it, some texture not display correctly, it's black. When i traced, no warning or error found. 
Here is my trace file: https://drive.google.com/file/d/0Byegtv_jp0SaU3dlZkVHVm9GT1U/view?usp=sharing

**Comment by jrfonseca** [comment]
> I have traced CSGO game and when i replay it, some texture not display correctly, it's black.

I see the black textures when I replay your trace, but I haven't found any clue to why so far.

> When i traced, no warning or error found. 

Note that on Windows, one needs to use [DebugView](https://technet.microsoft.com/en-us/sysinternals/debugview.aspx) to view apitrace's warning/error messages.  If you didn't use, please retry tracing again, and search for any `apitrace: warning: ...`  messages in DebugView's window.

**Comment by jrfonseca** [comment]
I investigated this further.  and I strongly suspect that CSGO is using some vendor specific D3D9 hacks that apitrace doesn't fully support.

In particular, I suspect it might be using `NvAPI_D3D9_StretchRectEx` or `NvAPI_D3D9_AliasSurfaceAsTexture`, to get depth values into a texture.  Apitrace doesn't support these calls, so they are not recorded on the trace.  And the depth stencil texture (object `0x10f90b80` in your trace) is always zero.

See also:
* https://code.google.com/archive/p/direct-depth-access-dx9/
* http://aras-p.info/texts/D3D9GPUHacks.html

This is just a theory.  I'm not sure how to prove this.  I also don't know if there's any way to prevent CSGO from using these hacks.

**Comment by jrfonseca** [comment]
Per https://bugs.winehq.org/show_bug.cgi?id=35062#c10 potential workarounds are:
- masking PCI Vendor ID
- hiding nvapi.dll

**Comment by jrfonseca** [comment]
There's no plan to support tracing NVAPI in the foreseeable future, so closing this.
