### ISSUE TITLE
glretrace crashes on replay_memcpy

### ISSUE THREAD

**Issue by NightNord** [apitrace/apitrace#460]
Hello. I've been trying to make and replay some XCOM2 traces. I've made two and both seem too crash on replay_memcpy at various points - one after most of intro videos and the another right after a splash screen. Unlike #407 no driver is involved in the callstack

```
72708 @5 memcpy(dest = 0x7f9ee88f1200, src = blob(1248), n = 1248)
apitrace: warning: caught signal 11
72708: error: caught an unhandled exception
glretrace+0x23ce6c
/lib64/libpthread.so.0+0x10e1f
/lib64/libc.so.6+0x8eda9
glretrace+0xddf2
glretrace+0xcaac
glretrace+0xd1ef
glretrace+0xd461
/lib64/libpthread.so.0+0x7433
/lib64/libc.so.6: clone+0x6c
?
apitrace: info: taking default action for signal 11
zsh: segmentation fault  glretrace -v XCOM2_splash_crash.trace
```
(Adding -d doesn't help)

gdb:
```
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:37
#1  0x000000000040ddf3 in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>) at /usr/include/bits/string3.h:53
#2  retrace_memcpy (call=...) at /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/retrace/retrace_stdc.cpp:81
#3  0x000000000040caad in retrace::retraceCall (call=call@entry=0x7fffd40808e0) at /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/retrace/retrace_main.cpp:233
#4  0x000000000040d1f0 in retrace::RelayRunner::runLeg (call=0x7fffd40808e0, this=0xf373b0) at /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/retrace/retrace_main.cpp:386
#5  retrace::RelayRunner::runRace (this=0xf373b0) at /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/retrace/retrace_main.cpp:364
#6  retrace::RelayRunner::runnerThread (_this=0xf373b0) at /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/retrace/retrace_main.cpp:442
#7  0x000000000040d462 in os::thread::CallbackParam<void (retrace::RelayRunner*), retrace::RelayRunner*>::operator()() (this=0xe4d380) at /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/common/os_thread.hpp:438
#8  os::thread::_callback<os::thread::CallbackParam<void (retrace::RelayRunner*), retrace::RelayRunner*> >(void*) (lpParameter=0xe4d380) at /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/common/os_thread.hpp:451
#9  0x00007ffff7885434 in start_thread (arg=0x7fffe2d48700) at pthread_create.c:333
#10 0x00007ffff62b574d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

(gdb) up
#3  0x000000000040caad in retrace::retraceCall (call=call@entry=0x7fffd40808e0) at /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/retrace/retrace_main.cpp:233
233     /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/retrace/retrace_main.cpp: Нет такого файла или каталога.
(gdb) print *call
$1 = {thread_id = 5, no = 72708, sig = 0x7fffd6805ca0, args = std::vector of length 3, capacity 3 = {{value = 0x7fffd73cfdd0}, {value = 0x7fffd6f96a10}, {value = 0x7fffd7616e70}}, ret = 0x0, flags = 0, backtrace = 0x0}

#2  retrace_memcpy (call=...) at /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/retrace/retrace_stdc.cpp:81
81      /var/tmp/portage/dev-util/apitrace-7.1/work/apitrace-7.1/retrace/retrace_stdc.cpp: Нет такого файла или каталога.
(gdb) info locals
destPtr = 0x7fffe21ce200
destLen = 60928
srcPtr = 0x7fffd7847450
srcLen = 1248

(gdb) print *(float*)srcPtr
$2 = 524288

(gdb) print *(float*)destPtr
Cannot access memory at address 0x7fffe21ce200
```
This is captured from replaying "splash screen crash" trace [2]

I've tried to `apitrace trim` the traces to cutoff everything after crashing call, but it seems to remove a bit more than that, so results are unreplayable at all and are crashing at first `glBegin`.

So I've made a shorter trace (just loading to the main menu). Replaying it worked. I've made an another - it worked again. I've made a longer (just waiting around in the main menu) version and it finally crashed during the replay - same location, same reason, different numbers. But this time it makes to the mainmenu and renders it for a few seconds. Longer the trace is - faster it crashes during the replay. I guess it's depending on a size? Could make more tests if needed.
```
# For a "small" trace [3]
(gdb) info locals
destPtr = 0x7fffe21942b0
destLen = 490832
srcPtr = 0x7fffd72b2f90
srcLen = 768
n = <optimized out>
(gdb) print *(float*)0x7fffe21942b0
Cannot access memory at address 0x7fffe21942b0
```

During the trace it also writes tons of 
```
apitrace: warning: glNamedBufferStorage: MAP_NOTIFY_EXPLICIT_BIT_VMWX set w/o MAP_PERSISTENT_BIT
```
And, in the beginning:
```
apitrace: redirecting dlopen("libGL.so.1", 0x102)
apitrace: warning: unknown function "glProgramCallbackMESA"
apitrace: warning: unknown function "glGetProgramRegisterfvMESA"
apitrace: warning: unknown function "glBlendEquationSeparateATI"
apitrace: warning: unknown function "glEGLImageTargetTexture2DOES"
apitrace: warning: unknown function "glEGLImageTargetRenderbufferStorageOES"
apitrace: warning: unknown function "glMultiTexCoord1bOES"
apitrace: warning: unknown function "glMultiTexCoord1bvOES"
...
apitrace: warning: unknown function "glVertex4xOES"
apitrace: warning: unknown function "glVertex4xvOES"
```
Skipped functions are all from OES.

OS: Gentoo Linux 64bit
Version: apitrace-7.1.0 from portage
GPU: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
Drivers: OpenGL renderer string: Gallium 0.4 on AMD TAHITI (DRM 2.43.0, LLVM 3.7.1). Mesa-11.2.1

\[1\] (crash just before main menu, ~900Mb xz-compressed) https://drive.google.com/open?id=0B8bYgtw5eDBHZUphZWFoZlZlNk0
\[2\] (crash just after splash screen, ~940Mb xz-compressed) https://drive.google.com/open?id=0B8bYgtw5eDBHME05d1I3MHRtS00
\[3\] (crash a few seconds in the main menu, ~170Mb xz-compressed) https://drive.google.com/open?id=0B8bYgtw5eDBHa3cxRHFyU0RLN28

**Comment by jrfonseca** [comment]
This is probably the same as issue #450.

I need to integrate @nhaehnle's patch,

**Comment by NightNord** [comment]
I've updated the patch from #450 to the recent master and tried it and it worked. So yes, it seems to be a duplicate. But hey, at least now you have traces to test on! In case you haven't.

[apitrace-450_updated-implicit-unmap.diff.txt](https://github.com/apitrace/apitrace/files/300637/apitrace-450_updated-implicit-unmap.diff.txt)

**Comment by jrfonseca** [comment]
> I've updated the patch from #450 to the recent master and tried it and it worked. So yes, it seems to be a duplicate. 

I've pushed the fix.

> But hey, at least now you have traces to test on! In case you haven't.

Indeed, the traces were helpful.  Thanks!
