### ISSUE TITLE
.trace file

### ISSUE THREAD

**Issue by witent** [apitrace/apitrace#463]
Would anyone advise whether .trace file can be loaded or opened by OSG engine? any idea how to do it?

**Comment by jrfonseca** [comment]
No, I'm not aware of OpenSceneGraph or any other tool being able to open apitrace .trace files except apitrace itself.

In theory it's not impossible to have a tool to extract geometry and textures from .traces.  But I'm not aware of such tool, and it's not a trivial thing.

**Comment by witent** [comment]
Thank you very much, jrfonseca. Apitrace is very useful, I'd like to try to integrate it with OSG. Have you heard about Equalizer (another project in the Github)? Can replay function (in Apitrace) be integrated with Equalizer? Any advice?
When you have a chance to come to China, please let me know. I will very very happy to meet you if possible.
