### ISSUE TITLE
unable to replay trace on Android 6.0

### ISSUE THREAD

**Issue by Ding34** [apitrace/apitrace#465]
on a root Galaxy S3 with Cyanogenmod 13, based on Android 6.0
tried 2 method, none works:
1. run apitrace from shell
   /data/apitrace replay com.android.gallery3d.trace
   give error:
   error: failed to execute: eglretrace com.android.gallery3d.trace
   by printing the errno msg, seems apitrace tries to run eglretrace binary by os::execvp, but in Android build there is no elgretrace binary generated, only libretrace.so
   can you help to confirm and resolve this?
2. run EGLRetrace app
   when launch the app, logcat always show:
   libc: Fatal signal 6 (SIGABRT), code -6 in tid 21756 (b.io.eglretrace)
   and the app hang there with black screen

**Comment by jrfonseca** [comment]
I'm afraid Android is no longer supported.  See #521
