### ISSUE TITLE
Steam game:Dead Island Definitive Edition - failed to replay trace

### ISSUE THREAD

**Issue by QiaoKen** [apitrace/apitrace#466]
I can trace the game, but get errors while replaying the trace file.

95 glXSwapIntervalMESA(interval = 0) = 0
95: warning: unsupported glXSwapIntervalMESA call
4315 glXSwapIntervalMESA(interval = 0) = 0
4315: warning: unsupported glXSwapIntervalMESA call
apitrace: warning: caught signal 11
4408: error: caught an unhandled exception
apitrace: info: taking default action for signal 11**_

Here is the trace file:
[dide.zip](https://github.com/apitrace/apitrace/files/331478/dide.zip)

**Comment by jrfonseca** [comment]
How was this trace generated? It's totally broken: the blobs were converted to strings.

Did you modify this trace from the one you originally recorded (e.g., via qapitrace or something?) And how?

**Comment by QiaoKen** [comment]
I just use ./apitrace trace to generated the file, and the same command works for glxgears. Maybe it is broken while uploading.
I have generated a new trace file and shared by a net drive:
http://jmp.sh/lpHOrsj

**Comment by jrfonseca** [comment]
> I just use ./apitrace trace to generated the file, and the same command works for glxgears. 

I don't see how.   For example,  *something* is transforming for example a blob with 600000 bytes (`blob(600000)`), into a 12 byte string with `"blob(600000)"`.

There's no way that `apitrace trace` could do that.

> Maybe it is broken while uploading.

No, the second trace is just the same.  I also doubt the issue is in transmission.  I can bet that some transformation inside apitrace is downgrading blobs to strings.

**Comment by jrfonseca** [comment]
Maybe your build directory got inconsistent somehow.

Please download and build the latest source, into a  new directory and retry.

**Comment by QiaoKen** [comment]
Thanks, I'll get a latest one and retry.

**Comment by jrfonseca** [comment]
No update, so I presume the issue was fixed.
