### ISSUE TITLE
Only able to see a couple rendered thumbnails with radeonsi DRI driver

### ISSUE THREAD

**Issue by spstarr** [apitrace/apitrace#467]
Version/Package: apitrace-7.1-2.fc24.x86_64
Mesa: Git master
LLVM: trunk (3.9)

I am not seeing all the frames in an apitrace. When I run qapitrace, I only see a few rendered frames at the start of the apitrace the rest are not shown even though the apitrace will run correctly.

I tried using Unigine Heaven, Valley, a UE4 Game (ARK: Survival Evolved) and I only get a few thumbnails to show the rest don't display.

This never has worked for me right, how to debug this?

**Comment by jrfonseca** [comment]
The qapitrace thumbnail is indeed a bit awkard: it only shows thumbnails of the frames you're seeing right now.

So, if you see frames where the thumbnails are missing, just hit `Ctrl+T` again, and they should show.  Please confirm.

I agree this could be improved.  Unfortunately I barely have time for the apitrace core, let along the gui.  But if you find a way to make this more user friendly, I'll happily take the patches.

**Comment by spstarr** [comment]
That does indeed work, selecting the frame up do that point does show all thumbnails
