### ISSUE TITLE
is posible to dump 3d models from frames?

### ISSUE THREAD

**Issue by Pollito001** [apitrace/apitrace#468]
Hi i want to know is posible to dump/rip 3d models from .trace file?

**Comment by mtschoen** [comment]
Hi! I've actually given this a shot, but it was too hacky/disorganized to merit a fork. I've been thinking of revisiting this.

**Comment by jrfonseca** [comment]
No, this is not currently possible. 

I don't object patches, but it's far from a trivial endeavor.  In the old days with fixed-function graphics pipelines it was easy to extract model geometry/textures/etc.  But nowadays it's pretty hard to figure out pre-transformation geometry, so such tool would have to be customized for each graphics engine.  The best that could be done generically would be to extract the post-transformed vertices.
