### ISSUE TITLE
Error copying file "apitrace/libs/arm64-v8a/libgnustl_shared.so" to "apitrace/build/android-build/libs/arm64-v8a/".

### ISSUE THREAD

**Issue by yenWu** [apitrace/apitrace#472]
Hello,
I am trying to build apitrace on Android 5.1.1 64bit emulator and get some error message. I am confuse that I don't have such directory or file.

Here cmake commands are.
`cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=android.toolchain.cmake -DANDROID_NDK=~/android-ndk-r10c -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=android-21 -DANDROID_TOOLCHAIN_NAME=aarch64-linux-android-4.9 -DANDROID_STL=gnustl_shared -DANDROID_API_LEVEL=21 -DANDROID_SDK=~/android-sdk-linux`

`make -C build retraceAPK`
error message like that
**Error copying file "/home/ken/emulator/apitrace/libs/arm64-v8a/libgnustl_shared.so" to "/home/ken/emulator/apitrace/build/android-build/libs/arm64-v8a/".**

I have no idea about that, and I still try many different cmake commands, but  always fail at `make retraceAPK`.

**Comment by jrfonseca** [comment]
I don't use Android myself, so I can't give much assistance (you might want to try the apitrace mailing list instead.)

But it builds OK for me when I do

    cmake -H. -Bbuild/android-arm -DCMAKE_TOOLCHAIN_FILE=android.toolchain.cmake -DANDROID_API_LEVEL=9 -DANDROID_STL=gnustl_shared -DANDROID_SDK=/path/to/android-sdk-linux

**Comment by xtrawurst** [comment]
I had the same issue. Have a look into the file build.make in the copyAndroidStuff.dir folder.

There's a rule called:
retrace/CMakeFiles/copyAndroidStuff:
with some commands under it.
I solved the issue by manually creating the missing folders mentioned in these commands and putting the required files into them manually.

**Comment by xtrawurst** [comment]
Actually I discovered a FIXME part in the relevant CMakeLists.txt (in the retrace folder):

                # FIXME According to android.toolchain.cmake decumentation the
                # android libs should be putted to
                # ${LIBRARY_OUTPUT_PATH_ROOT}/libs/${ANDROID_NDK_ABI_NAME} but
                # android.toolchain.cmake sees LIBRARY_OUTPUT_PATH_ROOT as
                # CMAKE_SOURCE_DIR and this CMakeLists.txt file sees it as
                # ANDROID_BUILD_DIR ;-( so, I must use
                # ${CMAKE_SOURCE_DIR}/libs/${ANDROID_NDK_ABI_NAME} insted of
                # ${LIBRARY_OUTPUT_PATH_ROOT}/libs/${ANDROID_NDK_ABI_NAME} ...

That's probably the issue.

**Comment by jrfonseca** [comment]
I'm afraid Android is no longer supported.  See #521
