### ISSUE TITLE
[Question] glReadPixels skipped during retrace?

### ISSUE THREAD

**Issue by Ancurio** [apitrace/apitrace#475]
Hi,

I recorded a very slow frame in a game, it turns out that there are hundreds of small glReadPixels interspersed with the rest of the calls. I noticed that when I replay the trace file, the frame only takes a fraction of the time to be rendered compared to the real application.

My theory is that since glReadPixels doesn't affect any GL side state whatsoever, from a retrace point of view, any calls to it can be treated as noops without affecting the rendering at all. If apitrace does indeed drop those calls during playback, that would explain the execution time disparity.

Is this actually the case?

**Comment by jrfonseca** [comment]
Yep.  glretrace ignores glReadPixels that are not done to PBOs, as those have no side-effects.

It could (and probably should) indeed do better than that -- we could replay the glReadPixel calls, and just ignore the read pixels.

I admit any profiling without that can be quite biased indeed.

There's also lots of  `glGet*` calls, which glretrace skips, which might or not have a significant impact.

**Comment by Ancurio** [comment]
Thanks! Indeed, I often record problematic parts and replay them to judge at a glance whether a bottleneck might be caused by game-logic or rendering. However, seeing many synchronizing calls like ReadPixels set off the alarm bells anyway :)

I suppose we can close this issue as my question as been answered; I didn't really intend this to be a feature request, but if you say that it's a valid one nonetheless then we can keep it open, although I should probably change the issue title?

**Comment by jrfonseca** [comment]
It's valid, but to be honest, it's low priority compared with other issues, and it's not trivial (it will require a bunch of hand written code, because the trace file doesn't record the size of blobs required to store the read pixels), so I doubt I'll ever get around to do it given how busy I've been.

So I'll close it for now, and if anybody else asks, I'll reopen it or open a new one.
