### ISSUE TITLE
Linux-based apitrace no longer works for tracing windows apps in Wine

### ISSUE THREAD

**Issue by 10110111** [apitrace/apitrace#479]
Starting from Wine commit https://github.com/wine-mirror/wine/commit/4a1629c4117fda9eca63b6f56ea45771dc9734ac, apitrace no longer has any chance to save its trace when run like
```
apitrace trace wine prog.exe
```
The [wiki page](https://github.com/apitrace/apitrace/wiki/WINE) currently says:
> To trace the host OpenGL calls there is nothing special required besides using 32-bits Linux binaries of apitrace for tracing 32-bits Windows applications.

It should now mention that starting from wine 1.7.48, in order to use this very convenient way of tracing OpenGL calls made by Wine, one has to revert that commit (in fact, just replace `_exit` with `exit` in `NtTerminateProcess`).

**Comment by 10110111** [comment]
See also [WineHQ bug](https://bugs.winehq.org/show_bug.cgi?id=41138) for possible status updates of this problem. Maybe worth adding to the Wiki too.

**Comment by jrfonseca** [comment]
Apitrace indeed relies on receiving `DLL_PROCESS_DETACH` on its `DllMain` entrypoint to flush and close the trace.  WINE is diverging substantially from Windows if it doesn't do that anymore.  Maybe this was an unintentional side effect.

It's also possible there is some other event we could listen to to known when flush and close the trace file.

**Comment by 10110111** [comment]
No, I don't mean Windows-based apitrace version. I mean, as I said in original post, running a Linux-based version of it like
```
apitrace trace wine prog.exe
```
I.e. to trace `wine`, and only indirectly `prog.exe`.

**Comment by jrfonseca** [comment]
Oh, I see what you mean now.

I can see how WINE calling exit instead of _exit might cause problems.

If there was some Linux signal apitrace could trap to flush here, that would solve this problem.

A workaround would be to not buffer trace writes when WINE is detected.  But that would mean there would be practically no compression, and tracing performance would be awful.

**Comment by 10110111** [comment]
Yeah, the workaround doesn't seem good. Can apitrace somehow hook `_exit` and similar functions like it does for OpenGL calls?

**Comment by jrfonseca** [comment]
Good idea.  Done now.  Thanks.

**Comment by Hi-Angel** [comment]
So, should it work already, or not? With git version of `apitrace` I'm getting *(here I just loaded into game menu, and exited)*:

	$ WINEDEBUG=-all apitrace trace wine kl2.exe                        
	apitrace: loaded into /usr/bin/apitrace
	apitrace: unloaded from /usr/bin/apitrace
	ERROR: ld.so: object '/usr/bin/../$LIB/apitrace/wrappers/glxtrace.so' annot open shared object file): ignored.
	ERROR: ld.so: object '/usr/bin/../$LIB/apitrace/wrappers/glxtrace.so' annot open shared object file): ignored.
	apitrace: loaded into /usr/bin/wineserver
	apitrace: loaded into /usr/bin/wine64-preloader
	apitrace: loaded into /usr/bin/wine64-preloader
	wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
	apitrace: loaded into /usr/bin/wine64-preloader
	apitrace: loaded into /usr/bin/wine64-preloader
	apitrace: loaded into /usr/bin/wine64-preloader
	apitrace: loaded into /usr/bin/wine64-preloader
	apitrace: unloaded from /usr/bin/wineserver
	$ ls *.trace
	zsh: no matches found: *.trace

**Comment by Hi-Angel** [comment]
Oh, may be it because of that `glxtrace.so` error. I didn't see it actually before I posted — I used `WINEDEBUG=-all` just for the post, and didn't look at it…

**Comment by Hi-Angel** [comment]
Ok, 32 bit doesn't seem to work well either. I tried two games, one *(GTAⅣ)* recorded a single frame, and another one *(Kane&Lynch 2)* didn't record anything at all.

**Comment by 10110111** [comment]
@Hi-Angel
Didn't check current latest, but it works for me with GTAIV on apitrace version `7.1-275-g886e2ae` (given by `git describe --tags`) and `wine-2.2`. Here's how I run it:
```
cd "/home/ruslan/opt/Games/Grand Theft Auto IV"
WINEDEBUG=-all apitrace trace wine LaunchGTAIV.exe
apitrace replay wine-preloader.trace
```
One of the windows created by `replay` has the front buffer, which does show the in-game image (i.e. Niko inside his safe house), and the image does change (Niko runs), so there are at least multiple frames, not single only as you describe.

**Comment by Hi-Angel** [comment]
Hm… I don't know then, may be it's because here GTAⅣ didn't actually exit for pressing "quit" *(some processes keep running, and e.g. `apitrace` not being detached)*, so I have to kill it. Perhaps apitrace just didn't save in that case anything.

**Comment by 10110111** [comment]
It did quit for me, almost instantly. Try doing `wineserver -k` before running `wine` via `apitrace`. Also note what `apitrace` prints on the console. As a last resort, try using earlier version of `apitrace`, as I gave above (`git checkout myVersion` and compile etc.).

**Comment by Hi-Angel** [comment]
I found the problem: it's specific to nine state-tracker. Upon enabling OpenGL one *(e.g. CSMT)* it works.
