### ISSUE TITLE
Pythonic cheats? 

### ISSUE THREAD

**Issue by acterhd** [apitrace/apitrace#485]
Hello. Can I use apitrace with pyopengl? This is possible? 
If (not?) possible, can you give me (some) technical details?

**Comment by jrfonseca** [comment]
I never tried using apitrace with pyopengl, but it should work fine.

Follow the standard instructions on https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown and do

    apitrace trace python yourPyOpenGLScript.py args ...
