### ISSUE TITLE
Android retrace app crashes on launch in MmapAllocator

### ISSUE THREAD

**Issue by dozencrows** [apitrace/apitrace#487]
The temporary file generation call mkstemp doesn't work for Android (possibly depending on device).

Switching to the default allocator instead avoids this crash.

(Apologies for not submitting a PR with a fix, but I can't do so directly for employment reasons)

**Comment by xtrawurst** [comment]
I experience the same issue (at least I think it's the same issue). Ran ndk-stack on the crash log and attached the output.

[trace.txt](https://github.com/apitrace/apitrace/files/536216/trace.txt)

**Comment by jrfonseca** [comment]
I'm afraid Android is no longer supported.  See #521
