### ISSUE TITLE
Android retrace output over socket is cut short

### ISSUE THREAD

**Issue by dozencrows** [apitrace/apitrace#488]
This occurs when a GL state value of -1 (actually 0xffffffff unsigned, such as GL_STENCIL_VALUE_MASK) retrieved from the state gets passed to the ubjsonWriter writeInt call. This leads to a call on the outputstream `os.put((char)i)`, which for some reason kills the stream (sets badbit).

The retrace continues to run, but no further data gets sent over the socket to the desktop app.

Replacing the put call with `os.write((const char*)&i, 1)` fixes this.

**Comment by jrfonseca** [comment]
I'm afraid Android is no longer supported.  See #521
