### ISSUE TITLE
Discrepancy and ambiguity in docs (FORMAT.markdown)

### ISSUE THREAD

**Issue by bkdoormaus** [apitrace/apitrace#492]
Just two small things.

Firstly, in FORMAT.markdown, struct_sig is described as 'id count member_name\*'. This is incorrect. Per the logic in common/trace_parser.cpp, it should be 'id struct_name count member_name\*', where 'struct_name' is a string.

Secondly, the documentation about bitmask_sig and bitmask values are a bit ambiguous. I would suggest changing 'value' to 'uint', since it uses uint terminals and not an actual value expression.

The documentation seems otherwise fine. While writing a custom trace parser, I only had to check the apitrace source when I ran into problems in these two cases.

**Comment by jrfonseca** [comment]
Fixed, thanks.

I'm glad you find it useful.  I often wondered if anybody would ever write a parser from scratch for .trace files.  I know the answer now.

BTW, interesting project you have on https://github.com/bkdoormaus/Glurg .  Quite a few people asked for this.  For example #468.
