### ISSUE TITLE
Failed to find OpenGL.framework/OpenGL wrapper on OSX 10.12

### ISSUE THREAD

**Issue by usunyu** [apitrace/apitrace#496]
I follow the command from https://github.com/apitrace/apitrace/blob/master/docs/INSTALL.markdown#mac-os-x to install the apitrace, and try to trace my game with:

```
apitrace trace -v DYLD_FRAMEWORK_PATH=/Users/sun/repos/apitrace/wrappers /Applications/Minecraft.app
```

But got errors as below:

```
info: did not find /usr/local/bin/wrappers/OpenGL.framework/OpenGL
info: did not find /usr/local/bin/../lib/wrappers/OpenGL.framework/OpenGL
info: did not find /usr/local/lib/wrappers/OpenGL.framework/OpenGL
error: failed to find OpenGL.framework/OpenGL wrapper (rerun with -v option for more details)
```

Any help would be very appreciate, thanks a lot!

**Comment by jrfonseca** [comment]
The right command line should be

    apitrace trace -v /Applications/Minecraft.app

as `apitrace trace` will set `DYLD_FRAMEWORK_PATH` env var appripriately.

**Comment by usunyu** [comment]
Hi, thank you!
And I ran the command:
```
export DYLD_FRAMEWORK_PATH=/Users/sun/repos/apitrace/wrappers
apitrace trace -v /Applications/Minecraft.app
```
But still got errors:
```
info: did not find /usr/local/bin/wrappers/OpenGL.framework/OpenGL
info: did not find /usr/local/bin/../lib/wrappers/OpenGL.framework/OpenGL
info: did not find /usr/local/lib/wrappers/OpenGL.framework/OpenGL
error: failed to find OpenGL.framework/OpenGL wrapper (rerun with -v option for more details)
```

**Comment by jrfonseca** [comment]
Did you do `make install`? It's better not to.  Just run apitrace from the source directory.

**Comment by usunyu** [comment]
Thank you very much for your response!
No, I didn't do ```make install```.
Yeah, I tried ran it in source directory:
```
sun:~/repos/apitrace/build $apitrace trace -v /Applications/Minecraft.app
info: did not find /usr/local/bin/wrappers/OpenGL.framework/OpenGL
info: did not find /usr/local/bin/../lib/wrappers/OpenGL.framework/OpenGL
info: did not find /usr/local/lib/wrappers/OpenGL.framework/OpenGL
error: failed to find OpenGL.framework/OpenGL wrapper (rerun with -v option for more details)
```
Is it because I am using the OSX 10.12?

**Comment by jrfonseca** [comment]
Somethings off.  I don't see how else `/usr/local/bin` could appear in the logs, unless you `/usr/local/bin/apitrace` exists.

Please wipe off apitrace stuff from `/usr/local/...` and run `./apitrace` instead of `apitrace`

**Comment by usunyu** [comment]
Thanks, yeah, the lib not found issue gone, but seems I still cannot ran trace successfully.
```
sun:~/repos/apitrace/build $./apitrace trace -v /Applications/Minecraft.app
info: found /Users/sun/repos/apitrace/build/./wrappers/OpenGL.framework/OpenGL
DYLD_FRAMEWORK_PATH=/Users/sun/repos/apitrace/build/./wrappers:
/Applications/Minecraft.app
error: failed to execute: /Applications/Minecraft.app
```
Any idea?

**Comment by MTCoster** [comment]
I'm currently facing what appears to be an identical issue to that detailed in the final post here.  How did you resolve this @usunyu?

```
$ /usr/local/apitrace/build/apitrace trace -v --api gl MyApp
info: found /usr/local/apitrace/build/wrappers/OpenGL.framework/OpenGL
DYLD_FRAMEWORK_PATH=/usr/local/apitrace/build/wrappers
MyApp
error: failed to execute: MyApp
```
