### ISSUE TITLE
Custom frame boundary support

### ISSUE THREAD

**Issue by paulmelis** [apitrace/apitrace#499]
I'm trying to debug and profile a VR application with apitrace. This application uses OpenVR (https://github.com/ValveSoftware/openvr) to render a VR scene to an HTC Vive. The issue I'm facing is that the rendering method with OpenVR is a bit different than with a regular desktop OpenGL application: images are rendered offscreen to an FBO for each eye, which are then submitted to an OpenVR compositor object, which displays the final frame in the Vive. No swap-buffers command is ever issued and therefore qapitrace only detects a single frame, containing all the calls for the traced session.

Also, by default there is no on-screen view of what is visible in the Vive. I did add one myself that simply takes one of the rendered eye FBOs and blits them to the front-buffer, but again no swap-buffers is issued. Blitting to the back-buffer and doing swap-buffers could be a work-around to get frame boundaries, but would mean disabling wait-for-vsync as the Vive display renders at 90Hz and my desktop display at 60Hz and blocking on vsync is simply not an option.

Would it be possible to add a custom frame boundary to (q)apitrace?  Meaning, that you can specify a call that signals the end (or start) of a frame?

**Comment by amonakov** [comment]
I think it's already there: see GL_GREMEDY_frame_terminator in docs/USAGE.markdown.

**Comment by paulmelis** [comment]
But that extension only seems to be available when running under gDebugger. I don't see it anywhere in the NVidia OpenGL extension listing. Also, glewinfo reports glFrameTerminatorGREMEDY as missing.

**Comment by amonakov** [comment]
docs/USAGE.markdown explicitly addresses this concern:

> apitrace will advertise and intercept these OpenGL extensions regardless of whether the OpenGL implementation supports them or not. So all you have to do is to use these extensions when available, and you can be sure they will be available when tracing inside apitrace.

**Comment by jrfonseca** [comment]
Yep, as @amonakov  said, the solution is to use glFrameTerminatorGREMEDY.  It will be advertised when running inside apitrace.
