### ISSUE TITLE
trace java app fail in android

### ISSUE THREAD

**Issue by yanbo1986** [apitrace/apitrace#502]
Hello,
I try to debug apitrace in android java app.
Refer to Android.markdown, I do the following steps:
 $ setprop wrap.com.android.settings LD_PRELOAD="/data/local/tmp/libgnustl_shared.so:/data/local/tmp/egltrace.so"
 $ setprop debug.apitrace.procname com.android.settings
 $ am start -S com.android.settings/com.android.settings.Settings
After above steps, the android will restart the zygote, and keep in bootanimation, it will not stop unless I reboot the android.
I make sure I have pushed the "libgnustl_shared.so" and "egltrace.so" to the data/local/tmp/ directory. and the version is arm64-v8a and them are consistent with android system.
The error log is as follow:

--------- beginning of system
01-16 06:22:36.524 980 3491 I ActivityManager: Force stopping com.android.settings appid=1000 user=0: from pid 11168
01-16 06:22:36.531 3117 3117 D CarrierSvcBindHelper: No carrier app for: 0
01-16 06:22:36.553 3729 3729 D RegisteredNfcFServicesCache: Service unchanged, not updating
01-16 06:22:36.778 980 2963 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.android.settings/.Settings} from uid 0 on display 0
01-16 06:22:36.797 11168 11168 D AndroidRuntime: Shutting down VM
01-16 06:22:36.812 589 589 E Zygote : Unsupported st_mode 4480
01-16 06:22:36.813 589 589 E Zygote : Unsupported st_mode 4480
01-16 06:22:36.813 589 589 F art : art/runtime/jni_internal.cc:492] JNI FatalError called: frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:484: Unable to restat file descriptor table.
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] Runtime aborting...
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] Aborting thread:
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] "main" prio=5 tid=1 Native
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] | group="" sCount=0 dsCount=0 obj=0x7579adb0 self=0x741b295a00
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] | sysTid=589 nice=0 cgrp=default sched=0/0 handle=0x741f1d5a98
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] | state=R schedstat=( 2917903863 737189732 3983 ) utm=166 stm=125 core=2 HZ=100
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] | stack=0x7fc6af5000-0x7fc6af7000 stackSize=8MB
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] | held mutexes= "abort lock"
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #00 pc 000000000047e090 /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+220)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #1 pc 000000000047e08c /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+216)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #02 pc 00000000004521f8 /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+480)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #03 pc 0000000000440170 /system/lib64/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+56)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #04 pc 000000000043ffec /system/lib64/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+668)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #05 pc 0000000000433998 /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+148)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #06 pc 00000000000e5a7c /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+1592)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #07 pc 000000000032b4b0 /system/lib64/libart.so (_ZN3art3JNI10FatalErrorEP7_JNIEnvPKc+152)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #08 pc 0000000000151648 /system/lib64/libandroid_runtime.so (???)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #09 pc 00000000001527a4 /system/lib64/libandroid_runtime.so (???)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #10 pc 000000000015375c /system/lib64/libandroid_runtime.so (???)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #11 pc 0000000000f64188 /system/framework/arm64/boot-framework.oat (???)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native method)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:95)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] at com.android.internal.os.ZygoteConnection.runOnce(ZygoteConnection.java:225)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] at com.android.internal.os.ZygoteInit.runSelectLoop(ZygoteInit.java:850)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] Dumping all threads without appropriate locks held: thread list lock mutator lock
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] All threads:
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] DALVIK THREADS (1):
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] "main" prio=5 tid=1 Runnable
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] | group="" sCount=0 dsCount=0 obj=0x7579adb0 self=0x741b295a00
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] | sysTid=589 nice=0 cgrp=default sched=0/0 handle=0x741f1d5a98
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] | state=R schedstat=( 2948966727 740292491 4003 ) utm=167 stm=126 core=2 HZ=100
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] | stack=0x7fc6af5000-0x7fc6af7000 stackSize=8MB
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] | held mutexes= "abort lock" "mutator lock"(shared held)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #00 pc 000000000047e090 /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+220)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #1 pc 000000000047e08c /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+216)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #02 pc 00000000004521f8 /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+480)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #03 pc 0000000000469d7c /system/lib64/libart.so (_ZN3art14DumpCheckpoint3RunEPNS_6ThreadE+832)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #04 pc 0000000000461f64 /system/lib64/libart.so (_ZN3art10ThreadList13RunCheckpointEPNS_7ClosureE+476)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #05 pc 0000000000461b54 /system/lib64/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEb+848)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #06 pc 000000000043ffa0 /system/lib64/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+592)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #07 pc 0000000000433998 /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+148)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #08 pc 00000000000e5a7c /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+1592)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #09 pc 000000000032b4b0 /system/lib64/libart.so (_ZN3art3JNI10FatalErrorEP7_JNIEnvPKc+152)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #10 pc 0000000000151648 /system/lib64/libandroid_runtime.so (???)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #11 pc 00000000001527a4 /system/lib64/libandroid_runtime.so (???)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #12 pc 000000000015375c /system/lib64/libandroid_runtime.so (???)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] native: #13 pc 0000000000f64188 /system/framework/arm64/boot-framework.oat (Java_com_android_internal_os_Zygote_nativeForkAndSpecialize__II_3II_3_3IILjava_lang_String_2Ljava_lang_String_2_3ILjava_lang_String_2Ljava_lang_String_2+356)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native method)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:95)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] at com.android.internal.os.ZygoteConnection.runOnce(ZygoteConnection.java:225)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] at com.android.internal.os.ZygoteInit.runSelectLoop(ZygoteInit.java:850)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422] at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422]
01-16 06:22:36.902 589 589 F art : art/runtime/runtime.cc:422]
--------- beginning of crash
01-16 06:22:36.902 589 589 F libc : Fatal signal 6 (SIGABRT), code -6 in tid 589 (main)
01-16 06:22:36.905 355 355 W : debuggerd: handling request: pid=589 uid=0 gid=0 tid=589
01-16 06:22:36.973 11177 11177 F DEBUG : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-16 06:22:36.973 11177 11177 F DEBUG : Build fingerprint: 'google/angler/angler:7.1.1/N4F26J/3549317:user/release-keys'
01-16 06:22:36.973 11177 11177 F DEBUG : Revision: '0'
01-16 06:22:36.973 11177 11177 F DEBUG : ABI: 'arm64'
01-16 06:22:36.973 11177 11177 F DEBUG : pid: 589, tid: 589, name: main >>> zygote64 <<<
01-16 06:22:36.973 11177 11177 F DEBUG : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-16 06:22:36.978 11177 11177 F DEBUG : Abort message: 'art/runtime/jni_internal.cc:492] JNI FatalError called: frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:484: Unable to restat file descriptor table.'
01-16 06:22:36.978 11177 11177 F DEBUG : x0 0000000000000000 x1 000000000000024d x2 0000000000000006 x3 0000000000000008
01-16 06:22:36.978 11177 11177 F DEBUG : x4 00000000000000e9 x5 0000800000000000 x6 000000741f121000 x7 0000000000000000
01-16 06:22:36.978 11177 11177 F DEBUG : x8 0000000000000083 x9 ffffffffffffffdf x10 0000000000000000 x11 0000000000000001
01-16 06:22:36.978 11177 11177 F DEBUG : x12 0000000000000018 x13 0000000000000000 x14 0000000000000000 x15 0035cbb7e7a625ab
01-16 06:22:36.978 11177 11177 F DEBUG : x16 000000741ce20ee0 x17 000000741cdcaaac x18 0000000000000000 x19 000000741f1d5b40
01-16 06:22:36.978 11177 11177 F DEBUG : x20 0000000000000006 x21 000000741f1d5a98 x22 0000000000000000 x23 000000741b1fe000
01-16 06:22:36.978 11177 11177 F DEBUG : x24 000000740e62f100 x25 0000000000000000 x26 0000007fc72f0281 x27 00000000000001e4
01-16 06:22:36.978 11177 11177 F DEBUG : x28 0000007fc72f05c8 x29 0000007fc72f0160 x30 000000741cdc7ed8
01-16 06:22:36.978 11177 11177 F DEBUG : sp 0000007fc72f0140 pc 000000741cdcaab4 pstate 0000000060000000
01-16 06:22:37.464 11177 11177 F DEBUG :
01-16 06:22:37.464 11177 11177 F DEBUG : backtrace:
01-16 06:22:37.464 11177 11177 F DEBUG : #00 pc 000000000006bab4 /system/lib64/libc.so (tgkill+8)
01-16 06:22:37.464 11177 11177 F DEBUG : #1 pc 0000000000068ed4 /system/lib64/libc.so (pthread_kill+64)
01-16 06:22:37.464 11177 11177 F DEBUG : #02 pc 0000000000023f58 /system/lib64/libc.so (raise+24)
01-16 06:22:37.464 11177 11177 F DEBUG : #03 pc 000000000001c810 /system/lib64/libc.so (abort+52)
01-16 06:22:37.464 11177 11177 F DEBUG : #04 pc 0000000000433ad4 /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+464)
01-16 06:22:37.464 11177 11177 F DEBUG : #05 pc 00000000000e5a7c /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+1592)
01-16 06:22:37.464 11177 11177 F DEBUG : #06 pc 000000000032b4b0 /system/lib64/libart.so (_ZN3art3JNI10FatalErrorEP7_JNIEnvPKc+152)
01-16 06:22:37.464 11177 11177 F DEBUG : #07 pc 0000000000151648 /system/lib64/libandroid_runtime.so
01-16 06:22:37.464 11177 11177 F DEBUG : #08 pc 00000000001527a4 /system/lib64/libandroid_runtime.so
01-16 06:22:37.464 11177 11177 F DEBUG : #09 pc 000000000015375c /system/lib64/libandroid_runtime.so
01-16 06:22:37.464 11177 11177 F DEBUG : #10 pc 00000000025ea188 /system/framework/arm64/boot-framework.oat (offset 0x1686000) (com.android.internal.os.Zygote.nativeForkAndSpecialize+356)
01-16 06:22:37.464 11177 11177 F DEBUG : #11 pc 00000000025e9df4 /system/framework/arm64/boot-framework.oat (offset 0x1686000) (com.android.internal.os.Zygote.forkAndSpecialize+176)
01-16 06:22:37.464 11177 11177 F DEBUG : #12 pc 00000000025edd18 /system/framework/arm64/boot-framework.oat (offset 0x1686000) (com.android.internal.os.ZygoteConnection.runOnce+1428)
01-16 06:22:37.464 11177 11177 F DEBUG : #13 pc 00000000025f2478 /system/framework/arm64/boot-framework.oat (offset 0x1686000) (com.android.internal.os.ZygoteInit.runSelectLoop+804)
01-16 06:22:37.465 11177 11177 F DEBUG : #14 pc 00000000025ef50c /system/framework/arm64/boot-framework.oat (offset 0x1686000) (com.android.internal.os.ZygoteInit.main+1304)
01-16 06:22:37.465 11177 11177 F DEBUG : #15 pc 00000000000d29e8 /system/lib64/libart.so (art_quick_invoke_static_stub+600)
01-16 06:22:37.465 11177 11177 F DEBUG : #16 pc 00000000000df430 /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+256)
01-16 06:22:37.465 11177 11177 F DEBUG : #17 pc 000000000042d334 /system/lib64/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+108)
01-16 06:22:37.465 11177 11177 F DEBUG : #18 pc 000000000042cf8c /system/lib64/libart.so (_ZN3art17InvokeWithVarArgsERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDSt9__va_list+380)
01-16 06:22:37.465 11177 11177 F DEBUG : #19 pc 0000000000346fec /system/lib64/libart.so (_ZN3art3JNI21CallStaticVoidMethodVEP7_JNIEnvP7_jclassP10_jmethodIDSt9__va_list+600)
01-16 06:22:37.465 11177 11177 F DEBUG : #20 pc 000000000009f088 /system/lib64/libandroid_runtime.so
01-16 06:22:37.465 11177 11177 F DEBUG : #21 pc 00000000000a16c4 /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+708)
01-16 06:22:37.465 11177 11177 F DEBUG : #22 pc 000000000000225c /system/bin/app_process64
01-16 06:22:37.465 11177 11177 F DEBUG : #23 pc 000000000001a594 /system/lib64/libc.so (__libc_init+88)
01-16 06:22:37.465 11177 11177 F DEBUG : #24 pc 0000000000001cc8 /system/bin/app_process64
01-16 06:22:37.601 980 2960 W NativeCrashListener: Couldn't find ProcessRecord for pid 589
01-16 06:22:37.601 11177 11177 E : AM data write failed: Broken pipe
01-16 06:22:37.616 355 355 W : debuggerd: resuming target 589
01-16 06:22:37.622 980 997 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
01-16 06:22:37.640 980 990 E Process : Starting VM process through Zygote failed
01-16 06:22:37.642 980 990 E ActivityManager: Failure starting process com.android.settings
01-16 06:22:37.642 980 990 E ActivityManager: java.lang.RuntimeException: Starting VM process through Zygote failed
01-16 06:22:37.642 980 990 E ActivityManager: at android.os.Process.start(Process.java:527)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3797)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3654)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3535)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:1419)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2577)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2127)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1829)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityStack.completePauseLocked(ActivityStack.java:1332)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityStack.activityPausedLocked(ActivityStack.java:1212)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityManagerService.activityPaused(ActivityManagerService.java:6918)
01-16 06:22:37.642 980 990 E ActivityManager: at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:571)
01-16 06:22:37.642 980 990 E ActivityManager: at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2794)
01-16 06:22:37.642 980 990 E ActivityManager: at android.os.Binder.execTransact(Binder.java:565)
01-16 06:22:37.642 980 990 E ActivityManager: Caused by: android.os.ZygoteStartFailedEx: java.io.EOFException
01-16 06:22:37.642 980 990 E ActivityManager: at android.os.Process.zygoteSendArgsAndGetResult(Process.java:618)
01-16 06:22:37.642 980 990 E ActivityManager: at android.os.Process.startViaZygote(Process.java:737)
01-16 06:22:37.642 980 990 E ActivityManager: at android.os.Process.start(Process.java:521)
01-16 06:22:37.642 980 990 E ActivityManager: ... 13 more
01-16 06:22:37.642 980 990 E ActivityManager: Caused by: java.io.EOFException
01-16 06:22:37.642 980 990 E ActivityManager: at java.io.DataInputStream.readFully(DataInputStream.java:200)
01-16 06:22:37.642 980 990 E ActivityManager: at java.io.DataInputStream.readInt(DataInputStream.java:389)
01-16 06:22:37.642 980 990 E ActivityManager: at android.os.Process.zygoteSendArgsAndGetResult(Process.java:609)
01-16 06:22:37.642 980 990 E ActivityManager: ... 15 more
01-16 06:22:37.642 980 990 I ActivityManager: Force stopping com.android.settings appid=1000 user=0: start failure
01-16 06:22:37.644 980 990 I ActivityManager: Force finishing activity ActivityRecord{69a6b34 u0 com.android.settings/.Settings t22}
01-16 06:22:37.657 401 401 I ServiceManager: service 'media.player' died
01-16 06:22:37.657 401 401 I ServiceManager: service 'media.resource_manager' died
01-16 06:22:37.660 401 401 I ServiceManager: service 'media.camera' died
01-16 06:22:37.660 401 401 I ServiceManager: service 'netd' died
01-16 06:22:37.673 596 3007 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...

**Comment by nioncode** [comment]
I'm having the same issue on Android 6.0.1 (LineageOS 13). LD_PRELOAD seems to be broken somehow.

**Comment by sg1993** [comment]
https://issuetracker.google.com/issues/62179655
Reported on open AOSP forum as well.

**Comment by jrfonseca** [comment]
I'm afraid Android is no longer supported.  See #521
