### ISSUE TITLE
Can't trace an application that needs to load libs via LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by jfirebaugh** [apitrace/apitrace#504]
I have an EGL + GLES application that depends on loading libGLESv2.so via LD_LIBRARY_PATH (libGLESv2.so is not installed to ld default search paths). It seems that apitrace wipes out the value of LD_LIBRARY_PATH, and the application then fails to load libGLESv2.so. Here's the output from `LD_DEBUG=libs apitrace trace --api egl <app>`:

<details>
<pre>
      1951:	find library=libz.so.1 [0]; searching
      1951:	 search path=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/tls/x86_64:/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/tls:/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/x86_64:/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib		(LD_LIBRARY_PATH)
      1951:	  trying file=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/tls/x86_64/libz.so.1
      1951:	  trying file=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/tls/libz.so.1
      1951:	  trying file=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/x86_64/libz.so.1
      1951:	  trying file=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/libz.so.1
      1951:	 search cache=/etc/ld.so.cache
      1951:	  trying file=/lib/x86_64-linux-gnu/libz.so.1
      1951:	
      1951:	find library=libsnappy.so.1 [0]; searching
      1951:	 search path=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib		(LD_LIBRARY_PATH)
      1951:	  trying file=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/libsnappy.so.1
      1951:	 search cache=/etc/ld.so.cache
      1951:	  trying file=/usr/lib/libsnappy.so.1
      1951:	
      1951:	find library=libstdc++.so.6 [0]; searching
      1951:	 search path=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib		(LD_LIBRARY_PATH)
      1951:	  trying file=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/libstdc++.so.6
      1951:	 search cache=/etc/ld.so.cache
      1951:	  trying file=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
      1951:	
      1951:	find library=libgcc_s.so.1 [0]; searching
      1951:	 search path=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib		(LD_LIBRARY_PATH)
      1951:	  trying file=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/libgcc_s.so.1
      1951:	 search cache=/etc/ld.so.cache
      1951:	  trying file=/lib/x86_64-linux-gnu/libgcc_s.so.1
      1951:	
      1951:	find library=libc.so.6 [0]; searching
      1951:	 search path=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib		(LD_LIBRARY_PATH)
      1951:	  trying file=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/libc.so.6
      1951:	 search cache=/etc/ld.so.cache
      1951:	  trying file=/lib/x86_64-linux-gnu/libc.so.6
      1951:	
      1951:	find library=libm.so.6 [0]; searching
      1951:	 search path=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib		(LD_LIBRARY_PATH)
      1951:	  trying file=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib/libm.so.6
      1951:	 search cache=/etc/ld.so.cache
      1951:	  trying file=/lib/x86_64-linux-gnu/libm.so.6
      1951:	
      1951:	
      1951:	calling init: /lib/x86_64-linux-gnu/libc.so.6
      1951:	
      1951:	
      1951:	calling init: /lib/x86_64-linux-gnu/libm.so.6
      1951:	
      1951:	
      1951:	calling init: /lib/x86_64-linux-gnu/libgcc_s.so.1
      1951:	
      1951:	
      1951:	calling init: /usr/lib/x86_64-linux-gnu/libstdc++.so.6
      1951:	
      1951:	
      1951:	calling init: /usr/lib/libsnappy.so.1
      1951:	
      1951:	
      1951:	calling init: /lib/x86_64-linux-gnu/libz.so.1
      1951:	
      1951:	
      1951:	initialize program: apitrace
      1951:	
      1951:	
      1951:	transferring control: apitrace
      1951:	
      1952:	find library=egltrace.so [0]; searching
      1952:	 search path=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/tls/x86_64:/usr/lib/x86_64-linux-gnu/apitrace/wrappers/tls:/usr/lib/x86_64-linux-gnu/apitrace/wrappers/x86_64:/usr/lib/x86_64-linux-gnu/apitrace/wrappers		(LD_LIBRARY_PATH)
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/tls/x86_64/egltrace.so
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/tls/egltrace.so
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/x86_64/egltrace.so
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/egltrace.so
      1952:	
      1952:	find library=libdl.so.2 [0]; searching
      1952:	 search path=/usr/lib/x86_64-linux-gnu/apitrace/wrappers		(LD_LIBRARY_PATH)
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/libdl.so.2
      1952:	 search cache=/etc/ld.so.cache
      1952:	  trying file=/lib/x86_64-linux-gnu/libdl.so.2
      1952:	
      1952:	find library=librt.so.1 [0]; searching
      1952:	 search path=/usr/lib/x86_64-linux-gnu/apitrace/wrappers		(LD_LIBRARY_PATH)
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/librt.so.1
      1952:	 search cache=/etc/ld.so.cache
      1952:	  trying file=/lib/x86_64-linux-gnu/librt.so.1
      1952:	
      1952:	find library=libstdc++.so.6 [0]; searching
      1952:	 search path=/usr/lib/x86_64-linux-gnu/apitrace/wrappers		(LD_LIBRARY_PATH)
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/libstdc++.so.6
      1952:	 search cache=/etc/ld.so.cache
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
      1952:	
      1952:	find library=libm.so.6 [0]; searching
      1952:	 search path=/usr/lib/x86_64-linux-gnu/apitrace/wrappers		(LD_LIBRARY_PATH)
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/libm.so.6
      1952:	 search cache=/etc/ld.so.cache
      1952:	  trying file=/lib/x86_64-linux-gnu/libm.so.6
      1952:	
      1952:	find library=libgcc_s.so.1 [0]; searching
      1952:	 search path=/usr/lib/x86_64-linux-gnu/apitrace/wrappers		(LD_LIBRARY_PATH)
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/libgcc_s.so.1
      1952:	 search cache=/etc/ld.so.cache
      1952:	  trying file=/lib/x86_64-linux-gnu/libgcc_s.so.1
      1952:	
      1952:	find library=libpthread.so.0 [0]; searching
      1952:	 search path=/usr/lib/x86_64-linux-gnu/apitrace/wrappers		(LD_LIBRARY_PATH)
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/libpthread.so.0
      1952:	 search cache=/etc/ld.so.cache
      1952:	  trying file=/lib/x86_64-linux-gnu/libpthread.so.0
      1952:	
      1952:	find library=libc.so.6 [0]; searching
      1952:	 search path=/usr/lib/x86_64-linux-gnu/apitrace/wrappers		(LD_LIBRARY_PATH)
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/libc.so.6
      1952:	 search cache=/etc/ld.so.cache
      1952:	  trying file=/lib/x86_64-linux-gnu/libc.so.6
      1952:	
      1952:	
      1952:	calling init: /lib/x86_64-linux-gnu/libpthread.so.0
      1952:	
      1952:	
      1952:	calling init: /lib/x86_64-linux-gnu/libc.so.6
      1952:	
      1952:	
      1952:	calling init: /lib/x86_64-linux-gnu/libgcc_s.so.1
      1952:	
      1952:	
      1952:	calling init: /lib/x86_64-linux-gnu/libm.so.6
      1952:	
      1952:	
      1952:	calling init: /usr/lib/x86_64-linux-gnu/libstdc++.so.6
      1952:	
      1952:	
      1952:	calling init: /lib/x86_64-linux-gnu/librt.so.1
      1952:	
      1952:	
      1952:	calling init: /lib/x86_64-linux-gnu/libdl.so.2
      1952:	
      1952:	
      1952:	calling init: /usr/lib/x86_64-linux-gnu/apitrace/wrappers/egltrace.so
      1952:	
      1952:	
      1952:	initialize program: node
      1952:	
      1952:	
      1952:	transferring control: node
      1952:	
      1952:	find library=libGLESv2.so.2 [0]; searching
      1952:	 search path=/usr/lib/x86_64-linux-gnu/apitrace/wrappers		(LD_LIBRARY_PATH)
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/apitrace/wrappers/libGLESv2.so.2
      1952:	 search cache=/etc/ld.so.cache
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/mesa-egl/libGLESv2.so.2
      1952:	 search path=/lib/x86_64-linux-gnu/tls/x86_64:/lib/x86_64-linux-gnu/tls:/lib/x86_64-linux-gnu/x86_64:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls/x86_64:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu/x86_64:/usr/lib/x86_64-linux-gnu:/lib/tls/x86_64:/lib/tls:/lib/x86_64:/lib:/usr/lib/tls/x86_64:/usr/lib/tls:/usr/lib/x86_64:/usr/lib		(system search path)
      1952:	  trying file=/lib/x86_64-linux-gnu/tls/x86_64/libGLESv2.so.2
      1952:	  trying file=/lib/x86_64-linux-gnu/tls/libGLESv2.so.2
      1952:	  trying file=/lib/x86_64-linux-gnu/x86_64/libGLESv2.so.2
      1952:	  trying file=/lib/x86_64-linux-gnu/libGLESv2.so.2
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/tls/x86_64/libGLESv2.so.2
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/tls/libGLESv2.so.2
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/x86_64/libGLESv2.so.2
      1952:	  trying file=/usr/lib/x86_64-linux-gnu/libGLESv2.so.2
      1952:	  trying file=/lib/tls/x86_64/libGLESv2.so.2
      1952:	  trying file=/lib/tls/libGLESv2.so.2
      1952:	  trying file=/lib/x86_64/libGLESv2.so.2
      1952:	  trying file=/lib/libGLESv2.so.2
      1952:	  trying file=/usr/lib/tls/x86_64/libGLESv2.so.2
      1952:	  trying file=/usr/lib/tls/libGLESv2.so.2
      1952:	  trying file=/usr/lib/x86_64/libGLESv2.so.2
      1952:	  trying file=/usr/lib/libGLESv2.so.2
      1952:	
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libGLESv2.so.2: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/john/mapbox-gl-native/platform/node/index.js:5:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
      1952:	
      1952:	calling fini: node [0]
      1952:	
      1952:	
      1952:	calling fini: /usr/lib/x86_64-linux-gnu/apitrace/wrappers/egltrace.so [0]
      1952:	
      1952:	
      1952:	calling fini: /lib/x86_64-linux-gnu/libdl.so.2 [0]
      1952:	
      1952:	
      1952:	calling fini: /lib/x86_64-linux-gnu/librt.so.1 [0]
      1952:	
      1952:	
      1952:	calling fini: /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
      1952:	
      1952:	
      1952:	calling fini: /lib/x86_64-linux-gnu/libm.so.6 [0]
      1952:	
      1952:	
      1952:	calling fini: /lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
      1952:	
      1952:	
      1952:	calling fini: /lib/x86_64-linux-gnu/libpthread.so.0 [0]
      1952:	
      1951:	
      1951:	calling fini: apitrace [0]
      1951:	
      1951:	
      1951:	calling fini: /lib/x86_64-linux-gnu/libz.so.1 [0]
      1951:	
      1951:	
      1951:	calling fini: /usr/lib/libsnappy.so.1 [0]
      1951:	
      1951:	
      1951:	calling fini: /usr/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
      1951:	
      1951:	
      1951:	calling fini: /lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
      1951:	
      1951:	
      1951:	calling fini: /lib/x86_64-linux-gnu/libm.so.6 [0]
      1951:	
</pre>
</details>

libGLESv2.so.2 is in `/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib`. Is there anything I can do to ensure that this directory remains on the ld search path?

**Comment by amonakov** [comment]
I don't see apitrace (re)setting LD_LIBRARY_PATH anywhere. What's your apitrace version, and how did you install it?

**Comment by jrfonseca** [comment]
Like @amonakov said, apitrace does not override `LD_LIBRARY_PATH`.

It does however override `dlopen`.

Could you try with latest apitrace from master branch? Because master includes additional logging in the form of `apitrace: redirecting/ignoring dlopen(...)` which I don't see in your logs.

**Comment by jfirebaugh** [comment]
I'm using the [default package for Ubuntu trusty](http://packages.ubuntu.com/trusty/apitrace-gl-frontend). Package version is listed as `3.0+git20121018.d1c301f7-0ubuntu1`. Is there a command line flag to print the version? `apitrace --version` didn't work.

I said "wipes out the value" based on the `LD_DEBUG=libs` output, which showed the necessary `LD_LIBRARY_PATH` before loading `egltrace.so`:

```
1951:	 search path=/home/john/mapbox-gl-native/mason_packages/linux-x86_64/mesa/13.0.3/lib		(LD_LIBRARY_PATH)
```

But not afterward:

```
1952:	 search path=/usr/lib/x86_64-linux-gnu/apitrace/wrappers		(LD_LIBRARY_PATH)
```

But I'll freely admit I don't have knowledge of how this is intended to work. I'll try the latest from master today and report back.

**Comment by jfirebaugh** [comment]
Latest master works great. 😄 Sorry for the noise.
