### ISSUE TITLE
OSX deployment target mismatch with required SDK version (?)

### ISSUE THREAD

**Issue by kavika13** [apitrace/apitrace#505]
This line ([/CMakeLists.txt](https://github.com/apitrace/apitrace/blob/master/CMakeLists.txt#L13) - line 13):

    set (CMAKE_OSX_DEPLOYMENT_TARGET "10.11" CACHE STRING "Minimum OS X version to target for deployment" FORCE)

... seems to conflict with these lines ([/CMakeLists.txt](https://github.com/apitrace/apitrace/blob/master/CMakeLists.txt#L318) - line 318):

    check_cxx_source_compiles ("#include <AvailabilityMacros.h>\n#if MAC_OS_X_VERSION_MAX_ALLOWED >= 101200\nint main() { return 0; }\n#endif" HAVE_MACOSX_10_12_SDK)
    if (NOT HAVE_MACOSX_10_12_SDK)
        message (FATAL_ERROR "macOS 10.12 SDK or newer (i.e. Xcode 8.0 or newer) required")
    endif ()

This is causing me to get the `macOS 10.12 SDK or newer` error message when trying to use cmake on 10.12, with the 10.12 SDK installed (and the 10.11 SDK installed). When I switch line 13 to `10.12`, cmake succeeds.

I'm not terribly familiar with build versions and OSX. Can you even install 10.12 on top of a 10.11 OS? Can you even target 10.11 using a 10.12 SDK? If not, then it seems like these versions should match.

**Comment by jrfonseca** [comment]
Weird.  I'm not terribly familiar neither, but my understanding is that:
* `CMAKE_OSX_DEPLOYMENT_TARGET` specifies the minimum OSX version (not maximum.)
* if one uses Xcode 8.x one should get a macOS 10.12 SDK.  What Xcode version do you have?

Anyway, I think if I remove `CMAKE_OSX_DEPLOYMENT_TARGET` then it will default to the macOS used to build which should work. I'll do that.

**Comment by kavika13** [comment]
> if one uses Xcode 8.x one should get a macOS 10.12 SDK. What Xcode version do you have?

8.2.1.

The problem is that the variable is used to determine the SDK to point at.

https://cmake.org/cmake/help/v3.0/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

> CMake uses this value for the -mmacosx-version-min flag and to help choose the default SDK (see CMAKE_OSX_SYSROOT).

I am not sure if a build can force a 10.12 SDK and usefully target an older platform version. So the fix you made might be the right one, if there's absolutely no way < 10.12 can be used with the current state of apitrace.

**Comment by jrfonseca** [comment]
> So the fix you made might be the right one, if there's absolutely no way an SDK version < 10.12 can be used with the current state of apitrace.

Yes. It wouldn't be impossible to make apitrace build with older SDK by adding missing defines etc, but it would always be brittle, so I rather not support it.

**Comment by follower** [comment]
FWIW I was able to build `apitrace` (at 711b198a0ff2b60e52808003de395bc1b6e9da4d) for Mac OS X 10.9.5 with the following changes:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 206e13f..b8b9903 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -330,12 +330,12 @@ else ()
     add_compiler_flags (-fmessage-length=0)
 endif ()
 
-if (APPLE)
-    check_cxx_source_compiles ("#include <AvailabilityMacros.h>\n#if MAC_OS_X_VERSION_MAX_ALLOWED >= 101200\nint main() { return 0; }\n#endif" HAVE_MACOSX_10_12_SDK)
-    if (NOT HAVE_MACOSX_10_12_SDK)
-        message (FATAL_ERROR "macOS 10.12 SDK or newer (i.e. Xcode 8.0 or newer) required")
-    endif ()
-endif ()
+#if (APPLE)
+#    check_cxx_source_compiles ("#include <AvailabilityMacros.h>\n#if MAC_OS_X_VERSION_MAX_ALLOWED >= 101200\nint main() { return 0; }\n#endif" HAVE_MACOSX_10_12_SDK)
+#    if (NOT HAVE_MACOSX_10_12_SDK)
+#        message (FATAL_ERROR "macOS 10.12 SDK or newer (i.e. Xcode 8.0 or newer) required")
+#    endif ()
+#endif ()
 
 if (MINGW)
     # Avoid depending on MinGW runtime DLLs
diff --git a/retrace/glws_cocoa.mm b/retrace/glws_cocoa.mm
index 813682b..e1ff06d 100644
--- a/retrace/glws_cocoa.mm
+++ b/retrace/glws_cocoa.mm
@@ -51,6 +51,39 @@
 #include "glws.hpp"
 
 
+
+// Deprecated constants in 10.12 SDK
+# define NSAlertStyleCritical NSCriticalAlertStyle
+# define NSAlertStyleInformational NSInformationalAlertStyle
+# define NSAlertStyleWarning NSWarningAlertStyle
+# define NSCompositingOperationSourceOver NSCompositeSourceOver
+# define NSControlSizeRegular NSRegularControlSize
+# define NSEventModifierFlagCapsLock NSAlphaShiftKeyMask
+# define NSEventModifierFlagCommand NSCommandKeyMask
+# define NSEventModifierFlagControl NSControlKeyMask
+# define NSEventModifierFlagDeviceIndependentFlagsMask NSDeviceIndependentModifierFlagsMask
+# define NSEventModifierFlagHelp NSHelpKeyMask
+# define NSEventModifierFlagNumericPad NSNumericPadKeyMask
+# define NSEventModifierFlagOption NSAlternateKeyMask
+# define NSEventModifierFlagShift NSShiftKeyMask
+# define NSEventTypeApplicationDefined NSApplicationDefined
+# define NSEventTypeKeyDown NSKeyDown
+# define NSEventTypeKeyUp NSKeyUp
+# define NSEventTypeLeftMouseUp NSLeftMouseUp
+# define NSEventTypeMouseEntered NSMouseEntered
+# define NSEventTypeMouseExited NSMouseExited
+# define NSEventTypeRightMouseDown NSRightMouseDown
+# define NSWindowStyleMaskBorderless NSBorderlessWindowMask
+# define NSWindowStyleMaskClosable NSClosableWindowMask
+# define NSWindowStyleMaskFullScreen NSFullScreenWindowMask
+# define NSWindowStyleMaskMiniaturizable NSMiniaturizableWindowMask
+# define NSWindowStyleMaskResizable NSResizableWindowMask
+# define NSWindowStyleMaskTexturedBackground NSTexturedBackgroundWindowMask
+# define NSWindowStyleMaskTitled NSTitledWindowMask
+# define NSWindowStyleMaskUnifiedTitleAndToolbar NSUnifiedTitleAndToolbarWindowMask
+
+# define NSEventMaskAny NSAnyEventMask 
+
 /**
  * Dummy thread to force Cocoa to enter multithreading mode.
  *
```

This was based on the following links (and I see was mostly also proposed in #503):

 * <https://github.com/stevenlovegrove/Pangolin/issues/327>
 * <https://github.com/stevenlovegrove/Pangolin/commit/7a24ac185ea4d4f808df13fe0b45e8bc1b710e43>
 * <https://github.com/macvim-dev/macvim/blob/master/src/MacVim/MacVim.h#L43>

I understand the desire not to support older versions but thought for people who need it I can at least confirm that the code base still builds & runs for now.
