### ISSUE TITLE
Link to Carl Worth's talk under Miscellaneous is dead.

### ISSUE THREAD

**Issue by lringham** [apitrace/apitrace#507]
Hello,

The link to Carl Worth's talk under Documentation > Miscellaneous is dead. 
Namely, "Carl Worth linux.conf.au 2013 presentation on measuring/improving opengl performance with apitrace" with the url "http://mirror.linux.org.au/linux.conf.au/2013/mp4/Measuring_and_Improving_OpenGL_Performance.mp4"

I suggest replacing it with a video hosted on youtube "https://www.youtube.com/watch?v=NaIhuXvg39U" or you can download an older version of the video from the way back machine website.

**Comment by jrfonseca** [comment]
Thanks.  Fixed.
