### ISSUE TITLE
*.trace format

### ISSUE THREAD

**Issue by Iman-sm** [apitrace/apitrace#515]
I need to access and modify the API commands for my work and unfortunately i don't know that how is a trace file stored. it cannot be read using a normal text editing software so i converted the *.trace file to a text file using the dump command, yet i can't convert it back to *.trace format so i can replay the trace file (there is no way to replay a text file, right?). 
i also tried to understand the source code to see that how is a trace written to a file and i was also unsuccessful in that regard either.
So, the main question here is that how is a trace formatted and written to a file? and i'd really appreciate it if you can tell me that where in the source code i need to look if i ever need to modify the way that the trace is written to a file.

**Comment by jrfonseca** [comment]
https://github.com/apitrace/apitrace/blob/master/docs/FORMAT.markdown
