### ISSUE TITLE
Does not detect libdwarf 

### ISSUE THREAD

**Issue by moozaad** [apitrace/apitrace#519]
As they appear on the system
```
/usr/include/libdwarf/dwarf.h
/usr/include/libdwarf/libdwarf.h
```
cmake 3.7.2

```
> cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo
-- Found procps: /usr/lib64/libprocps.so  
-- Using bundled SNAPPY
-- Found ZLIB: /usr/lib64/libz.so (found suitable version "1.2.8", minimum required is "1.2.6") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- libdwarf not found. Disabling Backtrace support.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/moozaad/Documents/dev/apitrace/build
```

I added some debug to https://github.com/apitrace/apitrace/blob/master/thirdparty/libbacktrace/CMakeLists.txt#L126

```
include (CheckIncludeFile)
check_include_file (dwarf.h HAVE_DWARF_H)
check_include_file (libdwarf/dwarf.h HAVE_LIBDWARF_DWARF_H)

get_property(dirs DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY INCLUDE_DIRECTORIES)
foreach(dir ${dirs})
  message(STATUS "dir='${dir}'")
endforeach()

if (NOT HAVE_DWARF_H AND NOT HAVE_LIBDWARF_DWARF_H)
    set (FORMAT_FILE unknown.c)
    set (BACKTRACE_SUPPORTED 0)
    message (STATUS "libdwarf not found. Disabling Backtrace support.")
endif ()
```
output:
```
-- dir='/usr/include'
-- dir='/home/moozaad/Documents/dev/apitrace/compat'
-- dir='/home/moozaad/Documents/dev/apitrace/thirdparty/snappy'
-- dir='/usr/include'
```

I honestly can't see the issue, maybe need a rubber duck, as it should see /usr/include/libdwarf/dwarf.h

**Comment by jrfonseca** [comment]
IIRC `check_include_file(foo.h )` actually tries to compile a C/C++ file with an `#include "foo.h"`.

So perhaps the problem is not that it doesn't find the file per se, but that it fails to compile (because it needs additional includes.)

If that's the case here, then there should be some log files generated by CMake with the input C file and the compiler error.

**Comment by jrfonseca** [comment]
I can't repro this.  Furthermore I checked my `/usr/include/libdwarf/dwarf.h` and it has no `#include`s of its own, so my theory can't be right.

Perhaps what's happening is that `/usr/include/libdwarf/dwarf.h` was missing at some point in the past, but now that result is cached (in `CMakeLists.txt`) and CMake is not checking again anymore.  Try wiping out the build dir (e.g, by doing `git clean -fdx`) and build again.

**Comment by Quix0r** [comment]
Sorry, but the error is back. I freshly installed `libdwarf-dev:amd64 (20190529-1)` through `aptitude install` but it reports absence.

```
/usr/bin/ccache  gcc -D_GNU_SOURCE  -g -O3 -fPIC -fvisibility=hidden -Wall -Wno-sign-compare -fno-strict-aliasing -fmessage-length=0 -fno-omit-frame-pointer
/home/quix0r/git/build/apitrace/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: libdwarf/dwarf.h: No such file or directory
 #include <libdwarf/dwarf.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
But:
```
$ ls -l /usr/include/libdwarf/libdwarf.h 
-rw-r--r-- 1 root root 188741 Aug 25 17:39 /usr/include/libdwarf/libdwarf.h
$
```
So strange that it reports absence while it is there in fact.

"Fix": I had to cleanup the build directory so it can freshly detect it. It is now working.
