### ISSUE TITLE
Problem with Win32 API

### ISSUE THREAD

**Issue by Aidoru** [apitrace/apitrace#524]
Hello,
I' m trying to trace a simple opengl application (only display a cube on a Win32 Window) using win32 API (Window Application) but if I trace it the cube doesn' t appear and I cannot create any .trace file.
I don' t know if it is a bug o simple I cannot use Win32 GUI if I want to trace it.

Thank you

**Comment by jrfonseca** [comment]
From what you describe, it should work.  No idea why it doesn't..

**Comment by jrfonseca** [comment]
Run https://docs.microsoft.com/en-us/sysinternals/downloads/debugview and see what it shows while you trace

**Comment by Aidoru** [comment]
Ok, sorry it was a stupid problem:
shaders have to be in the apitrace.exe folder not in the application folder, I tried using GLFW and apitrace signal "shader not found" error, in win32 any error appear.

Thank you

**Comment by jrfonseca** [comment]
Cool.  You can also run apitrace from the directory where you application lives.  It should work.
