### ISSUE TITLE
OSMesa support

### ISSUE THREAD

**Issue by kyriazis** [apitrace/apitrace#525]
It would be nice to have OSMesa API support.

Currently, taking traces with osmesa apps ignores the osmesa calls, ending up with non-replayable traces.

**Comment by jrfonseca** [comment]
I wouldn't refuse a patch, but I'm afraid I can't implement it myself, as it's not a priority for me.

If anybody wants to venture, it's actually not too hard:
* fork `wrappers/glxtrace.py` into `osmesatrace.py`, and modify it accordingly
* add a `osmesatrace` target to `wrappers/CMakeLists.txt`
* fork `retrace/glretrace_glx.cpp` to `retrace/glretrace_osmesa.cpp` and modify it for OSMesa API.
