### ISSUE TITLE
DrawIndexedPrimitiveUP (D3D 8/9) calls broken with non-zero MinVertexIndex values

### ISSUE THREAD

**Issue by Ullion** [apitrace/apitrace#526]
Any DrawIndexedPrimitiveUP calls with a non-zero MinVertexIndex value leads to broken/glitched polygons being rendered. MinVertexIndex doesn't appeared to be used? It should be an offset of the vertex buffer.

Wine had a similar bug a while back, now fixed, for what it's worth:
https://source.winehq.org/git/wine.git/commitdiff/bbce5af7d39c54bad156aa0754e7eb4cd03552e4
https://source.winehq.org/git/wine.git/commitdiff/76686d4cc63e29e7a86335da1070c64f671b33db
https://source.winehq.org/git/wine.git/commitdiff/ea11b2752806e7467923de3c982ab2b89512697c

**Comment by jrfonseca** [comment]
You're right.  It should be fixed now.  Thanks!
