### ISSUE TITLE
glretrace: 2722: error: caught an unhandled exception

### ISSUE THREAD

**Issue by lwjglapitrace** [apitrace/apitrace#529]
At home, I have a Jenkins instance set up, with a job that runs my LWJGL application via VirtualGL. The .trace file is created with the following command:

`LD_PRELOAD=/usr/lib/apitrace/wrappers/glxtrace.so vglrun gradle test`

The .trace file that is generated is available here: https://dropfile.to/pRUKMxh

Next, I have a second job that runs a replay against a specific trace for a specific call. This replay is called with:

`/usr/bin/glretrace -D ${CALL_ID} /mnt/data/builds/apitraces/${TRACE_ID}/java.trace > /mnt/data/builds/apitraces/${TRACE_ID}/dumps/${CALL_ID}.json`

However, when that job runs, it fails with:

```+ /usr/bin/glretrace -D 500234 /mnt/data/builds/apitraces/1505076462/java.trace
2696: message: major api error 1282: GL_INVALID_OPERATION error generated. The required buffer is missing.
2696: warning: glGetError(glReadBuffer) = GL_INVALID_OPERATION
2713: message: api issue 131185: Buffer detailed info: Buffer object 1 (bound to GL_PIXEL_PACK_BUFFER_ARB, usage hint is GL_STREAM_READ) will use DMA CACHED memory as the source for buffer object operations.
glretrace: /build/apitrace/src/apitrace-7.1/retrace/glws_glx.cpp:139: virtual void glws::GlxDrawable::swapBuffers(): Assertion `!pbuffer' failed.
apitrace: warning: caught signal 6
2722: error: caught an unhandled exception
/usr/bin/glretrace+0x234eec
/usr/lib/libc.so.6+0x3393f
/usr/lib/libc.so.6: gsignal+0x110
/usr/lib/libc.so.6: abort+0x1b1
/usr/lib/libc.so.6+0x2c5bd
/usr/lib/libc.so.6: __assert_fail+0x42
/usr/bin/glretrace+0xbe38
/usr/bin/glretrace+0xc48b
/usr/bin/glretrace+0xca29
/usr/bin/glretrace+0x771f
/usr/lib/libc.so.6: __libc_start_main+0xe9
/usr/bin/glretrace: _start+0x28
?
apitrace: info: taking default action for signal 6
/tmp/jenkins5802488658496973992.sh: line 14: 15702 Aborted                 (core dumped) /usr/bin/glretrace -D ${CALL_ID} /mnt/data/builds/apitraces/${TRACE_ID}/java.trace > /mnt/data/builds/apitraces/${TRACE_ID}/dumps/${CALL_ID}.json
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
After some searching, I found a post that mentioned glretrace failing, and the solution was to to specify the --sb flag. Specifying this flag as part of the glretrace run resolved the issue for me, and the replay was able to run successfully. I am running apitrace 7.1 on Arch Linux.

**Comment by jrfonseca** [comment]
@lwjglapitrace Apologies for the delay.  I was about to look into this but the DropBox file expired.  Could you please attached it again? Thanks.

I have a good idea of what's the problem -- glretrace doesn't honour double/single buffer visual's that the recorded application used, but rather always presumes double buffer.

Still, having an easy repro would make things easier.

**Comment by okias** [comment]
@lwjglapitrace if the issue still occurs with recent apitrace, please provide the trace again and feel free to reopen.
