### ISSUE TITLE
Parsing base64 textures/framebuffer images output from glretrace

### ISSUE THREAD

**Issue by oenglesy** [apitrace/apitrace#530]
Currently, when I run glretrace with:

`glretrace -D 501876 myapp.trace > myapp.json`

The resulting JSON contains entries for "textures" and "framebuffer". The image data for the image entries of these properties looks to be in base64 format, but I can only get the stencil depth buffer to convert to a valid PNG image. When I try to parse a GL_TEXTURE_BUFFER to an image, I get an error message relating to how PX is not a valid signature.

Is it possible that there is a bug with how images are generated?

How does qapitrace display these images? When I view my GL_TEXTURE_BUFFER in qapitrace, I get a black and red image. 

Is it possible to have apitrace convert the bas64 to valid PNG images for me?

**Comment by jrfonseca** [comment]
Some images are indeed base64 encoded PNG.  But when the source data does not fit 8 bits normalized unsigned integers, then they are base64 encoded [PFM](http://netpbm.sourceforge.net/doc/pfm.html), which stores them as floats.

The `PX` is actually a non-standard extension of the PFM format to four floats, as the original PFM format only supports 1 or 3 floats.  See https://github.com/apitrace/apitrace/blob/master/lib/image/image_pnm.cpp#L70

qapitrace understands these formats.
