### ISSUE TITLE
How to override gl core context version ?

### ISSUE THREAD

**Issue by CapOM** [apitrace/apitrace#531]
Hi,

I have an apitrace that creates a gl 4.3 core context, is it possible to hack it so it creates 4.1 ? I know the apitrace might not work well if it uses 4.3 features but this is a test.

In apitrace dump I can see:

glXCreateContextAttribsARB(dpy = 0x1dce400, config = 0x1f278e0, share_context = NULL, direct = True, attrib_list = {GLX_CONTEXT_MAJOR_VERSION_ARB, 4, GLX_CONTEXT_MINOR_VERSION_ARB, 3, GLX_CONTEXT_PROFILE_MASK_ARB, GLX_CONTEXT_CORE_PROFILE_BIT_ARB, 0}) = 0x1e2a840

Thx!

**Comment by jrfonseca** [comment]
Sorry for the delay replying.  It's probably too late now, but in any case...

I don't see an easy way to do this.  qapitrace doesn't seem to allow to edit arrays yet.  So the only solution would be to manually modify the glretrace source code:

    diff --git a/retrace/glretrace_glx.cpp b/retrace/glretrace_glx.cpp
    index 6094266e..30e057af 100644
    --- a/retrace/glretrace_glx.cpp
    +++ b/retrace/glretrace_glx.cpp
    @@ -97,6 +97,8 @@ static void retrace_glXCreateContextAttribsARB(trace::Call &call) {
     
         const trace::Value * attrib_list = &call.arg(4);
         glfeatures::Profile profile = parseContextAttribList(attrib_list);
    +    profile.major = 4;
    +    profile.minor = 1;
     
         Context *context = glretrace::createContext(share_context, profile);
         context_map[orig_context] = context;


BTW you're using Mesa OpenGL drivers you can also use `MESA_GL_VERSION_OVERRIDE`, per https://www.mesa3d.org/envvars.html

**Comment by CapOM** [comment]
Great, thx !
