### ISSUE TITLE
D3DFMT_INTZ format

### ISSUE THREAD

**Issue by Iman-sm** [apitrace/apitrace#535]
Hi,
I've been trying to develop a program to replay a trace using the "dump"ed data from that trace. Yet, I've encountered the "D3DFMT_INTZ" format which is not a standard D3DFORMAT (thus, not recognizable by direct3d) and is defined by the APITrace (along with some other formats), but it is passed as an argument to IDirect3DDevice9::CreateTexture method. Is there a way to replace D3DFMT_INTZ  in CreateTexture method so that it is possible to run it as a normal direct3d method? I tired to read the APITrace source code to understand the purpose of defining D3DFMT_INTZ so i could tackle the situation (I take it that it is a 1 channel float type buffer) but i was unsuccessful. 
Thanks

**Comment by jrfonseca** [comment]
INTZ format is unofficial, but it was not invented by apitrace.  See https://aras-p.info/texts/D3D9GPUHacks.html#depth

If you see INTZ format in the trace, that's because the application is using the INTZ format, and there's nothing apitrace can do to escape that fact...
