### ISSUE TITLE
Can not replay RetroArch traces.

### ISSUE THREAD

**Issue by orbea** [apitrace/apitrace#537]
OS: `Slackware64-current`
`apitrace-2017.10.18_73dc602_master-x86_64-1_git`
RetroArch commit: https://github.com/libretro/RetroArch/commit/7ff25fe732d083f8b1527ff2497dc93e1007ee73

When replaying RetroArch traces nothing displays and this is printed many times.
```
4156 @0 glXSwapBuffersMscOML(dpy = 0x2417210, drawable = 50331651, target_msc = 0, divisor = 0, remainder = 0) = 1
4156: warning: unsupported glXSwapBuffersMscOML call
```
Full log.
https://pastebin.com/AcsYwPB0

Here is an example trace.
http://ks392457.kimsufi.com/orbea/stuff/trace/retroarch.trace.xz

Is there anything that can be done to resolve this?

**Comment by jrfonseca** [comment]
It should be fixed now.  It was trivial -- just a matter of honouring glXSwapBuffersMscOML .  The other ignored calls are harmless.

**Comment by orbea** [comment]
Thanks a lot!
