### ISSUE TITLE
poor quality recording OpenGL

### ISSUE THREAD

**Issue by mikeglaz** [apitrace/apitrace#539]
I'm not sure this is the right place to post but when I try the following:
`apitrace dump-images -o - solid.trace | ffmpeg -r 30 -f image2pipe -vcodec ppm -i pipe: -vcodec mpeg4 -y solids.mp4`

I get very poor quality during the playback of the .mp4.  Is there a setting I need to adjust?

**Comment by jrfonseca** [comment]
`ffmpeg` is an external/independent project.  There are many ways to adjust quality of video compression with `fmpeg`, but you need to refer to its documentation.  See https://trac.ffmpeg.org/wiki/Encode/MPEG-4
