### ISSUE TITLE
Remove github auth token from repository

### ISSUE THREAD

**Issue by hvoigt** [apitrace/apitrace#554]
Just saw this while searching for something else:

https://github.com/apitrace/apitrace/blob/1cb7b77a3846df2c775fe0bcafde7cc5940774e9/appveyor.yml#L47

Not shure if it is very secure to distribute the upload token for github to everyone. I would think that should be put somewhere private or everyone can upload to your github releases, no?

Cheers Heiko

**Comment by jrfonseca** [comment]
That's not a plain-text github auth token, but rather one encrypted by AppVeyor as explained in https://www.appveyor.com/docs/deployment/github/ .

So only Appveyor build infrastructure knows how to decrypt it and therefore. (Of course, I'm explicitly trusting Appveyor with this information.)

Thanks for your concern nevertheless.  Cheers
