### ISSUE TITLE
make a new release

### ISSUE THREAD

**Issue by vitlav** [apitrace/apitrace#570]
please, make a new release (with tag and tarball)

**Comment by orbea** [comment]
This would be nice, I maintain apitrace for slackbuilds.org and for various reasons I found the last release too buggy and was forced to update to an arbitrary git revision which includes many relevant and useful bug fixes.

**Comment by jrfonseca** [comment]
Finally fixed -- https://github.com/apitrace/apitrace/releases/tag/8.0  -- thanks for your patience.
