### ISSUE TITLE
Consider moving to Python 3.x

### ISSUE THREAD

**Issue by linkmauve** [apitrace/apitrace#574]
With Python 2.7’s EOL approaching quite fast (only one year and three months remaining), the switch to Python 3 should happen very soon.

I’d suggest supporting not earlier than 3.5, which is what is currently available in “stable” distributions.

**Comment by JayFoxRox** [comment]
I'm also interested in this.

I checked the fork-network, and there's some work by @p-podsiadly in https://github.com/p-podsiadly/apitrace/tree/python3 (4 months old by now). I'm not sure what the state of this is, and did not try running it.

**Comment by jrfonseca** [comment]
Other than Python3 vs PythonInterp issue, the @p-podsiadly  change looks good to me.

I've pushed it to https://github.com/apitrace/apitrace/tree/python3  .  Let's how Travis/AppVeyor builds go.

**Comment by jrfonseca** [comment]
Fixed now, though I wouldn't be surprised if there are a few issues lingering somewhere.

Thanks @p-podsiadly for doing the bulk of the work, and @JayFoxRox for drawing my attention to it.

**Comment by etam** [comment]
docs/INSTALL.markdown still says that it requires Python 2.7

**Comment by jrfonseca** [comment]
@etam, indeed.  Fixed iin ddb32e0d1f00b78727464f2abb8c0fe766b401ca .  Thanks
