### ISSUE TITLE
Trace contains invalid buffer data when captured on GLES2 driver supporting GL_EXT_unpack_subimage

### ISSUE THREAD

**Issue by freemangordon** [apitrace/apitrace#599]
If I read the code correctly, GL_UNPACK_ROW_LENGTH, GL_UNPACK_SKIP_ROWS and GL_UNPACK_SKIP_PIXELS are assumed to be supported only on GL, however, we have https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_unpack_subimage.txt, which allows them to be supported on gles2 as well. If a trace is captured on a driver that supports the extension, those 3 parameters are ignored and buffer size is incorrectly calculated, leading to segfault later on when one tries to replay the trace.

**Comment by freemangordon** [comment]
https://github.com/freemangordon/apitrace/commit/353cec3ec76054ef78661f42159683200e50775a fixes the replay segfault, however, I don't know how to deal with https://github.com/apitrace/apitrace/blob/master/helpers/eglsize.cpp#L103, hits are to be appreciated

**Comment by freemangordon** [comment]
I did https://github.com/freemangordon/apitrace/commit/c9b84a9fbee62f7d26f61b25ea0078a9d393f0b2 , but honestly have no idea if this is the correct way of fixing it nor I have a clue how to test it properly.

**Comment by jrfonseca** [comment]
Thanks, you're right.  It should be fixed now.

**Comment by freemangordon** [comment]
what about https://github.com/freemangordon/apitrace/commit/c9b84a9fbee62f7d26f61b25ea0078a9d393f0b2 ?

**Comment by jrfonseca** [comment]
I did look into your change before my fix, but it wasn't the best way.  It would cause glGetStrings to be called and its result parsed with frequency, both on desktop and ES GL versions.  My change does the same thing, but it caches the result so it's only done once.
