### ISSUE TITLE
Can GL_BACK buffer be GL_RGBA format?

### ISSUE THREAD

**Issue by julienmoumne** [apitrace/apitrace#602]
As in the attached screenshot, when using `qapitrace` to have a look at the GL_BACK buffer, we see that the color format is GL_RGB.

![screenshot at 2019-01-24 16-55-26](https://user-images.githubusercontent.com/723165/51690557-3a7b7d00-1ff9-11e9-811c-3667fdb6da70.png)

This means we loose the alpha channel.

Is there anyway to tell `apitrace` to retain the alpha values?

The end goal is to render images/videos that retain the alpha component.

Thanks for the help.

**Comment by julienmoumne** [comment]
Thanks for the help.

Would you have an idea of how one can use `apitrace`/`glretrace` to generate images/videos that includes the alpha layer?

As far as I understand, the images produced by `glretrace` are not in a format that support an alpha layer, right?

**Comment by julienmoumne** [comment]
It's actually possible to dump PNGs with alpha channel by using the option `--snapshot-alpha` present on the master branch.

Thanks for such a great tool.

Cheers

**Comment by jrfonseca** [comment]
Glad to hear it! Thanks.
