### ISSUE TITLE
Wrong number of frame calls 

### ISSUE THREAD

**Issue by Lecrapouille** [apitrace/apitrace#608]
- The inclosed WrongFrameCount.png Apitrace has detected an incorrect number of OpenGL calls: 67 calls while 34 where effectively called. 
![WrongFrameCount](https://user-images.githubusercontent.com/17874458/56171581-1fac1980-5fe6-11e9-90f5-f8f45ab8fc8f.png)
- The inclosed CorrectFrameCount.png Apitrace has detected 27 calls which is the correct number. ![CorrectFrameCount](https://user-images.githubusercontent.com/17874458/56171556-086d2c00-5fe6-11e9-9c51-dfb28f4e2924.png)

- I'm debugging my application and I compare it to a reference application. Apitrace displays incorrect number of calls for my application. The only difference is that I do some extra OpenGL calls like unbind GLProgram, AttribArray and I bind VBOs.

**Comment by jrfonseca** [comment]
The remains calls are probably hidden, as qapitrace by default hides uninteresting calls just as `glGet*`.

Go to Trace > Options, and untick all hidden events.

**Comment by Lecrapouille** [comment]
Thank you a lot! I did not notice this Option and I totally forget that I wrapped all my OpenGL functions with a macro calling glGetError. So the number of calls is correct :)
