### ISSUE TITLE
Printing errors with --dump-format=json rather than --dump-format=ubjson

### ISSUE THREAD

**Issue by hellmouthengine** [apitrace/apitrace#613]
I'm trying to capture the list of errors output in the qapitrace UI

When I use qapitrace, I can see the equivalent glretrace command being printed on the console

This command looks something like:

`glretrace --dump-format=ubjson -D=101 mytracefile`

When I run this command on the command line, I get the ubjson output, and the list of errors I see in qapitrace

However, I don't want ubjson, but just regular json. Running the following command does not give me an error list:

`glretrace --dump-format=json -D=101 mytracefile`

Is there an additional flag I can pass to glretrace, or is it possible to have the error list generated as part of the json formatted output?

Right now I can work around this by capturing (what I'm assuming is) the stderr output of an ubjson run, and the stdout output of a json run, and combining the two to get the complete data set I'm interested in - but I was just curious if there was a more straightforward way of doing it?

Thanks for all your efforts with this project!

**Comment by jrfonseca** [comment]
My understanding is that glretrace errors are _always_ printed to stderr when dumping state, regardless of dump format.  If there were errors intermingled on stdout, the JSON/UBSON would become invalid.  Are you you're seeing errors on stdout?

**Comment by jrfonseca** [comment]
As I said above I don't believe this issue really exists -- there should be no errors on stdout -- just stderr.  Please reopen if you can provide a test case showing otherwise.
