### ISSUE TITLE
How does apitrace get NVfp representation of GLSL shaders?

### ISSUE THREAD

**Issue by 10110111** [apitrace/apitrace#617]
One wonderful feature I found in apitrace when exploring the trace generated from my app using `qapitrace`, is that on an NVidia GPU, along with `GL_FRAGMENT_SHADER` in the _Shaders_ tab, I can view `NVfp5.0`, although my app is completely unaware of the `NV_*_program*` extensions. I assume these entries in the _Shaders_ tab represent the NVidia driver's view of my GLSL shader (the codes do appear functionally the same).

Having all this, I've been unable so far to find how exactly apitrace gets these NV-assembly strings. I've tried to simply check `glGetProgramivNV(GL_FRAGMENT_PROGRAM_NV, GL_PROGRAM_LENGTH_NV, &progLength);`, but it gives me 0 as the length. And I've also failed to find any similar statements in the apitrace source.

So my question is: how does apitrace obtain these NV-assembly strings? How can I do the same in my program without the need to trace it and explore the trace after the program has terminated?

**Comment by jrfonseca** [comment]
It does that through `GL_ARB_get_program_binary` extension.  It so happens NVIDIA's program binaries include the plain-text programs it generates internally.

See https://github.com/apitrace/apitrace/commit/49192a4e48d080e44a0d66f059e6897f07cf67f8
