### ISSUE TITLE
replay trace file at different resolution

### ISSUE THREAD

**Issue by grundmanns** [apitrace/apitrace#622]
Hello Apitrace team,

I try to replay a trace file at a different resolution. I managed to do so in a simple trace file by editing glViewport and glScissor in qapitrace. It worked perfect.
Unfortunately I have a trace files that does glViewport and glScissors 3x per frame and there are 500 frames to playback. this means I would have to edit 3000 entries in the GUI, which looks rather unfriendly to change the file.

My hope was to use apitrace sed but I do not really understand how to use it and what it really can replace (I am familiar with sed / grep and regexp).
I already tried to explore cli_sed.cpp to check weather sed would be an option but I was not easily understood by me.

I checked qapitrace but it does not seem to contain a search and replace function that can do this job.

Can somebody suggest me into the right direction for this job ?

BR
Sven

ps: I use the apitrace cloned from github using Waffle  / Wayland on aarch64 for replay (which works brilliant)

**Comment by jrfonseca** [comment]
`apitrace sed` is not powerful enough for this.  There's really no good way to do this automatically with apitrace as it stands today.  And it would be really difficult to do so, without adding some sort of scripting language.

If you're determined to do this, the easiest way would be to modify `lib/trace/trace_parser_flags.cpp`, to detect the calls you want, and manually modify the arguments of the calls you care.

You could then obtain an updated trace by running `apitrace sed` without extra options.

**Comment by grundmanns** [comment]
Hello jrfonseca,
thank you very much for your quick answer.
I checked lib/trace/trace_parser_flags.cpp and it did not contain glViewport / glScissors.
Instead there is some autogenerated code generated by retrace/glretrace.py in the build directly. I seems that it takes care of glViewport / glScissor .
Did I misunderstood your suggestion ?
BR
Sven

**Comment by jrfonseca** [comment]
> I checked lib/trace/trace_parser_flags.cpp and it did not contain glViewport / glScissors.

Sorry, ` lib/trace/trace_parser_flags.cpp` was the wrong place.  I meant something like

    diff --git a/lib/trace/trace_parser.cpp b/lib/trace/trace_parser.cpp
    index 73e287c8..c4c42435 100644
    --- a/lib/trace/trace_parser.cpp
    +++ b/lib/trace/trace_parser.cpp
    @@ -639,6 +639,11 @@ void Parser::adjust_call_flags(Call *call) {
             call->ret->toSInt() == 0) {
             call->flags |= CALL_FLAG_VERBOSE;
         }
    +
    +    if (strcmp(call->sig->name, "glViewport") == 0) {
    +        call->args[2].value = new UInt(1024);
    +        call->args[3].value = new UInt(768);
    +    }
     }
     
     void Parser::parse_arg(Call *call, Mode mode) {

**Comment by grundmanns** [comment]
Hello jrfonseca,
thank you very much. Your help is much appreciated. I will check it.
BR
Sven
