### ISSUE TITLE
release 8.1 with python3 support

### ISSUE THREAD

**Issue by tjaalton** [apitrace/apitrace#629]
Please tag a release which supports python3.

**Comment by jrfonseca** [comment]
Indeed, I've should have done it long time ago.  I'll try to get it done soon.

**Comment by JayFoxRox** [comment]
This can be closed now; see https://github.com/apitrace/apitrace/releases/tag/9.0

**Comment by jrfonseca** [comment]
Ah, yes, forgot to do so.  Thanks
