### ISSUE TITLE
D3D11 not able to look up state while replaying

### ISSUE THREAD

**Issue by vaibhavgupta-bst** [apitrace/apitrace#632]
I am able to replay the trace in Gl mode and d3d9 mode but setting --api=dxgi creates the trace but while i replay it , the thumbnails are not generated and the apitrace tool keeps on looking the state with bar reached to 100%.
this happens for freestyle2 :Dunk game (korean game)

**Comment by jrfonseca** [comment]
Please provide me the trace.  See https://github.com/apitrace/apitrace/blob/master/docs/BUGS.markdown#attachments

**Comment by jrfonseca** [comment]
I'm closing as I'd need the trace to investigate this further.  Feel free to reopen if you can provide it.

**Comment by vaibhavgupta-bst** [comment]
d11.trace
<https://drive.google.com/a/bluestacks.com/file/d/1iuHUVCjG2QF2AYVvPp3ApsnLBOZxwB3I/view?usp=drive_web>
Still facing the issue as can't replay the trace in dx11 but can do it in
dx9
PFA the trace and the screenshot for the error in d3d11createdevice
Regards,
Vaibhav Gupta
Member, Technical Staff (System-Dev)
