### ISSUE TITLE
Civilization VI traces corrupt

### ISSUE THREAD

**Issue by janesma** [apitrace/apitrace#633]
Traces made of Civ6 fail to parse on a call to glCompressedTexImage2D

I've reproduced this with master and the 8.0 tag.

To capture the trace, I set launch options in steam: 
```
  {path_to}/apitrace trace -o /tmp/civ.trace %command%
```
You can get the parse error with
```
   > apitrace dump /tmp/civ.trace
   error: (glCompressedTexImage2D) unknown call detail 81
```
After parsing the blob from param 7 of glCompressedTeximage2D, the following byte is not a call detail.  Several calls to glCompressedTexImage2D successful before the crash.

I can't figure out how to debug the tracing through the steam engine, but I would be happy to look if someone can point me in the right direction.

A sample trace file is at:

 http://swizzler.org/imgcache/civ.trace.xz

**Comment by werman** [comment]
Could you try with https://github.com/apitrace/apitrace/pull/626?

**Comment by jrfonseca** [comment]
@werman appologies. I'll try to get it commited regardless.

**Comment by janesma** [comment]
Thanks for the pointer!  It definitely looks like the type of issue that would cause my crash.  Unfortunately, I couldn't get Civ 6 to trace after building apitrace master with the fix from #626.

**Comment by werman** [comment]
Additional info about launching the game, add:  
`LD_PRELOAD=/usr/lib/libfreetype.so.6 LD_LIBRARY_PATH=/usr/lib/openssl-1.0` for game to launch, at least on arch.
To bypass launcher (it is stuck when being traced) use:
`~/.steam/steam/steamapps/common/Sid\ Meier\'s\ Civilization\ VI/Civ6Sub %command%`

**Comment by werman** [comment]
Now I'm unable to reproduce the issue.

**Comment by janesma** [comment]
I can still reproduce the issue when I try to create a trace with the launcher options method.  However, I have found a method that does take a working trace:

```
cd ~/.steam/steam/steamapps/common/Sid\ Meier\'s\ Civilization\ VI
~src/apitrace/build/apitrace trace -o /tmp/civ.trace /home/majanes/.steam/ubuntu12_32/steam-runtime/run.sh ~/.steam//steam/steamapps/common/Sid\ Meier\'s\ Civilization\ VI/Civ6Sub -benchmark
```

For some reason, the launch options method for taking traces no longer works for several steam titles.  My steam client was updated, which may have something to do with it.  Fewer windows are shown when launching from the command line.

**Comment by janesma** [comment]
since I can get a working trace, I think this issue has more to do with the steam client than apitrace.
