### ISSUE TITLE
Replay API

### ISSUE THREAD

**Issue by mhuzai** [apitrace/apitrace#635]
(Wasn't sure where else to ask this question.)

Is there a programming API for the replay functionality? I am trying to replay frames from within an application and was wondering if it would be possible to do so via some function call to apitrace (as opposed to doing it from the command line).

Thank you!

**Comment by jrfonseca** [comment]
No, there's no replay API.  It's not clear what would be the goal of such API: another graphics derived tool, or just play traces like a movie?  But whatever it might be, i really have no intention to create and support a replay API.

Perhaps one that we could have some sort of network protocol between retrace and GUI, which third party applications/tools could build upon.  But for now, the only interface provided to replay functionality is CLI.

If CLI doesn't work, you could fork and and embed apitrace on your app.  https://github.com/p3/regal did this for example.
