### ISSUE TITLE
helpers/glsize.hpp:928: bad test ?

### ISSUE THREAD

**Issue by dcb314** [apitrace/apitrace#640]
helpers/glsize.hpp:928:44: warning: logical 'and' of mutually exclusive tests is always false [-Wlogical-op]

Source code is

  if (code_point < 65536 && code_point > 1114111) {

Maybe better code:

  if (code_point < 65536 || code_point > 1114111) {

**Comment by jrfonseca** [comment]
CC'ing @markkilgard

But based on the following assertion,

    assert(code_point >= 65536 && code_point <= 1114111);

there's little doubt that `||` was intended.

**Comment by jrfonseca** [comment]
Thank you.

**Comment by markkilgard** [comment]
I agree with you.
