### ISSUE TITLE
The freeze happens in "Deus Ex: Mankind Divided" while trying to trace the game

### ISSUE THREAD

**Issue by asimiklit** [apitrace/apitrace#642]
The issue source is here: https://gitlab.freedesktop.org/mesa/mesa/issues/2123#note_314517
The fix for a freeze: https://github.com/apitrace/apitrace/pull/641

**Comment by jrfonseca** [comment]
Can I mark this as fixed now that https://github.com/apitrace/apitrace/pull/641 has been merged?

**Comment by asimiklit** [comment]
I double checked it on master just for case, the issue disappeared, so it could be closed. Thanks for reviewing)
