### ISSUE TITLE
Rip like Ninja Ripper (Linux)

### ISSUE THREAD

**Issue by 0Curtain0** [apitrace/apitrace#643]
Hi, forgive me if I am asking in the wrong place. 

I was working on a guide for ripping 3D models with a program called Ninja Ripper: 
- https://www.deviantart.com/xcurtainx/journal/Rip-Your-Favorite-3D-Game-Character-Models-FREE-753410159 

Not too long ago, Valve released [Steam Play](https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561) which allows Linux users to play Windows games using [Proton](https://github.com/ValveSoftware/Proton). 
The list of Proton supported games is growing everyday: https://www.protondb.com/ 

I have recently moved to Linux but I am curious to know if apitrace would be able to do what Ninja Ripper does but for Linux. 

I am not a programmer, but I believe the author of Ninja Ripper released only the source code for the x86 version of the program. 
- https://github.com/riccochicco/ninjaripper

**Comment by jrfonseca** [comment]
Something like this is requested every now an dthen.  But it's supper difficult to do this effectively and generally nowadays, where everything is done in shaders, and there's little or no fixed function.  So there's no standard layout for model data.  I'm afraid it's not a feature a can afford to support, even if somebody else did most of the work, it will just add to maintenance burden, and I already struggle to cope as it is.  Sorry.
