### ISSUE TITLE
mainwindow.cpp: 2 * this condition has identical branches

### ISSUE THREAD

**Issue by dcb314** [apitrace/apitrace#647]
1.

gui/mainwindow.cpp:848:5: warning: this condition has identical branches [-Wduplicated-branches]

    if (shaderSources.isEmpty()) {
        m_sourcesWidget->setShaders(shaderSources);
    } else {
        m_sourcesWidget->setShaders(shaderSources);
    }

2.

gui/mainwindow.cpp:1646:13: warning: this condition has identical branches [-Wduplicated-branches]

Duplicate.

**Comment by jrfonseca** [comment]
Good find.  Thanks.

**Comment by jrfonseca** [comment]
Reopened by mistake.. Closing.
