### ISSUE TITLE
OpenGL API trace crash on startup in End of Time demo by Alcatraz & Altair

### ISSUE THREAD

**Issue by kode54** [apitrace/apitrace#652]
This demo:

http://www.pouet.net/prod.php?which=77102

...Which comes in at under 5KB, crashes the OpenGL tracer. It also doesn't run in Wine, crashing in the same way there. It's probably doing something fishy.

**Comment by jrfonseca** [comment]
Fixed now.  It was a matter of apitrace opengl32.dll's export ordinals not matching Windows'.  WINE issue might be the same.

It's so rare for applications to import DLL symbols by ordinal.  But it's a way to save bytes, which is what this sort of fantastically small apps are all about.

**Comment by kode54** [comment]
Thanks, I'll test that now, but I suppose you already did that?
