### ISSUE TITLE
How to apitrace a steam game within firejail?

### ISSUE THREAD

**Issue by AndtJe** [apitrace/apitrace#659]
Can I get an apitrace of a steam game running inside of firejail (https://github.com/netblue30/firejail)?

`firejail DEBUGGER="apitrace trace" steam steam://rungameid/xxxxxx`
(where xxxxxx is any gameid) doesn't work:
```
/bin/bash: DEBUGGER=apitrace trace: command not found
Parent is shutting down, bye...
```

and

`DEBUGGER="apitrace trace" firejail steam steam://rungameid/xxxxxx`
does not return an error and launches the game but does not create a trace.

Installing lib32-apitrace did not help either.

**Comment by werman** [comment]
What about using game's launch options:
`apitrace trace %command%`

**Comment by AndtJe** [comment]
Here are all the commands I tried. Apitrace on it's own works (but not like the wiki suggested - is https://github.com/apitrace/apitrace/wiki/Steam outdated?), firejail on it's own works, too. But once I try using both, it does not work, but perhaps I need to write the command differently.

- `apitrace trace steam steam://rungameid/278360`
[starts game but does not generate trace] 

- `DEBUGGER="apitrace trace" steam steam://rungameid/278360`
[starts game but does not generate a trace]

- `apitrace trace "/home/manjaro/.local/share/Steam/steamapps/common/_GameName_ /Binaries/linux-amd64/_GameExecutable_"`
[starts game+ generates trace!]
locating the executable and ignoring the wiki advice helped

Now with firejail: 

- `firejail apitrace trace "/home/manjaro/.local/share/Steam/steamapps/common/_GameName_/Binaries/linux-amd64/_GameExecutable_"`
[doesn't start game, no trace]

<p>
<details>
<summary>&emsp;&emsp;output</summary>
<pre><code>
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 118186, child pid 118187
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: cleaning all supplementary groups
Child process initialized in 56.03 ms
apitrace: loaded into /usr/bin/apitrace
apitrace: unloaded from /usr/bin/apitrace
error: failed to execute: /home/manjaro/.local/share/Steam/steamapps/common/A Story About My Uncle/Binaries/linux-amd64/ASAMU

Parent is shutting down, bye...
</code></pre>
</details>
</p>


- `apitrace trace firejail "/home/manjaro/.local/share/Steam/steamapps/common/_GameName_/Binaries/linux-amd64/_GameExecutable_"`
[doesn't start game, no trace]

<p>
<details>
<summary>&emsp;&emsp;output</summary>
<pre><code>
apitrace: loaded into /usr/bin/apitrace
apitrace: unloaded from /usr/bin/apitrace
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 118202, child pid 118203
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: cleaning all supplementary groups
Child process initialized in 52.18 ms
/bin/bash: /home/manjaro/.local/share/Steam/steamapps/common/A Story About My Uncle/Binaries/linux-amd64/ASAMU: Permission denied

Parent is shutting down, bye...
</code></pre>
</details>
</p>


- `firejail DEBUGGER="apitrace trace" "/home/manjaro/.local/share/Steam/steamapps/common/_GameName_/Binaries/linux-amd64/_GameExecutable_"`
[doesn't start game, no trace]

<p>
<details>
<summary>&emsp;&emsp;output</summary>
<pre><code>
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 118746, child pid 118747
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: cleaning all supplementary groups
Child process initialized in 53.66 ms
/bin/bash: DEBUGGER=apitrace trace: command not found

Parent is shutting down, bye...
</code></pre>
</details>
</p>


- `DEBUGGER="apitrace trace" firejail "/home/manjaro/.local/share/Steam/steamapps/common/_GameName_/Binaries/linux-amd64/_GameExecutable_"`
[doesn't start game, no trace]

<p>
<details>
<summary> &emsp;&emsp; output</summary>
<pre><code>
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 120249, child pid 120250
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: cleaning all supplementary groups
Child process initialized in 54.95 ms
/bin/bash: /home/manjaro/.local/share/Steam/steamapps/common/A Story About My Uncle/Binaries/linux-amd64/ASAMU: Permission denied

Parent is shutting down, bye...
</code></pre>
</details>
</p>

- `firejail steam steam://rungameid/_xxxxxx_`
[starts game]

- `firejail apitrace trace steam steam://rungameid/_xxxxxx_`
[doesn't work at all]
`Couldn't set up Steam data - please contact technical support`

**Comment by turol** [comment]
Firejail hides a lot of stuff, including binaries under `/usr/bin` where apitrace is probably installed. You need to change the firejail profile you're using to whitelist apitrace and its libraries.

**Comment by AndtJe** [comment]
I have to correct some of my earlier statements: in some cases, the trace was generated successfully, just not in home but inside of the steam folder structure at the location of the game executable.

/usr/bin is accessible from within firejail (at least with the default profile).

Thank you for your help!
