### ISSUE TITLE
Cannot reproduce Navi hang when running apitrace

### ISSUE THREAD

**Issue by Evernow** [apitrace/apitrace#661]
Hello there!

Apologies if this is not the correct place to put this, but I've been encountering many issues and have not been able to get them to be reproduced when doing an apitrace. 

In many games such as The Witcher 2, Half Life 2 episode 2, Frostpunk, Space Engineers, Quantum break hang when not doing an apitrace on my Navi GPU on Manjaro, but when doing an apitrace they do not hang. 

This makes gathering useful logs to troubleshoot the issue very difficult, especially since the AMD developers cannot reproduce the issue easily, even when I report how to reproduce it: 

Space Engineers still hangs: https://gitlab.freedesktop.org/mesa/mesa/issues/2121

Frostpunk still hangs: https://gitlab.freedesktop.org/mesa/mesa/issues/2447

Subnautica still hangs: https://gitlab.freedesktop.org/mesa/mesa/-/issues/2791

The Witcher 2 still hangs: https://gitlab.freedesktop.org/mesa/mesa/issues/2369

All these issues are in limbo, and I cannot capture an apitrace that contains the code that hangs it because when capturing an apitrace it never hangs. Hell I even completed full games while doing an apitrace because that was the only way to stop it from hanging my entire system. 

Any help is greatly appreciated!

**Comment by jrfonseca** [comment]
I glanced over those mesa bug reports, and the feeling I get is that these issues are inherently random.   So even though the race condition it happens when recording, it might not happen when replaying.

What I usually try in such circumstances, often with success, is replay the trace over and over again, and in parallel.

That is, try something like:

    TRIES=32
    NPROC=2
    seq 1 $TRIES | xargs -P $NPROC -n1 -I % wine d3dretrace foo.trace

This will run the trace `foo.trace` `TRIES` times, using `NPROC` processes.   With luck, if you bump TRIES and/or NPROC you might be able to make this issues happen more frequently.

**Comment by Evernow** [comment]
> I glanced over those mesa bug reports, and the feeling I get is that these issues are inherently random. So even though the race condition it happens when recording, it might not happen when replaying.
> 
> What I usually try in such circumstances, often with success, is replay the trace over and over again, and in parallel.
> 
> That is, try something like:
> 
> ```
> TRIES=32
> NPROC=2
> seq 1 $TRIES | xargs -P $NPROC -n1 -I % wine d3dretrace foo.trace
> ```
> 
> This will run the trace `foo.trace` `TRIES` times, using `NPROC` processes. With luck, if you bump TRIES and/or NPROC you might be able to make this issues happen more frequently.

Would this still help if it doesn't hang when I was recording the apitrace though? Because that's what is happening here. It hangs when not recording and apitrace, but then I try to record an apitrace it never hangs

**Comment by jrfonseca** [comment]
Oh I see.  I hadn't understood that.  But yes, it's possible it could help.

The slowdown introduced by apitrace when tracing, due to compressing and writing data to disk, might make the issue less likely.

So you could try to record a trace that includes the scene where the hang is likely (e.g., 1 minute worth.)   Then try the above technique to see if you can the hang happen on demain.

Replaying is still slower than the actual game, due to the need of reading the trace from the disc decompressing.  But if you run many times and in parallel, it might even the odds.

It might also help doing

     aptirace repack -brotli in.trace out.trace

This will make the trace smaller, and decompression sill very fast, so it might speed up replaying.

I hope it helps.

**Comment by jrfonseca** [comment]
Also the SpaceEngineers traces are useless.

It seems `dxgi.dll` wasn't intercepted, as the first call is:

    0 D3D11CreateDevice(pAdapter = 0x12ac15e0, DriverType = D3D_DRIVER_TYPE_UNKNOWN, Software = NULL, Flags = 0x0, pFeatureLevels = &D3D_FEATURE_LEVEL_11_0, FeatureLevels = 1, SDKVersion = 7, ppDevice = &0x770c58, pFeatureLevel = &D3D_FEATURE_LEVEL_11_0, ppImmediateContext = &0x8503e0) = S_OK

and the DXGI call that created  `pAdapter = 0x12ac15e0` is nowhere to be seen.

**Comment by Evernow** [comment]
> Oh I see. I hadn't understood that. But yes, it's possible it could help.
> 
> The slowdown introduced by apitrace when tracing, due to compressing and writing data to disk, might make the issue less likely.
> 
> So you could try to record a trace that includes the scene where the hang is likely (e.g., 1 minute worth.) Then try the above technique to see if you can the hang happen on demand.
> 
> Replaying is still slower than the actual game, due to the need of reading the trace from the disk and decompressing it. But if you run many times and in parallel, it might even the odds.
> 
> It might also help doing
> 
> ```
>  aptirace repack -brotli in.trace out.trace
> ```
> 
> This will make the trace smaller, and decompression sill very fast, so it might speed up replaying.
> 
> I hope it helps.

Thank you very much!

Indeed it seems to help, I was able to replay an apitrace and have it hang, even though it did not hang while I was recording it! Thank you!

**Comment by Evernow** [comment]
> Also the SpaceEngineers traces are useless.
> 
> It seems `dxgi.dll` wasn't intercepted, as the first call is:
> 
> ```
> 0 D3D11CreateDevice(pAdapter = 0x12ac15e0, DriverType = D3D_DRIVER_TYPE_UNKNOWN, Software = NULL, Flags = 0x0, pFeatureLevels = &D3D_FEATURE_LEVEL_11_0, FeatureLevels = 1, SDKVersion = 7, ppDevice = &0x770c58, pFeatureLevel = &D3D_FEATURE_LEVEL_11_0, ppImmediateContext = &0x8503e0) = S_OK
> ```
> 
> and the DXGI call that created `pAdapter = 0x12ac15e0` is nowhere to be seen.

Thanks, possibly due to me recording it using DXVK, but sadly did not have a choice because Space Engineers does not open with Wine D3D

**Comment by Evernow** [comment]
> I glanced over those mesa bug reports, and the feeling I get is that these issues are inherently random. So even though the race condition it happens when recording, it might not happen when replaying.
> 
> What I usually try in such circumstances, often with success, is replay the trace over and over again, and in parallel.
> 
> That is, try something like:
> 
> ```
> TRIES=32
> NPROC=2
> seq 1 $TRIES | xargs -P $NPROC -n1 -I % wine d3dretrace foo.trace
> ```
> 
> This will run the trace `foo.trace` `TRIES` times, using `NPROC` processes. With luck, if you bump TRIES and/or NPROC you might be able to make this issues happen more frequently.

Question is there a way to do this where the result is a unified apitrace? Point of this is to have an apitrace that is guaranteed to hang everytime

**Comment by jrfonseca** [comment]
What do you mean by _unified apitrace_?

**Comment by Evernow** [comment]
> What do you mean by _unified apitrace_?

Right now I am in a scenario where playing one trace one time is not enough to reproduce the issue, and AMD devs seem to be having even more troubles. 

Was asking if there's a way to play it long enough to reproduce the issue, and then sent the apitrace that can be replayed that will always hang

**Comment by jrfonseca** [comment]
So IIUC, you'd like a trace that's equivalent to playing an original trace many times repeatedly and in parallel.

While technically possible it would be time consuming to implement and I doubt it would be helpful for the case at and.

Often these issues are inherently random.  There's no guarantee that even if one generates such unified trace that repros 100% on your system, it will repro on another system.  The advantage of the the techinique seq/xargs technique I described above is that every time

The only thing you could try is using the d3dretrace `--loop` option to loop the last frame.  That is, first identify a frame near where the issue happens:

    apitrace dump --grep Present foo.trace
    d3dretrace -S frame foo.trace

and note than the call number of the Present you're interested.  Then do

    apitrace trim --calls 0-123456 -o test.trace foo.trace
    d3dretrace --loop test.trace

apitrace trim command will trim out all after the frame of interest, and d3dretrace will loop continuously that last frame.  Maybe you get luck and it works, but TBH I have doubts.

> AMD devs seem to be having even more troubles.

Which bug/forum is this conversation happening?

As long as AMD devs can repro it, unified trace or not, they should be able to get to the bottom of it.  

If they can't repro at all, then I think you need to start looking for what other external factors might be affecting the odds (like software versions and hardware other than gpu.)
