### ISSUE TITLE
apitrace doesn't trace anything when using a custom loader

### ISSUE THREAD

**Issue by liquid600pgm** [apitrace/apitrace#663]
Or so I think. I recently switched to using my own, custom OpenGL loader, but for some bizarre reason, apitrace does not seem to detect OpenGL running? I don't really know what's going on; the window appears, my program acts (fairly) normally, but no matter what I do, apitrace just doesn't seem to want to work.
I'm using GLFW to create my OpenGL 3.3 context, if that's relevant. The debug context is enabled.

**Comment by jrfonseca** [comment]
I'll need more info to make sense of it.

What do you mean by _custom OpenGL loader_?  How is it different from an ordinary OpenGL application?

What OS is this on?  Windows, Linux, or macOS?

If it's on Windows, sometimes it pays trying the alternative injection method, of copying `opengl32.dll` onto the app's folder as described on https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown#windows

**Comment by liquid600pgm** [comment]
It's on Linux, by *custom* I mean different from the usual GLAD/GLEW.
After a bit of debugging I realized that this is due to the fact I'm using EGL instead of GLX as the backend, so let's consider this as resolved.
