### ISSUE TITLE
Windows binaries depend on Debug MSVC runtime

### ISSUE THREAD

**Issue by AnyOldName3** [apitrace/apitrace#677]
The Windows binaries depend on the Debug variant of the MSVC runtime, so `VCRUNTIME140D.dll`, `MSVCP140D.dll` and `ucrtbased.dll` with the `d` suffix. These aren't included in the MSVC redistributables, and, in fact, Microsoft says not to distribute debug binaries to users here: https://docs.microsoft.com/en-us/cpp/windows/preparing-a-test-machine-to-run-a-debug-executable?view=vs-2019

The result of this is that regular people without Visual Studio installed can't run APITrace, which is a nuisance for me as it's one of the main ways I collect information about issues from users. The solution is to go back to RelWithDebInfo.

**Comment by jrfonseca** [comment]
Thanks for letting me know.

I used to compile the nightly binaries on a in-house Jenkins instance,but I want to decommission it, and rely exclusively on Appveyor.

I'll look into this ASAP.
