### ISSUE TITLE
Cannot download the file apitrace-7.0.20200517-win64.7z :(

### ISSUE THREAD

**Issue by CloudHaze** [apitrace/apitrace#680]
Tried already downloading multiple times using different download managers such Eagle Get, Ninja, J-downloader keep failing in resuming/connect

like 10 times fails or stop downloading at 90% , 92%, 98%  

Can you please upload to mediafire or something?
![fails](https://user-images.githubusercontent.com/19179554/89645697-51568d00-d888-11ea-928f-f72cfca8aef3.png)

PS: I'm from Venezuela and mi internet is so bad, thats why i use Download manager to be able to pause/resume

**Comment by jrfonseca** [comment]
I'm not sure what's going on.  The difficulty I have is that whatever storage I use needs to be something that accepts automatic uploads from AppVeyor, where Apitrace windows builds are being built.  I can't be anything that implies manual intervention.

**Comment by astillich-igniti** [comment]
I guess these download managers open a huge number of connections to download parts of the file simultaneously which the server rightfully rejects.

**Comment by astillich** [comment]
I guess these download managers open a huge number of connections to download parts of the file simultaneously which the server rightfully rejects.

**Comment by jrfonseca** [comment]
I recommend a command line tool like `wget` or `curl`.  Eihter tool allows to resume downloads, but don't attempt to make multiple connections, which might trigger AppVeyor web server to refuse connections.
