### ISSUE TITLE
can anyone help me i want to do an apitrace

### ISSUE THREAD

**Issue by CloudHaze** [apitrace/apitrace#682]
I'm trying to do an apitrace for Torchlight II which i have it on steam....  I put in the game folder a d3d9 made by doitsujin/dvxk vulkan implementation, but for some reason torchlight 2 doesnt open, what i'm doing wrong?

I'm running appitrace32bit binaries 

![help](https://user-images.githubusercontent.com/19179554/89835750-5723cb00-db33-11ea-8371-cbc3cadcf3aa.png)
![torchlight2](https://user-images.githubusercontent.com/19179554/89835786-6b67c800-db33-11ea-8bac-402b80d8b332.png)

**Comment by lawlove** [comment]
Try putting the exe <path>\<executable> in quotes, i.e.
"C:\Program Files (x86\Steam\steamapps\common\Torchlight II\Torchlight2.exe"

**Comment by lawlove** [comment]
"C:\Program Files
(x86)\Steam\steamapps\common\Torchlight II\Torchlight2.exe"

**Comment by lawlove** [comment]
If that doesn't work you might have to play around with the delimiters,
change '\' to '/' or escape them.

**Comment by CloudHaze** [comment]
Oh it worked putting the "" "
But now dunno what to do XD

Looks i tried this> apitrace replay "C:\Program Files (x86)\Steam\steamapps\common\Torchlight II\Torchlight2.exe" i know the game is using d3d9 but for some reason didn't detect, I wanted to record a log file of torchlight II so this way people can help me to figure what is going on on torchlight II with the d3d9
![image](https://user-images.githubusercontent.com/19179554/89838677-dfa56a00-db39-11ea-9f28-c7679777489d.png)

**Comment by lawlove** [comment]
go to the apitrace site to see what arguments you can pass to it. (Or maybe
you can try apitrace /h or -h I forget what the help argument is and don't
have access) but you can pass it the API, I just don't remember what the
argument is. Good luck.

**Comment by lawlove** [comment]
I found the manual - it shows the APIs you can pass
https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown

**Comment by jrfonseca** [comment]
For Steam applications please follow the instructions on https://github.com/apitrace/apitrace/wiki/Steam#windows
