### ISSUE TITLE
D3D8 CreateVertexBuffer FVF displayed incorrectly

### ISSUE THREAD

**Issue by AnyOldName3** [apitrace/apitrace#684]
`IDirect3DDevice8::CreateVertexBuffer`'s FVF (Flexible Vertex Format) parameter gets helpfully decomposed into FVF flags, however:
* If `D3DFVF_XYZB3` is used, it's displayed as `D3DFVF_XYZ | D3DFVF_XYZB2` as `D3DFVF_XYZ = 0x002`, `D3DFVF_XYZB2= 0x008`, and `D3DFVF_XYZB3= 0x00a`. Only one of the `XYZ` and `XYZBn` options is supposed to be used at once, so some of them have overlapping bits.
* If `D3DFVF_TEX2` is used, it's displayed as `0x200`.

Also, these vertex format flags can be passed as the handle to `IDirect3DDevice8::SetVertexShader` to configure fixed-function vertex processing, and in that case, they're just displayed as a number. That was actually how I realised something weird was happening with the display of the `CreateVertexBuffer` argument.

**Comment by AnyOldName3** [comment]
I just got a chance to look at this again, and it seems there are still some problems. These include:
* `0x100` is displayed instead of `D3DFVF_TEX1`.
* As before, if `D3DFVF_XYZB3` is used, it's displayed as `D3DFVF_XYZ | D3DFVF_XYZB2`.
* `SetVertexShader` still just shows numbers, e.g. `338` instead of its constituents.

**Comment by jrfonseca** [comment]
Did you try the [latest binaries](http://apitrace.github.io/#download)?

**Comment by AnyOldName3** [comment]
It turns out I'd not used up-to-date binaries to actually record the trace and now I've looked at the implementation, it's pretty easy that that's the stage at which the conversion's done. Now I've had another go with everything updated, it's working.

It *might* be worth considering if there's some way to make the change retroactively apply to old traces, or maybe just add a warning that FVFs might be decoded incorrectly when loading an old trace if there's a version field in there.
