### ISSUE TITLE
Cannot replay TES4:Oblivion  trace  CreateDeviceEX is failing with D3DERR_INVALIDCALL

### ISSUE THREAD

**Issue by llde** [apitrace/apitrace#687]
Hi, as title when I try to replay a captured trace from TES4:Oblivion  I got an error with device creation:
8358 @0 IDirect3D9Ex::CreateDeviceEx(this = 0x5954700, Adapter = D3DADAPTER_DEFAULT, DeviceType = D3DDEVTYPE_HAL, hFocusWindow = 0xa207fe, BehaviorFlags = D3DCREATE_MULTITHREADED | D3DCREATE_PUREDEVICE | D3DCREATE_HARDWARE_VERTEXPROCESSING, pPresentationParameters = &{BackBufferWidth = 1920, BackBufferHeight = 1080, BackBufferFormat = D3DFMT_X8R8G8B8, BackBufferCount = 1, MultiSampleType = D3DMULTISAMPLE_NONE, MultiSampleQuality = 0, SwapEffect = D3DSWAPEFFECT_DISCARD, hDeviceWindow = 0xa207fe, Windowed = FALSE, EnableAutoDepthStencil = TRUE, AutoDepthStencilFormat = D3DFMT_D24S8, Flags = 0x0, FullScreen_RefreshRateInHz = 0, PresentationInterval = D3DPRESENT_INTERVAL_ONE}, pFullscreenDisplayMode = &{Size = 24, Width = 1920, Height = 1080, RefreshRate = 0, Format = D3DFMT_X8R8G8B8, ScanLineOrdering = D3DSCANLINEORDERING_PROGRESSIVE}, ppReturnedDeviceInterface = &0x5a57be0) = D3D_OK
8358: warning: failed with 0x8876086c (D3DERR_INVALIDCALL): 

Strangely enough ths happen only in native D3d9. If I load apitrace with DXVK the trace load succesfully (albeit showing graphical glitches in text, but this only happen from traces captured from Windows (both native D3d9 and dxvk), while I don't get it from dxvk traces captured from wine).
This beheviours happen even if the trace was captured with DXVK. 
Of course, with the same exact parameters, CreateDeviceEx fully start.
Note Oblivion doesn't by default use D3d9Ex devices, but it was introduced to fix Alt-Tabbing issues by Oblivion Display Tweaks OBSE plugin.
The issue seems focused to D3d9EX devices, as if I use the normal device all works in apitrace. (And also repalying the trace with DXVK doesn'0t show text corruption anymore)
apitrace version: 7.0.20200517

https://drive.google.com/file/d/1zj6crDJBAYoSfAkcTGPO8t-K3b488Fy2/view?usp=sharing  Trace showing the issue
EDIT: ok the version I downlaoded wasn't the last version.  I downloaded the 9.0 version and it is still failing

**Comment by jrfonseca** [comment]
Sorry for the delay.

I just tried your trace on native Windows 10 (10.0.19042.928) and it worked fine. 

I suspect this got fixed with f1c0b0567aba12eaa05821a38f203c2186ebb350.  Please retry with the [latest binaries](http://apitrace.github.io/#download).

Feel free to reopen if the issue persists.
