### ISSUE TITLE
OpenGL ES profiling support

### ISSUE THREAD

**Issue by ammen99** [apitrace/apitrace#689]
Hi all,

I have an OpenGL ES application that I want to profile. I have read that I need `--pcpu --pgpu --ppd` however:

- `--pgpu` requires `GL_ARB_timer_query` which is not available on OpenGL ES at all.
- `--ppd` requires `GL_ARB_occlusion_query` which is not available on OpenGL ES either.

Am I missing something or this means that the only thing possible to measure for OpenGL ES is the CPU time? (with `--pcpu`)

**Comment by jrfonseca** [comment]
Sorry for the silence.  I really haven't been able to keep up with the inflow of issues and PRs on Apitrace.  It's probably too late to be of assistance, but better late than never...

It looks you're right.  OpenGL ES is missing those extensions, so it doesn't work.

ES doesn't seem to be anything resembling `GL_ARB_occlusion_query`.  [`EXT_occlusion_query_boolean`](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_occlusion_query_boolean.txt) only covered binary occlusion, so it can't be used for profiling.

But it does have [`EXT_disjoint_timer_query`](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_disjoint_timer_query.txt).  So apitrace could be enhanced to use this ES extension where available.

It's probably not a big task, but I'm afraid I don't have the time to pursuit nevertheless.

**Comment by jrfonseca** [comment]
For completeness, another solution would be to run the trace with desktop GL, as ES traces should run well if the `GL_ARB_ES2_compatibility`/`GL_ARB_ES3_compatibility` extensions are supported.

**Comment by lfrb** [comment]
I'm working on adding support using [EXT_disjoint_timer_query](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_disjoint_timer_query.txt). I have two related questions:

1) What should we do if a disjoint operation occurred (meaning the query resulting timestamp is not accurate and should not be used). Should we just not write anything or should we write `#INVALID`, `#DISJOINT` or whatever in the profiling log?

2) According to the spec, we should wait for the query result to be available before reading it, but I'm not seeing it in the code. Is it just a small mistake or is there a reason? (it's part of all three extensions: `EXT_timer_query`, `ARB_timer_query` and `EXT_disjoint_timer_query`)

```
        while (!available) {
            glGetQueryObjectiv(queries[1], GL_QUERY_RESULT_AVAILABLE, &available);
        }
```

**Comment by jrfonseca** [comment]
I believe currently we ignore disjoint timings across all APIs, and hope it happens rarely in practice.   We could try to percolate by using NANs for timings or something like that, but that would require more thought and testing, and I'm not sure it would yield  better experience.   A bit like CPU profiling, some degree of uncertainty is always to be expected anyway. 

My understanding is that `QUERY_RESULT_EXT` will _sync_, ie, wait until the result is available.  `GL_QUERY_RESULT_AVAILABLE` is used when the app wants to avoid those synchronizations, and defer the  `QUERY_RESULT_EXT` when it knows for sure it won't sync.

**Comment by lfrb** [comment]
I think you are that uncertainty is indeed expected, so I went with the middle ground of adding a new OpenGL metric in case the user care about the disjoint property itself. I don't think it makes sense to pollute the log with that info when not explicitly requested, so I didn't add anything when profiling is enabled through "-pgpu"

You are right about the `QUERY_RESULT` being synchronous, I misunderstood the spec at first.
