### ISSUE TITLE
Texture dumping is unsupported on OpenGL ES

### ISSUE THREAD

**Issue by jrmuizel** [apitrace/apitrace#70]
Neither glGetTexImage nor glGetTexLevelParameteriv exist on OpenGL ES. We'll need to do something else to get the texture data, like remember it from when we created the texture.

This would help with issue #2 as well.

**Comment by leye0** [comment]
Because regardless of the large amount of data it represents, debugging data is something programmers are doing from time to time, that would be nice.

**Comment by jrfonseca** [comment]
> Because regardless of the large amount of data it represents, debugging data is something programmers are doing from time to time, that would be nice.

This issue has been fixed -- apitrace supports dumping textures on OpenGL ES has been implemented (not via glGetTexImages, but via glReadPixels).

@leye0, aren't they working for you?

**Comment by leye0** [comment]
Isn't that only dump rendered data? Maybe I'm not searching at the right place. Let's say I'm initiating my application, I've made a texture from GlTexImage2D and afterwhile want to see if it exists in the OpenGL context? Like checking some pixels to see if it is what I uploaded?

**Comment by jrfonseca** [comment]
No, that should work fine. We blit the whole the texture level to a _temporary_ FBO, and read the pixels from the FBO.  That is, the data dumped, should match the texture.
