### ISSUE TITLE
Recent Launches list doesn't work on Windows

### ISSUE THREAD

**Issue by AnyOldName3** [apitrace/apitrace#703]
The *Recent Launches* list remains empty for me on Windows, however, it's worked for me on Ubuntu.

I've tracked down the problem and resolved it with https://github.com/apitrace/apitrace/pull/702

**Comment by jrfonseca** [comment]
https://github.com/apitrace/apitrace/pull/702 merged.

**Comment by jrfonseca** [comment]
Thanks!
