### ISSUE TITLE
Cannot build on M1 ... 

### ISSUE THREAD

**Issue by krogovin** [apitrace/apitrace#711]
Hi,

 I have Homebrew working on the M1 (qt5 is installed for example), and the build of apitrace almost completes, but fails at the very end with:
 

> Undefined symbols for architecture arm64:
>   "_png_init_filter_functions_neon", referenced from:
>       _png_read_filter_row in libpng_bundled.a(pngrutil.c.o)
> ld: symbol(s) not found for architecture arm64

is there a way to inform the build process to use the system libpng? I have them on homebrew:

> ls -al /opt/homebrew/lib/libpng*
> lrwxr-xr-x  1 kevinrogovin  admin  36 Jan 28 20:59 /opt/homebrew/lib/libpng.a@ -> ../Cellar/libpng/1.6.37/lib/libpng.a
> lrwxr-xr-x  1 kevinrogovin  admin  40 Jan 28 20:59 /opt/homebrew/lib/libpng.dylib@ -> ../Cellar/libpng/1.6.37/lib/libpng.dylib
> lrwxr-xr-x  1 kevinrogovin  admin  45 Jan 28 20:59 /opt/homebrew/lib/libpng16.16.dylib@ -> ../Cellar/libpng/1.6.37/lib/libpng16.16.dylib
> lrwxr-xr-x  1 kevinrogovin  admin  38 Jan 28 20:59 /opt/homebrew/lib/libpng16.a@ -> ../Cellar/libpng/1.6.37/lib/libpng16.a
> lrwxr-xr-x  1 kevinrogovin  admin  42 Jan 28 20:59 /opt/homebrew/lib/libpng16.dylib@ -> ../Cellar/libpng/1.6.37/lib/libpng16.dylib

**Comment by jrfonseca** [comment]
Try passing `-DENABLE_STATIC_EXE=1` to cmake.  It should force the bundled zlib and png to be used.

**Comment by jrfonseca** [comment]
> is there a way to inform the build process to use the system libpng?

Sorry, please ignore my previous reply, I interpreted your question the other way around.

No, there's no way to do that on macOS.

I've modified `CMakeLists.txt` to set `PNG_ARM_NEON_OPT=0` in d2c2bba731a2d1b299dbb23bdaeb1c4f40463ca7. Hopefully it fixes the issue without requiring local changes.
