### ISSUE TITLE
glVertexAttribPointer calls are not recorded

### ISSUE THREAD

**Issue by Desperado17** [apitrace/apitrace#717]
This problem arises for me on Ubuntu 18.04 with the preinstalled apitrace (7.1) as well as the current master.
The trace does not seem to capture calls to glVertexAttribPointer. I cannot see them neither in qapitrace or in apitrace dump.

GLES 3.2 application.

**Comment by jrfonseca** [comment]
`glVertexAttribPointer` calls are treated specially, as explained in https://github.com/apitrace/apitrace/blob/master/docs/BUGS.markdown#tracing

In short, when VBOs aren't used, those calls are only emitted in the trace right before the `glDraw*` calls.

Could this be what you're seeing?

**Comment by Desperado17** [comment]
I try to track down a VRAM resource leak that might be the result of the internal reference count of VBOs never becoming 0 due to being still bound in a VAO. For that purpose, I manually set the bindings of unused VAOs to 0 using glVertexAttribPointer. Since the VAOs are not used in a drawcall at the moment, I'm not sure when the glVertexAttribPointer calls are supposed to appear in the trace according to your rules.

Can you tell me if the vsize_start, vsize_dura, rss_start, rss_dura parameters are documented somewhere btw?

**Comment by jrfonseca** [comment]
You might be able to do what you want (record all `glVertexAttribPointer` calls) if you apply this patch:

```diff
diff --git a/wrappers/gltrace.py b/wrappers/gltrace.py
index 760ba077..41614358 100644
--- a/wrappers/gltrace.py
+++ b/wrappers/gltrace.py
@@ -405,7 +405,7 @@ class GlTracer(Tracer):
         # Defer tracing of user array pointers...
         if function.name in self.array_pointer_function_names:
             print('    GLint _array_buffer = _glGetInteger(GL_ARRAY_BUFFER_BINDING);')
-            print('    if (!_array_buffer) {')
+            print('    if (!_array_buffer && false) {')
             print('        static bool warned = false;')
             print('        if (!warned) {')
             print('            warned = true;')
```

Another alternative is to bind a dummy VBO instead of zero.  Is probably better idea, as it has less side effects.

> Can you tell me if the vsize_start, vsize_dura, rss_start, rss_dura parameters are documented somewhere btw?

It comes from Linux /proc, through procps libraries.  See 4f9982f5ec3dccae65d5a49dfd5a81b9737d90cd

**Comment by Desperado17** [comment]
Ok, so they aren't related to the VRAM usage, right? Is there a way to track the VRAM usage or cumulative OpenGL object size in apitrace?

**Comment by jrfonseca** [comment]
Right, it's CPU virtual memory, not VRAM.

If you're using NVIDIA you could try using [GL_NVX_gpu_memory_info](https://www.khronos.org/registry/OpenGL/extensions/NVX/NVX_gpu_memory_info.txt). It's not integrated into apitrace, but you could easily integrate into your application.

You could try, for example, call it before/after destroying a VBO, and assert if its value doesn't change.  But unfortunately this counts total VRAM, not process, so it might not be reliable enough for it.

Another thing you could consider is modifying https://github.com/apitrace/apitrace/blob/master/scripts/leaks.py to hunt for this leak.

**Comment by gerddie** [comment]
I like to add in that mesa also supports  GL_NVX_gpu_memory_info and [ATI_meminfo](https://www.khronos.org/registry/OpenGL/extensions/ATI/ATI_meminfo.txt), maybe not on all drivers, but at least on Radeon r600 and radeonsi,

**Comment by Desperado17** [comment]
Is there any extension that allows this on a per process basis?

**Comment by jrfonseca** [comment]
If you have NVIDIA you can use [`nvidia-smi`](https://stackoverflow.com/a/35765856).  NVIDIA has an API for this too.

I know of no GL extension for this unfortunately.

**Comment by Desperado17** [comment]
Now THIS looks useful.
