### ISSUE TITLE
Draw calls don’t get recorded with libepoxy master

### ISSUE THREAD

**Issue by linkmauve** [apitrace/apitrace#721]
This regression is also tracked here: https://github.com/anholt/libepoxy/issues/240

Since I updated epoxy, programs using it (such as `gtk4-demo`) are missing draw calls (such as `glDrawArrays()`) from the traces, while other calls are still present, resulting in only black frames.

**Comment by jrfonseca** [comment]
Presume this is fixed, since upstream issue is closed.
