### ISSUE TITLE
CMake 3.20 compatibility

### ISSUE THREAD

**Issue by adriaandegroot** [apitrace/apitrace#727]
One change in CMake 3.20 is that `TestBigEndian` is now handled internally by CMake. Previously, this called out to some compiler tests, and eventually got to `CHECK_TYPE_SIZE()`, which **incidentally** detects `HAVE_STDINT_H`. This is used in libbacktrace (the bundled version, at least, that ends up in FreeBSD packaging). 

I now apply this to the 9.0 release (again: this is for FreeBSD packaging, and it **looks** like it would apply upstream, but maybe it's already mitigated elsewhere):

```
@@ -408,6 +407,10 @@
 if (HAVE_BIGENDIAN)
     add_definitions (-DHAVE_BIGENDIAN)
 endif ()
+# CMake 3.20 doesn't do the tests internally in TestBigEndian
+# that end up setting HAVE_STDINT_H and similar.
+include(CheckTypeSize)
+CHECK_TYPE_SIZE("unsigned short" CMAKE_SIZEOF_UNSIGNED_SHORT LANGUAGE C)
 
 # Force certain components to always be built as release
 macro (force_release_build)
```

**Comment by jrfonseca** [comment]
Thanks for letting me know.  Indeed libbactrace depends on `HAVE_STDINT_H` define.

I think it's better to be explicit, and check `stdint.h` directly, like
```cmake
include (CheckIncludeFile)
check_include_file ("stdint.h" HAVE_STDINT_H)
```
that said, aptirace already depends upon `stdint.h`all over the place, so we could merely do
```cmake
set (HAVE_STDINT_H YES)
```

I'll commit one or the other shortly.

I should also create a new release.  It's been too long.
