### ISSUE TITLE
Windows binaries depend on debug Qt DLLs but don't bundle them

### ISSUE THREAD

**Issue by AnyOldName3** [apitrace/apitrace#731]
This makes the binary builds unable to do anything GUI-related.

**Comment by jrfonseca** [comment]
Thanks for letting me know.

This is baffling.  Per https://ci.appveyor.com/project/jrfonseca/apitrace/branch/master/job/g7ivyk5qhnwt2kbe RelWithDebInfo binaries are being built.  It's not obvious why the debug Qt DLLs are being depended on, nor why they aren't being packaged. 

I believe this was working before.  It might be a regression with the recent change to download Qt as opposed to use Qt from Appveyor's images.

I'll keep digging.

**Comment by jrfonseca** [comment]
I believe this is fixed on master, through 852ead1d8d97f9b6c3957d60c7ed69ec585e4937 .

I'll need to crossport to 10.0 release later.

**Comment by AnyOldName3** [comment]
I tried downloading the latest binaries, but Chrome decided to block them because it thought they were malware. After trying again with Firefox, the issue appears to be resolved.
