### ISSUE TITLE
Build error, unclear reason

### ISSUE THREAD

**Issue by batesj** [apitrace/apitrace#733]
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo
-- Using bundled SNAPPY
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found suitable version "1.2.11", minimum required is "1.2.6") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home...

loading initial cache file build/
CMake Error: Error processing file: build/
-- Using bundled SNAPPY
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found suitable version "1.2.11", minimum required is "1.2.6") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- libdwarf not found. Disabling Backtrace support.
-- Configuring incomplete, errors occurred!

It's unclear from the build logs which errors are ok (like libdwarf not found) and which are blockers:

Determining if the pthread_create exist failed with the following output:
Determining if the function pthread_create exists in the pthreads failed with the following output:
Determining if the function getexecname exists failed with the following output:
Determining if the include file dwarf.h exists failed with the following output:
Determining if the include file libdwarf/dwarf.h exists failed with the following output:

**Comment by jrfonseca** [comment]
Make sure you update git submodules.  See https://github.com/apitrace/apitrace/pull/730

I'll update CMakeLists.txt to explain this automatically.
