### ISSUE TITLE
Vertex attribute dumping regressed

### ISSUE THREAD

**Issue by jrfonseca** [apitrace/apitrace#751]
@10110111 , https://github.com/apitrace/apitrace/pull/745 caused a regression.

Take [tri_glsl_core.zip](https://github.com/apitrace/apitrace/files/6790238/tri_glsl_core.zip), obtained from https://github.com/apitrace/apitrace-tests/blob/master/apps/gl/tri_glsl_core.cpp

Running
```
glretrace -D 9740 tri_glsl_core.trace | sed -n -e '/^  "buffers"/,/^  }/p'
```
used to produce
```json
  "buffers": {
    "vertices": [{
        "color": [0.8, 0, 0],
        "pos": [-0.9, -0.9]
      },
      { 
        "color": [0, 0.9, 0],
        "pos": [0.9, -0.9]
      },
      { 
        "color": [0, 0, 0.7],
        "pos": [0, 0.9]
      }
    ]
  },
```
but now it produces
```json
  "buffers": {
    "vertices": [{
        "color": [0.8, 0, 0],
        "pos": [-0.9, -0.9]
      },
      { 
        "color": [0, 0.9, 0],
        "pos": [0.9, -0.9]
      }
    ]
  },
```

That is, one less vertex element.  The sample draws a triangle, so there's no doubt it should dump 3 vertices not too.

Can you please fix this?

**Comment by 10110111** [comment]
There appears to be some confusion between attribute size and array stride, see the beginning [here](https://github.com/apitrace/apitrace/blob/d4c352f1425ef4c7d26b164e2108202e9d06a02e/retrace/glstate_shaders.cpp#L991). The code seems to rely on there being only one attribute per stride, and thus it computes attribute count based on this.

I suppose this should fix it:
```diff
diff --git a/retrace/glstate_shaders.cpp b/retrace/glstate_shaders.cpp
index 99e162ab..24b8e03c 100644
--- a/retrace/glstate_shaders.cpp
+++ b/retrace/glstate_shaders.cpp
@@ -988,11 +988,11 @@ dumpVertexAttributes(StateWriter &writer, Context &context, GLint program)
         }
 
         attrib.desc = desc;
-        GLsizei attribSize = attrib.desc.arrayStride;
+        GLsizei attribSize = attrib.desc.numCols * attrib.desc.colStride;
 
         if (stride == 0) {
             // tightly packed
-            stride = attribSize;
+            stride = attrib.desc.arrayStride;
         }
 
         attrib.offset = offset;
```

Does it look OK? If yes, I'll make a PR.

**Comment by jrfonseca** [comment]
Looks good.  Please proceed with PR. Thanks
