### ISSUE TITLE
__libc_dlopen_mode and __libc_dlsym gone in glibc-2.33.9000+

### ISSUE THREAD

**Issue by manisandro** [apitrace/apitrace#756]
See [1]. On Fedora 35, apitrace fails to build with undefined references to `__libc_dlopen_mode` and `__libc_dlsym`. 

[1] https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/W5VILZ23RXACVPLKASR4NTHSX6DC4KCM/

**Comment by kraj** [comment]
I am seeing this with yocto + glibc-trunk as well, these symbols were clearly marked GLIBC_PRIVATE since they were only meant for glibc's internal functioning wth libdl, libdl is now gone and merged into libc these functions therefore are no longer needed and removed thusly. apitrace should not have violated the glibc private APIs.

**Comment by manisandro** [comment]
Here some feedback from fedora-devel:

> According to the comments in https://github.com/apitrace/apitrace.git file wrappers/dlsym.cpp ,
> the purpose is "to obtain the true dlsym" by explicit lookup in libdl.so.2, which is a library
> that no longer exists in glibc-2.34, having been combined into libc.so itself.

> The only legitimate way to find "the true dlsym" is to trust dl_iterate_phdr (/usr/include/link.h)
> and call it, dig through all the Dynamic sections to find all the symbols named 'dlsym',
> then choose the one you want: perhaps by being defined in a file whose DT_SONAME is "libc.so"
> and having symbol version GLIBC_2.2.5 .

**Comment by jrfonseca** [comment]
@manisandro , thanks for letting me know.

@kraj , yep, we brought this upon ourselves, but it's impossible to create reliable shared objects interposers (specially when when one needs to defence against other interposers, such as Steam Overlay) without getting hands dirty and reaching out to internals.

It sucks I don't have much time to look into this.

My suggestion for a quick fix is to modify the `#if` conditional in https://github.com/apitrace/apitrace/blob/master/wrappers/dlsym.cpp#L37 to skip when GLIBC version is 2.34 or more.

This means that using apitrace with Steam Overlay interposer won't work, but other usages should work fine, and one can always manually disable Steam Overlay.

**Comment by jrfonseca** [comment]
Something like this should do the trick:

```diff
diff --git a/wrappers/dlsym.cpp b/wrappers/dlsym.cpp
index 5ab8465b..5369af35 100644
--- a/wrappers/dlsym.cpp
+++ b/wrappers/dlsym.cpp
@@ -34,7 +34,7 @@
 #include "os.hpp"
 
 
-#if defined(__GLIBC__) && !defined(__UCLIBC__)
+#if defined(__GLIBC__) && !defined(__UCLIBC__) && __GLIBC__ == 2 && __GLIBC_MINOR__ < 34
 
 
 #include <dlfcn.h>
```
