### ISSUE TITLE
GUI build fails when BUILD_TESTING is disabled

### ISSUE THREAD

**Issue by armeenm** [apitrace/apitrace#779]
A build attempted with the CMake flag `-DBUILD_TESTING=OFF` will result in
```
CMake Error at gui/CMakeLists.txt:111 (target_link_libraries):
  Cannot specify link libraries for target "qubjson_test" which is not built
```
https://github.com/apitrace/apitrace/blob/764c9786b2312b656ce0918dff73001c6a85f46f/gui/CMakeLists.txt#L111
since earlier, `qubjson_test` is predicated on `BUILD_TESTING`:
https://github.com/apitrace/apitrace/blob/13b1b1aae4ee9acb2e2e92a9d7aaf214dc7f7559/gui/CMakeLists.txt#L16-L19

**Comment by jrfonseca** [comment]
Thanks.
