### ISSUE TITLE
Website: CodeXL link is dead

### ISSUE THREAD

**Issue by SmallJoker** [apitrace/apitrace#780]
I cannot open an issue on https://github.com/apitrace/apitrace.github.io, hence I'm creating it here.

> Professional compute content is no longer on GPUOpen.

https://gpuopen.com/compute-product/codexl/

According to Wikipedia, the functionalities were integrated into AMD uProf, which is located here: https://developer.amd.com/amd-uprof/
This website links to the User Guide which is important for setup and usage instructions.

EDIT: Alternatively there's the Radeon GPU Profiler: https://radeon-gpuprofiler.readthedocs.io/en/latest/ (only for amdgpu-pro drivers)

**Comment by jrfonseca** [comment]
Thanks.
