### ISSUE TITLE
leaks: doesn't support Unicode in shaders

### ISSUE THREAD

**Issue by ubitux** [apitrace/apitrace#781]
A fragment shader containing an unicode character such as "π" (typically in a comment) leads to the following traceback with `apitrace leaks`:

```
File "/usr/bin/../lib/apitrace/scripts/leaks.py", line 163, in <module>
  main()
File "/usr/bin/../lib/apitrace/scripts/leaks.py", line 159, in main
  detector.parse()
File "/usr/bin/../lib/apitrace/scripts/leaks.py", line 52, in parse
  unpickle.Unpickler.parse(self)
File "/usr/lib/apitrace/scripts/unpickle.py", line 251, in parse
  while self.parseCall():
File "/usr/lib/apitrace/scripts/unpickle.py", line 256, in parseCall
  callTuple = pickle.load(self.stream)
UnicodeDecodeError: '\''ascii'\'' codec can'\''t decode byte 0xcf in position 1833: ordinal not in range(128)'
```

**Comment by jrfonseca** [comment]
`leaks.py` hasn't received much love.  I haven't used myself for a long time.

This particular bug is probably due to Python 2->3 migration and is probably easy to fix.

Could you please provide the trace that triggers the bug?

**Comment by ubitux** [comment]
Sure. Here are 3 traces:
- Normal case with valid unicode characters [fragment-unicode.trace.gz](https://github.com/apitrace/apitrace/files/8730751/fragment-unicode.trace.gz)
- Naughty combination of unicode [fragment-naughty.trace.gz](https://github.com/apitrace/apitrace/files/8730750/fragment-naughty.trace.gz) -- with text from https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt inserted into the fragment (the string is still composed of valid unicode)
- Edge case with invalid unicode (could be a different encoding, but in this case it's an arbitrary `\x80\x81` sequence): [fragment-invalid.trace.gz](https://github.com/apitrace/apitrace/files/8730749/fragment-invalid.trace.gz)

Every trace is valid since the text is scoped into a comment.

**Comment by jrfonseca** [comment]
Thank you.  I pushed a workaround for now.  It's not a comprehensive fix, but it should be enough for the needs for leaks and other CLI tools which depend on Python pickling.
