### ISSUE TITLE
release 10.1 / 11

### ISSUE THREAD

**Issue by okias** [apitrace/apitrace#784]
Hello @jrfonseca,

I know your time limited, but when you have a moment, release of new version for packages to have something to catch on would be great.

Thank you!

**Comment by gerddie** [comment]
Hi @jrfonseca in principle I could help with making new releases (if that involves more than just adding a tag), however, since I don't have a MS Windows installation, I'd need to know how you create these release archives? Is is done by using travis?

**Comment by jrfonseca** [comment]
Thanks for the offer, @gerddie.  It _should_ just be a matter of pushing a tag.  The Windows binaries should be built and uploaded automatically by AppVeyor.  But it does happen on occasion things fail for one reason or another.  I actually just pushed `11.0` after merging one last bug fix PR.  Hopefully that's all to it.  But if there's more to it, I'll reach out to you.  I'm happy you do it next time around.

**Comment by jrfonseca** [comment]
The appveyor github token had expired due to lack of use.  But it's fixed now.

New release out on https://github.com/apitrace/apitrace/releases/tag/11.0

Thanks for your patience
