### ISSUE TITLE
up to discussion: name glx correctly in options and help

### ISSUE THREAD

**Issue by okias** [apitrace/apitrace#797]
```
    -a, --api=API       specify API to trace (gl or egl);
                        default is `gl`
```
- should be `glx` or `egl` 
- for compatibility reason to keep gl

Does that make sense to make the option less confusing for newcomers?

**Comment by jrfonseca** [comment]
By that account, it could also be `wgl`, `cgl`.    I think it might confuse than inform, because there are effectively only two options:
1. Originally there was only OpenGL (with its GLX/WGL/CGL/etc window specific counterparts). 
2. Then came EGL which tried to be cross-OS.

**Comment by okias** [comment]
oh right, would you mind I find sent MR with extending help text a bit with verbose explanation gl means "GLX/WGL/CGL/etc window specific counterparts"? (since I noticed in real-life, that user got a bit confused when trying to understand the settings, since he took gl literally just as GL.
