### ISSUE TITLE
Grand Theft Auto V can't load with apitrace dll's attached

### ISSUE THREAD

**Issue by kassindornelles** [apitrace/apitrace#817]
I know this is non-helpful-issue since i dont know the technical aspects of apitrace, but i wanted to let you guys know anyway...

On both Proton (Linux) and Windows the game crashes when we trying to load with the necessary .dll files to apitrace (dxgitrace.dll, dxgi.dll, d3d11.dll)

The game is having issues on proton and that's why different people are trying to apitrace with no luck.
see https://github.com/ValveSoftware/Proton/issues/37

Maybe is anti-debug function or maybe just an apitrace issue, we dont know yet.

**Comment by jrfonseca** [comment]
There could be many things going wrong, including anti debugging as mentioned.

I don't have access to the game or time to pursue this.

On Windows, I recommend trying the following while tracing:
- running [DebugViewer](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) and capture the los
- invoke the game inside https://github.com/jrfonseca/drmingw#catchsegv to see the stack backtrace

These might provide further clues.
