### ISSUE TITLE
Appveyor latest Win downloads broken?

### ISSUE THREAD

**Issue by oscarbg** [apitrace/apitrace#818]
Hi,

trying to obtain the lastest prebuilt apitrace for Windows..
the link:
https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-latest-win64.7z?branch=master&pr=false&job=msvc64
fails with:
{"message":"Artifact not found or access denied."}
win32 build also same issue (https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-latest-win32.7z?branch=master&pr=false&job=msvc32)
at least we have the github releases:
https://github.com/apitrace/apitrace/releases/tag/11.1
altough a little older..
it's my problem or Appveyor links are broken for all?

thanks..

**Comment by jrfonseca** [comment]
I think https://github.com/apitrace/apitrace/pull/801 broke binaries, as master builds no longer have "latest".  I'll need to partially revert that.

**Comment by okias** [comment]
Appveyor uses `1.1.8` instead of `latest` https://ci.appveyor.com/project/jrfonseca/apitrace/builds/44742082/job/jqco4c5vb18gu26e

It seems to guess the value from `thirdparty/snappy.cmake` and line
```
project (Snappy VERSION 1.1.8 LANGUAGES C CXX)
```
?

**Comment by okias** [comment]
@oscarbg as workaround, I think you can use https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-1.1.8-win64.7z?branch=master&pr=false&job=msvc64

**Comment by oscarbg** [comment]
@okias thanks will use that in the meanwhile.... but seems the download link ( https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-1.1.8-win64.7z?branch=master&pr=false&job=msvc64 ) is broken also for me similarly as reported initially..
suspecting blocked by region? I'm in Spain..

**Comment by oscarbg** [comment]
yep now works! thanks..

**Comment by jrfonseca** [comment]
BTW, I'm considering abandoning AppVeyor altogether.

The main reason for continuing using AppVeyor was that GitHub actions doesn't make it easy to download latest artifacts (there's no simple URL.)  But I managed to write a script that uses GitHub REST API to do the same and uploads the binaries to https://people.freedesktop.org/~jrfonseca/apitrace/

I'll keep both AppVeyor and GitHub for a while until I'm satisfied all's solid.  Then, unless there are any objections, I'll drop AppVeyor.

**Comment by oscarbg** [comment]
makes sense, thanks for explanation..
