### ISSUE TITLE
not comprehensible error instead of "not found $binary"

### ISSUE THREAD

**Issue by okias** [apitrace/apitrace#823]
apitrace: 11.1

When running `apitrace` on Linux, when `d3dcretrace.exe` is not found, it returns this error, which doesn't say much about the fact that it didn't find `d3dretrace.exe`.
```
qapitrace Heaven.trace
QSocketNotifier: Can only be used with threads started with QThread
Loading: "Heaven.trace"
Running: "wine" "d3dretrace.exe" "-D" "14228" "--dump-format" "ubjson" "Heaven.trace"
ASSERT: "0" in file ./gui/qubjson.cpp, line 284
[1]    23839 IOT instruction
```

**Comment by jrfonseca** [comment]
Weird.  I don't get this error here.

What exactly is the stdout of running `"wine" "d3dretrace.exe" "-D" "14228" "--dump-format" "ubjson" "Heaven.trace"`  on your system? Mine is empty.

One difficulty here is that the stdout parsing happens concurrently, hence the exit code is not known when checking the state.

A solution here would be for qapitrace to first make a trial run of `wine d3dretrace` without further options to ensure both WINE and d3dretrace are present and in working order.

**Comment by jrfonseca** [comment]
I fixed the misleading error message with https://github.com/apitrace/apitrace/commit/f8b94fc135544766665e190803dc8b8d9b9c1dad.

Now it will say _Process exited with non zero exit code._   Message could be better, but at least better than before, as it won't crash.
