### ISSUE TITLE
apitrace doesn't know GL_COMPUTE_WORK_GROUP_SIZE

### ISSUE THREAD

**Issue by okias** [apitrace/apitrace#832]
When tracing Tellusim Starwars demo I got
```
$ apitrace trace ./ts_executor.x64 -name starwars -gl
...
apitrace: warning: _gl_param_size: unknown GLenum 0x8267
...
```

**Comment by okias** [comment]
Not sure which type should I use for array ( https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetProgram.xhtml ) since we have only simple types to choose from.

**Comment by jrfonseca** [comment]
This should do the trick:
```diff
diff --git a/specs/glparams.py b/specs/glparams.py
index 980e38df..dd20751d 100644
--- a/specs/glparams.py
+++ b/specs/glparams.py
@@ -998,7 +998,7 @@ parameters = [
     ("glGet",  I,      1,      "GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS"),       # 0x8264
     ("glGet",  I,      1,      "GL_MAX_COMPUTE_ATOMIC_COUNTERS"),      # 0x8265
     ("glGet",  I,      1,      "GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS"),  # 0x8266
-    ("",       X,      1,      "GL_COMPUTE_WORK_GROUP_SIZE"),  # 0x8267
+    ("glGetProgram",   I,      3,      "GL_COMPUTE_WORK_GROUP_SIZE"),  # 0x8267
     ("",       X,      1,      "GL_DEBUG_TYPE_MARKER"),        # 0x8268
     ("",       X,      1,      "GL_DEBUG_TYPE_PUSH_GROUP"),    # 0x8269
     ("",       X,      1,      "GL_DEBUG_TYPE_POP_GROUP"),     # 0x826A
```

Can you confirm this works for you?  I'll push if so.

**Comment by okias** [comment]
@jrfonseca works as expected. Well, second thing will be Tellusim engine killing apitrace, but I'll have to verify if I can redistribute the binaries.

**Comment by okias** [comment]
few more unknown calls I noted:
```
apitrace: warning: unknown function "glViewportSwizzleNV"
apitrace: warning: unknown function "glDrawMeshTasksNV"
apitrace: warning: unknown function "glDrawMeshTasksIndirectNV"
apitrace: warning: unknown function "glMultiDrawMeshTasksIndirectNV"
apitrace: warning: unknown function "glMultiDrawMeshTasksIndirectCountNV"
```

**Comment by jrfonseca** [comment]
Thanks for confirming it works.

Concerning the unknown calls, these messages are often harmless.  What happens is that nowadays apps use GL loaders which call `glXGetProcAddress` to get pointers for every single possible function, which those which are never used.  apitrace always warns, as it has no way to now if these functions are or not used.

We can add the specs for these functions. But it takes time to go through the extensions, and time I lack.

In particular, these are NVIDIA specific functions, as opposed to EXT/ARB official functions, so odds they are used are lower.
