### ISSUE TITLE
How can I dump dx shader binary not assembly code?

### ISSUE THREAD

**Issue by zz817** [apitrace/apitrace#840]
Hi, all

I want support dump shader binary for d3d11 via qapitrace.
And I write some codes in function MainWindow::customContextMenuRequested and save pShaderBytecode content to file.
The file saved sucessful but it is assembly code.

Maybe I missing something and this feature this supported already.
If not, how can I dump shader binary?

Thanks,
Nelson

**Comment by jrfonseca** [comment]
I made this possible by passing the `--blobs` option to  `apitrace dump`, for example

    apitrace dump --blobs foo.trace

It will output something like

    12345 ID3D11Device::CreateVertexShader(this = ..., pShaderBytecode = blob("blob_call12345.bin"), BytecodeLength = ..., pClassLinkage = NULL, ppVertexShader = &...) = S_OK

The shader binaries are written to `blob_call12345.bin` where 12345 should be replaced with the whatever call used for the shader binar.y

This will dump lots of binaries.  You can restrict this by `--calls=12345` option.

You'll need an apitrace built after 5643863f64e5d6217410a119d4fb4070c3982edf.  If you can't build apitrace yourself, wait 24hrs, and new binaries should pop up at the usual place.

**Comment by zz817** [comment]
Thanks, I will have a try for it.
