### ISSUE TITLE
[d3d9] Secret World Legends launcher replay renders 0 frames

### ISSUE THREAD

**Issue by Blisto91** [apitrace/apitrace#845]
I'm unsure if this is a bug or I'm missing something/doing something wrong, but thought I'd make an issue.

I've made a apitrace on Windows of the [Secret World Legends](https://mega.nz/file/AkRSiLQa#48-9ywH-yrTIKHVHUchH8weThS6Fs4bWWSP6X5ek_Ow) launcher using apitrace 11.1 by dropping the d3d9 dll next to the exe as i usually do. It's to help debugging [a dxvk issue.](https://github.com/doitsujin/dxvk/issues/3116) 
Tho when i replay the trace it will just show a a window with a white background and then later end saying
```
warning: unexpected end of file while reading trace
Rendered 0 frames in 11.1807 secs, average of 0 fps
```
This is both when replaying on native Windows and Linux with 11.1 or latest git.

Link to captured trace: https://mega.nz/file/AkRSiLQa#48-9ywH-yrTIKHVHUchH8weThS6Fs4bWWSP6X5ek_Ow

**Comment by jrfonseca** [comment]
What's happening is that this game is not presenting directly to screen.  Instead it's rendering off-screen and reading back the rendering pixels:

```
> apitrace  dump ClientPatcher.trace
[...]
1133 IDirect3DDevice9::EndScene(this = 0x7b2f640) = D3D_OK
1134 IDirect3DTexture9::GetSurfaceLevel(this = 0x7ce7d00, Level = 0, ppSurfaceLevel = &0x7c5d3c0) = D3D_OK
1135 IDirect3DDevice9::GetRenderTargetData(this = 0x7b2f640, pRenderTarget = 0x7c533e0, pDestSurface = 0x7c5d3c0) = D3D_OK
```

I presume it renders the readback pixels using GDI.  Why it does this I don't know, but this is usually very inefficient compared with presenting directly to screen.

AFAICT, everything was still captured.  You can still inspect the rendering by opening the trace with qapitrace, and double clicking on the GetRenderTargetData calls.

I don't see anything else that an be done better here.  The app is the one doing something weird.

**Comment by Blisto91** [comment]
Ah i see thank you 🙂 👍
