### ISSUE TITLE
GL_ATI_meminfo state: 4 integers instead of 1

### ISSUE THREAD

**Issue by stgatilov** [apitrace/apitrace#848]
While trying to glretrace my game on AMD RX 550 with VS2022 x64 Debug, I get stack corruption around `texture_free_memory_ati` variable:
```
        // GL_TEXTURE_FREE_MEMORY_ATI
        {
            flushErrors();
    GLint texture_free_memory_ati = 0;
    glGetIntegerv(GL_TEXTURE_FREE_MEMORY_ATI, &texture_free_memory_ati);
            if (glGetError() != GL_NO_ERROR) {
                flushErrors();
            } else {
                writer.beginMember("GL_TEXTURE_FREE_MEMORY_ATI");
    writer.writeInt(texture_free_memory_ati);
                writer.endMember();
            }
        }
```

Looking at the [specs for GL_ATI_meminfo extension](https://registry.khronos.org/OpenGL/extensions/ATI/ATI_meminfo.txt), glGetIntegerv returns 4 integers instead of 1 for all three states.

**Comment by stgatilov** [comment]
Here is the fix: https://github.com/apitrace/apitrace/pull/849

**Comment by jrfonseca** [comment]
Good catch.  Thanks
