### ISSUE TITLE
ASSERT: "0" in qubjson.cpp, line 284 with wine64 + apitrace-win64-x86

### ISSUE THREAD

**Issue by q4a** [apitrace/apitrace#867]
Hi. I'm not sure, if it's related to https://github.com/apitrace/apitrace/issues/823 but I got error:
`ASSERT: "0" in file D:\a\apitrace\apitrace\gui\qubjson.cpp, line 284`
Full log here: [64bit-trace.txt](https://github.com/apitrace/apitrace/files/11111790/64bit-trace.txt)

Steps to reproduce:
- I'm using ubuntu 22.04 + Wine 64: just installed `winehq-stable` using this instructions: https://wiki.winehq.org/Ubuntu
- Download and unpack [apitrace-win64-x86.zip](https://github.com/apitrace/apitrace/suites/11560306421/artifacts/598615099) from [github actions](https://github.com/apitrace/apitrace/actions/runs/4419374849)
- Run command like: `wine64 /home/q/soft/apitrace/bin/qapitrace.exe ./d3d9-garfield-panfrost-bifrost.trace` (my trace:
[d3d9-garfield-panfrost-bifrost.trace.tar.gz](https://github.com/apitrace/apitrace/files/11111874/d3d9-garfield-panfrost-bifrost.trace.tar.gz) )
- And then in qapitrace menu: `Edit` - `Go to call` - `1000`, `Trace` - `Lookup state`
- Got error message and crash.

`apitrace-win32-x86.zip` from same github actions page works fine (without error):
[32bit-trace.txt](https://github.com/apitrace/apitrace/files/11111788/32bit-trace.txt)

Some system info:
```
q@mono:~/Downloads$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
q@mono:~/Downloads$ uname -a
Linux mono 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
q@mono:~/Downloads$ wine64 --version
wine-8.0
q@mono:~/Downloads$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: KABINI (kabini, LLVM 15.0.7, DRM 3.42, 5.15.0-69-generic) (0x9830)
    Version: 23.0.1
    Accelerated: yes
    Video memory: 1024MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 544 MB, largest block: 544 MB
    VBO free aux. memory - total: 3015 MB, largest block: 3015 MB
    Texture free memory - total: 544 MB, largest block: 544 MB
    Texture free aux. memory - total: 3015 MB, largest block: 3015 MB
    Renderbuffer free memory - total: 544 MB, largest block: 544 MB
    Renderbuffer free aux. memory - total: 3015 MB, largest block: 3015 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 1024 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 544 MB
OpenGL vendor string: AMD
OpenGL renderer string: KABINI (kabini, LLVM 15.0.7, DRM 3.42, 5.15.0-69-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.0.1 - kisak-mesa PPA
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.0.1 - kisak-mesa PPA
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.0.1 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by jrfonseca** [comment]
This ASSERT happens when the underlying d3dretrace.exe process crashes, from 64bit-trace.txt:

    Running: "d3dretrace" "-D" "1000" "--dump-format" "ubjson" "./d3d9-garfield-panfrost-bifrost.trace"

I ran here with a slightly different wine version (wine-6.0.3 Ubuntu 6.0.3~repack-1) 

    wine64 d3dretrace.exe -D 1000 d3d9-garfield-panfrost-bifrost.trace

but it didn't crash.  If you run it on your system I suspect it will.  And if you run it under [catchsegv](https://github.com/jrfonseca/drmingw#catchsegv) it should dump a nice stack trace, which should tell where the crash is happening -- apitrace or the drivers.  My guess is the drivers.


I need to update qapitrace to report a more informative error.

**Comment by jrfonseca** [comment]
I fixed the misleading error message with https://github.com/apitrace/apitrace/commit/f8b94fc135544766665e190803dc8b8d9b9c1dad.

There's nothing else for me to do here.
