### ISSUE TITLE
If I want to upgrade apitrace's support for OpenGL to version 4.6

### ISSUE THREAD

**Issue by BuryFlowers** [apitrace/apitrace#878]
Do I just have to upgrade the new extensions and functions to "glapi.py", and set types like GLtexture or GLlocation correctly?

Is there any extra work I have to do?

**Comment by jrfonseca** [comment]
Sorry for the silence.  Very little time for apitrace maintaince lately.

There are some instructions on https://github.com/apitrace/apitrace/blob/master/specs/scripts/README.markdown

In short, the idea is to use the scripts in that directory to get most of the grunt work done, then do some manual adjustments.

That's normally enough to get tracing to work.  Retracing might some times require more handholding.
