### ISSUE TITLE
Can Apitrace support retrace through EGL on Windows

### ISSUE THREAD

**Issue by mmmmmoria** [apitrace/apitrace#885]
Hello

   I’ve noticed that apitrace always uses WGL as the middleware for replay on the Windows platform, and there are no others configurable options available. I would like to use EGL instead of WGL, and I’ve tried both the master and angle’s branch, but there still seem to be some issues.  I’m wondering if apitrace will support egl replay on Windows in the future.

In another way,  I've tried `apitrace trace --api egl` to generate a trace file on Linux while it couldn't be replayed by glretrace nor eglretrace. Are there any other parameters that need to be configured？

Best Regrads!

**Comment by mmmmmoria** [comment]
What's more, on Linux,  I just 

    export LD_PRELOAD=/lib/aarch64-linux-gnu/apitrace/wrappers/egltrace.so
    apitrace trace --api egl glmark2
    apitrace replay glmark2.trace

then I got "error: unavailable function glXQueryVersion"

**Comment by jrfonseca** [comment]
Sorry, not supported.  See https://github.com/apitrace/apitrace/issues/522#issuecomment-848989942
