### ISSUE TITLE
[enhancement] replace zlib

### ISSUE THREAD

**Issue by okias** [apitrace/apitrace#896]
zlib is slow, old, unmaintained.

In general, usage is of `zlib` itself is not recommended, because the codebase is ancient and the library miss all assembly optimization. See the issues: https://github.com/madler/zlib/issues

Currently is mostly used only in legacy code.
Options:

1. https://github.com/zlib-ng/zlib-ng/ (most easiest drop-in solution is to use, thou not reaching [libdeflate performance](https://github.com/zlib-ng/zlib-ng/issues/1486))
2. https://github.com/ebiggers/libdeflate (while keeping the zlib compression)
3. or just replace crc32 routine and drop zlib at all (we can't do for opening the older files I think)

Even drop in replacement for a zlib-ng would [drastically](https://github.com/zlib-ng/zlib-ng/releases/tag/2.1.2) improve performance, thou is questionable how many traces compressed with it are outside and regularly used.

**Comment by jrfonseca** [comment]
> [...], thou is questionable how many traces compressed with it are outside and regularly used.

Precisely: Zlib is only kept around for legacy traces.  By default apitrace records with Snappy, and for long term storage the recommendation is Brotli.

I'd rather not spend time with zlib...
