### ISSUE TITLE
eglQueryDevicesEXT egl spec definition wrong 

### ISSUE THREAD

**Issue by per-mathisen-arm** [apitrace/apitrace#909]
In specs/eglapi.py the eglQueryDevicesEXT function is defined as

`GlFunction(EGLBoolean, "eglQueryDevicesEXT", [(EGLint, "max_devices"), Out(Array(EGLDeviceEXT, "max_devices"), "devices"), Out(Array(EGLint, "max_devices"), "num_devices")], sideeffects=False),`

however, I am quite sure from reading the spec (https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_device_enumeration.txt) that the last parameter is wrong and will lead to reading memory it shouldn't, as it is not an array and it should probably rather be defined as

`Out(Pointer(EGLInt), "num_devices")`

instead.

**Comment by jrfonseca** [comment]
Indeed!  Thank you.
