### ISSUE TITLE
How to show all textures?

### ISSUE THREAD

**Issue by W31RD-0** [apitrace/apitrace#928]
![image](https://github.com/user-attachments/assets/2a9d07a8-dc63-4f47-bc02-ee81e50870e8)
for some reason, qapitrace only shows 1 image with varying quality, and not other things that are on the screen. is there an option to show everything on screen?

**Comment by jrfonseca** [comment]
qapitrace only shows the textures currently bound.

There's currently no means to show all textures that exist.  There's no plan to do so: there's normally lots and lots of textures, so dumping them all would make qapitrace very slow.
