### ISSUE TITLE
Where should I start if I want to write a tool myself

### ISSUE THREAD

**Issue by wormtql** [apitrace/apitrace#933]
Some games detect and prevent capturing like RenderDoc or Nsight Graphics.
So if I wish to get around these detectings, or maybe I cound write a customized dll interceptor.
But I'm not understanding the capturing principles very well, so if I want to learn the methods, which part of the code should I start

**Comment by jrfonseca** [comment]
I suggest  you first start from reading up on https://github.com/apitrace/apitrace/blob/master/docs/HACKING.markdown#further-reading

If you're specifically about Windows DLLs, then the key section of the code is https://github.com/apitrace/apitrace/tree/master/inject , especially read up on the resources mentioned on https://github.com/apitrace/apitrace/blob/master/inject/injector.cpp

ApiTrace doesn't use it yet, but modern DLL injection tools would probably use https://github.com/microsoft/Detours


Avoiding detection is a different level altogether.  I don't have experience, but I reckon it will be a cat-and-mouse game, where every (anti-)injection step and by counteracted.
